>DL;NY045_Aegopogon_clean-4691_IDAU
NY045_Aegopogon_clean-4691_IDAU
ctattggtgtcctgactgcttgggctgtggccacggcgtcccccgtgatc
gccgctggacaggttaggtttccaggcttaatgcgagatagtggtttcgt
ctggaaataattttggtttggattgaatgtgtgaaccggtggttggtttc
cactcgctactgctgcctatctagttggcatattgtggcatttaggaaag
tatctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagcta---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;055_Aegopogon_clean-4691_IDAU
055_Aegopogon_clean-4691_IDAU
-----------ctggctgcttgggctgtggccacggcgtcccccgtgatc
gctgccggtcaggttaggtttccaggcttaatgcgagatagttgtttcgt
ctggaaataattttggtttggattgaatgtgtgaaccggtggttggtttc
cactcgctactgctgcctatctagttggcgtattgtggcatttaggaaag
tatctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagggttgagtagcatgcgacctatgttcaattgcca
ttaccatgtatgccgctgatgatgctcattgggtttcgaacatatgcttc
tgctcaggggtggacttctccaatgcagtcctagatagggtaaatttcgg
gaaggcaaatctgaaaggtgctttgttcaagaacacagtgctatctggat
ctaccttcgatgatgcccagttgcaagacgcagtttttgacgacacaatc
attggctatattgatcttcagaagctttgcaccaatacaacaattactga
agac*
>DL;NY033_Spruceana_clean-4691_IDAU
NY033_Spruceana_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------gcggca-ttaggaaag
gatctgctcgttcggttcaatttagctgtgtcctttctctgcagactagg
ctacctccactatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacgataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgatggtgcgga---------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;NY031_Spruceana_clean-4691_IDAU
NY031_Spruceana_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
-------------------ggattgaatgtgtgaactgggggttggtttc
cactcgctaatgctgcttaccttgttggcgtattgcggca-ttaggaaag
gatctgctcgttcggttcaatttagctgtgtccttcctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacaagcgtttgttgg
aaacacgataggacaggctaatggtgtttatgataagcccatcgatctcc
gcttctgtgactacacgaacgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgatggtgcggacatgtctga
ggttgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttctttatccgagagttgcatagcttgggacctacgttcaattgcca
ttaccatgtatg--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;044_Aegopogon_clean-4691_IDAU
044_Aegopogon_clean-4691_IDAU
-------tgtcctggctgcttgggctgtggccacggcgtcccccgtgatc
gctgccggtcaggttaggtttccaggcttaatgcgagatagttgtttcgt
ctggaaataattttggtttggattgaatgtgtgaaccggtggttggtttc
cactcgctactgctgcctatctagttggcgtattgtggcatttaggaaag
tatctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagggttgagtagcatgcgacctatgttcaattgcca
ttaccatgtatgccgctgatgatgctcattgggtttcgaacatatgcttc
tgctcaggggtggacttctccaatgcagtcctagatagggtaaatttcgg
gaaggcaaatctgaaaggtgctttgtt-----------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;066_Aegopogon_clean-4691_IDAU
066_Aegopogon_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------ctatctagttggcgtattgtggcatttaggaaag
tgtctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggaccccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagggttgagtagcatgcgacctatgttcaattgcca
ttaccatgtatgccgctgatgatgctcattgggtttcgaacatatgcctc
tgctcaggggtggacttctccaatgcagtcctagatagggtaaatttcgg
gaaggcaaatctgaaaggtgctttgttc----------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;NY030_Spruceana_clean-4691_IDAU
NY030_Spruceana_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------tgttggcgcattgcggca-ttaggaaag
gatctgctcgttcggttcaatttagctgtgtcctttctctgcagactagg
ctacctccactatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacgataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcactgatgtctgatgcaaagttcgacggcgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgt-----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;014_Aegopogon_clean-4691_IDAU
014_Aegopogon_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
----------------------------------------ggttggtttc
cactcgctactgctgcctatctagttggcatattgtggcatttaggaaag
tatctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagggttgagtagcatgcgacctatgttcaattgcca
ttaccatgtatgccgctgatgatgctcattgggtttcgaacatatgcttc
tgctcaggggtggacttctccaatgcagtcctagatagggtaaatttcgg
gaaggcaaatctgaaaggtgctttgt------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;NY028_Spruceana_clean-4691_IDAU
NY028_Spruceana_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------gctatcgacggagcccaatcgctgtgaacaagcgtttgttgg
aaacacgataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcactgatgtctgatgcgaagttcgacggcgcggacatgtctga
ggtcgtgatgtcaaaagcttat----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;42_Angustifolia_clean-4691_IDAU
42_Angustifolia_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
---------------gtttggattgaatgtgtgaaccggtggttggtttc
cactcgctactgctgcctatctggttggcgtattgtggcatttaggaaag
tatctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagggttgagtagcatgcgaccta-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;050_Aegopogon_clean-4691_IDAU
050_Aegopogon_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------agttggcgtattgtggcatttaggaaag
tatctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagggttgagtagcatgcgacctatgttcaattgcca
ttaccatgtatgccgctgatgatgctcattgggtttcgaacatttgcttc
tgctcaggggtggacttctccaatgcagtcctagatagggtaaatttcgg
gaaggcaaatctgaaaggtgctttgttcaagaac----------------
-------cagtgttgttagggcgctaaggcgcacttgaggcgaggaggcc
ttccatcgcccgaggcgctaggcgctaggc--------------------
----*
>DL;NY016_Kunhardtii_clean-4691_IDAU
NY016_Kunhardtii_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------ctcattcgattcagtgtagatgtgtcctttctctgcaggttagg
ttacctccactatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaatacgataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagagttgagtatcatgcgacctaggt----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;G35_Ramboi_clean-4691_IDAU
G35_Ramboi_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--cgatcttaggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgcgactacacgaatgagaaatctaacctcaaaggaaagtcactc
gcagctgcactgatgtctgatgcaaagttcgacggagcggacatgtctga
ggtagtgatgtctaaagcttatgccgtcggagctagctttaaaggtaatc
tctttctttgtctcagagttgcatggcatgcaacttagtt-caattgccg
tcaccatgtacgccgttga-------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;A30_Aspera_clean-4691_IDAU
A30_Aspera_clean-4691_IDAU
--------------------------------------------------
-----------------------------ttcatgcgagagtcgtttcat
ctggaactgttggttgattggattgaatgtgtgaactgggggttggtttc
cactcgctaatgctgcttaccttgttggcgtattgcggca-ttaggaaag
gatctgctcgttcggttcaatttagctgtgtcctttctctgcagactagg
ctacctccactatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacgataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcactgatgtctgatgcgaagttcgacggcgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgttggagctagctttaagggtaaac
tctttctttatctgagaattgtgtagcatgcgacctacgtttagtcgcca
ttaccatggacgccgctgactgtgtgcattgggtttcgaacatgcgcttc
tgctcaggggtggacttctctaatgcagtcctagatagggtaaacttcgg
gaaggcaaatctgcaaggtgctttgt------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;A37_Exasperata_clean-4691_IDAU
A37_Exasperata_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------t
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
cctttcttggtccgataattttatt-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
>DL;003_Aegopogon_clean-4691_IDAU
003_Aegopogon_clean-4691_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------ggaaag
tatctgctcgttcggttcaatttagacatgtcctccctctgcagattagg
ctacctccgctatcgacggagcccaatcgctgtgaacgagcgtttgttgg
aaacacaataggacaggctaatggtgtttatgataagcccatcgatctcc
gtttctgtgactacacaaatgagaaatctaacctcaaagggaagtcgctt
gcggctgcgctgatgtctgatgcaaagttcgacggtgcggacatgtctga
ggtcgtgatgtcaaaagcttatgccgtcggagctagctttaagggtaacc
tctttccttatctgagggttgagtagcatgcgacctatgttcaattgcca
ttac----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----*
