>DL;092_Barbigera_aff_clean-5090_BZDF
092_Barbigera_aff_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
-----------------------------ctcgtgacaggggctgcgagg
ctcactccggtggtacttcttctctgttcgtcgattccaggatctttttt
ttctttcttttcttttttggggtgtttaggtgatggaagtgatgattgaa
tgttccatttgcaggggatgtgttgctgcactgtgtggtggatgccactt
tgggggctctgggcc-tcctgatattggccagatcttccctgacaatgat
cctaagtggaagggagctctttccgcggtctttgtcgccgaagctgtgag
tcagcacatggttttggttgtcattgttttttt---ggtttcccttaatg
actgattatcattatccttggagtgttctttgtgtgtacaatttgaaaag
aaacccgtggctgtttttctttttttaacttattggatgcctgtggctgt
tgttcttaggagacggtgaag-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;G14_Albescens_clean-5090_BZDF
G14_Albescens_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
-----------------------------ctcatgacaggggctgcgagg
ctcactccgatggtacgtctgctctgttcatcgatttcagggattctttt
tt--------tttttttttgggtgtttaggtggtggaagtgatgattgaa
tgttccatttgcaggggatgtgttgctgcactgtgtggtggatgccattc
tgggggctctgggccttcctgatattgggcagatcttccctgacaatgat
cctaagtggaagggagctccttccgcggtcttcgtcgcggaagctgtgag
tcagcacatggttttggttgtcattgtttttttgtgggtttcctttatta
-------atgatcattcctggagtgttcttggtgtgcacaattcgatagg
caacccatggctgtt-----------------------------------
-gttcctaggagatggtgaataaattatgtggttgatgatattgtcggtt
gggac-aagcacttcttatggatttccattttttgggcatttttctgttc
tttagtatgtgtcctccatgggaaatttgggcaaagctaaaaattttcaa
actttttttccctgctacaataacttatgatgcttatgtaaagtgggtgc
gcagaattccatttgtttt*
>DL;NY011_Catharinae_2_clean-5090_BZDF
NY011_Catharinae_2_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------ttg
tc-----------------------------------------------a
agtctcatttccatcggccattctatttttcatgtagggaaatggttttg
atgtggccatattgggtcatgatactatt---------------------
--------------gtttctttctcttctcaggtccgactcatgcacgag
gcaggctacgagattggtaacttggacgctacc---ttgattctccagcg
gccgaaggtcagtccccacaaggagaacatc-cgggcgaacctcgccaag
ttactcgcagccgacctctcggttg-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;085_Aegopogon_aff_clean-5090_BZDF
085_Aegopogon_aff_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------tg
tc-----------------------------------------------a
agtgtcatttccatcggccattctatttttcatgtagggaaatggttttg
atgcggacatattgggtcatgatgctatt---------------------
--------------gtttccttctcttctcaggtccgactcatgcatgag
gcaggctacgagatcggtaacttggacgcaacc---ttgattctccagcg
gccgaaggtcagtccccacaaggagaacatc-cgggcgaacctcgccaag
ttactcggagccgacctctcggtcgtaaaccttaaggcg-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;NY009_Duidae_2_clean-5090_BZDF
NY009_Duidae_2_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------ttagggaaatggttttg
atgcggccatattgggtcatgatac-------------------------
---------------tttctttctcttctcaggtccgactcatgcacgag
gcaggctacgagattggtaacttggacgctacc---ttgattctccagcg
gccgaaggtcagtccccacaaggagaacatc-cgggcgaacctcgccaag
ttactcggagccgacctctcggttgtaaaccttaaggcga----------
-agacag-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;NY053_Fraterna_clean-5090_BZDF
NY053_Fraterna_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------ccatcggccattctatttttcatgtagggaaatggttttg
atgcggccatattgggtcatgatac-------------------------
---------------tttctttctcttctcaggtccgactcatgcacgag
gcaggctacgagattggtaacttggacgctacc---ttgattcttcagcg
gccgaaggtcagtccccacaaggagaacgtc-cgggcaaacctcgccaag
ttacttggagccgacctctcggtcgtaaaccttaaggcga----------
-agacccatgagaaagtcgacagcctcggggagaaccg------------
------gagcatcgc-----------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;F41_Edmundoi_clean-5090_BZDF
F41_Edmundoi_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------ctttg
tc-----------------------------------------------a
agtgtcgttcccatcatccagtctacttttcatgtagggaaatggttttg
atgctgccatatttggttgtgatactatt---------------------
--------------gtttctttctcttctcaggttcgactcatgcacgag
gcaggctacgagattggtaacttggacgctacc---ttgattctccagcg
tccgaggatcagtccccacaagaagaacatc-cgagcgaacctcgccaag
ttactcggagccgacctttcggtcgt------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;NY081_Papyrus_clean-5090_BZDF
NY081_Papyrus_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------ccatcggccattctatttttcatgtagggaaatggt----
-----gccatattgggtcatgatgctatt---------------------
--------------gtttccttctcttctcaggtccgactcatgcatgag
gcaggctacgagatcggtaacttggacgcaacc---ttgattctccagcg
gccgaaggtgagtccccacaaggagaacatc-cgggcgaacctcgccaag
ttactcggagccgacctctcg-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;088_Sp3_clean-5090_BZDF
088_Sp3_clean-5090_BZDF
gagaccccgtcgtggcgccccccatgtcctccccccagccggaggtgctt
cctttcagggtcggtcacgggtttgacctgcataggttagagcccggtta
tcccctgatcatcggcgggatcgatattcctcatgacaggggctgcgagg
ctcactccgatggtacttcttctctgttcgtcgattccaggatctttttt
tt-tttcttttcttttttggggtgtttaggtgatggaagtgatgattgaa
tgttccatttgcaggggatgtgttgctgcactgtgtggtggatgccactt
tgggggctctgggccttcctgatattggccagatcttccctgacaatgat
cctaagtggaagggagctctttccgcggtctttgtcgccgaagctgtgag
tcagcacatggttttggttgtcattgttttttt---ggtttcccttaatg
actgattatcattatccttggagtgttctttgtgtgtacaatttgaaaag
aaacccgtggctgtttttctttttttaacttattggatgcctgtggctgt
tgttcttaggagacggtgaagaaattatgtgtttgatgatattgtcggtt
gggacgaagcacttcttatggatttccagttttt-ggcatccttgtattc
tttagtctgcttcgtctatgggaagtattggcaaagct------------
--------------------------------------------------
-------------------*
>DL;G27_Desmocelis_clean-5090_BZDF
G27_Desmocelis_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------aactcgtacgatgtttccctgcggatgataat----
---ggactgaattctactctgacact------------------------
---------------gttgtttcttttctcaggtccggctcatgcacgag
gcaggttacgagatcggcaacttagacgctacc---ttgattctccagag
accgaaaatcagcccccacaaggagaccatc-cgggcgaacctcgccaag
ttactcggagtcgaactctcggttgtaaatcttaaggcga----------
-agacccacgagaaagttgacagcctcggcgagaaccg------------
------gagcatcgcc----------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;NY050_Fraterna_clean-5090_BZDF
NY050_Fraterna_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------ttctttg
tc-----------------------------------------------a
agtgtcatttccatcggccattctatttttcatgtagggaaatggttttg
atgcggccatattgggtcatgatac-------------------------
---------------tttctttctcttctcaggtccgactcatgcacgag
gcaggctacgagattggtaacttggacgctacc---ttgattctccagcg
gccgaaggtcagtccccacaaggagaacatc-cgggcaaacctcgccaag
ttacttggagccgacctctc------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
>DL;NY010_Catharinae_clean-5090_BZDF
NY010_Catharinae_clean-5090_BZDF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------catcggccattctatttttcatgtagggaaatggttttg
ctgtggccatattgggtcatgatactatt---------------------
--------------gtttctttctcttctcaggtccgactcatgcacgag
gcaggctacgagattggtaacttggacgctacc---ttgattctccagcg
gccgaaggtcagtccccacaaggagaacatc-cgggcgagcctcgccaag
ttactcgcagccgacctctc------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------*
