>DL;A29_Angustifolia_clean-5138_WMUK
A29_Angustifolia_clean-5138_WMUK
ttgtctcaatctcatgccgtgctgattcgtgattttaatggttcgtacag
gaattgtttatccctgctaggactgggattgttcggtcctaatggcgcgg
atgcataatgtaagttcctgtttagtacttgtttgggtttcggttatcgg
tgttattgtcggggcttctagatca-tttttttgctgcgaacatggcggc
gattttccatcagaaaaggaagagggcgtttgtgaagccggttgtgaaga
caccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagagggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtcttgtaggtctt
gtaaaaacatct--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------*
>DL;092_Barbigera_aff_clean-5138_WMUK
092_Barbigera_aff_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------atgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccaggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatgttggagttaattctggc--atgtctagtaggtctt
gtaaaaacatctcgttcgttcgtt--------------actgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggaccc-------
--------------------------------------------------
--------------------------------------------------
---------------*
>DL;NY059_Llanorum_clean-5138_WMUK
NY059_Llanorum_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
-----------------------agtacttgtttgggtttc---------
-------gtcggggcttctagatca-tttttttgctgc-------gtggc
aattttccatcagaaaaggaagagggcgtttgtgaagccagttgtgaaga
cgccgaagcatgtcgttcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaatcctggcatatgtatagtaggtctt
gtaaaaacatctcgttcgttcgttaacatctcgatttcactgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcgaaaacagatgctgcgccatacttac--
--------------------------------------------------
---------------*
>DL;126_Bruniana_clean-5138_WMUK
126_Bruniana_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------t
cgccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatc---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------*
>DL;NY090_Barbigera_clean-5138_WMUK
NY090_Barbigera_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--tccgatcttgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgttaacatctcgatttcactgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcgtatt---------------------------------
--------------------------------------------------
---------------*
>DL;NY088_Barbigera_clean-5138_WMUK
NY088_Barbigera_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------gtgaaga
cgccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcataa--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------*
>DL;NY051_Llanorum_clean-5138_WMUK
NY051_Llanorum_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
----------------------------------gggtttc---------
-------gtcggagcttctagatca-tttttttgctgc-------gtggc
aattttccatcagaaaaggaagagggcgtttgtgaagccagttgtgaaga
cgctgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgttaacatctcgatttcactgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcga--------------------------
--------------------------------------------------
---------------*
>DL;095_Barbigera_clean-5138_WMUK
095_Barbigera_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
-----------------ctgtttagtacttgtttgggtttc---------
-------gtcggggcttctagatcattttttttgctgc-------gtggc
aattttccatcagaaaaggaagagggcgtttgtgaagccagttgtgaaga
cgccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcaagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgttaacatctcgatttcactgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcgaaaacagatgctgcgccatacttacgt
gtcgcaaggacgcctcaaggtccaacacttacttttaagatcgaggaata
tgctttggcaactga*
>DL;NY085_Verticillaris_clean-5138_WMUK
NY085_Verticillaris_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------agcatgtcgatcacgtaacgggggataagattccaaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcagcttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgtttgttaacatctcgatttcactccaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcg---------------------------
--------------------------------------------------
---------------*
>DL;NY086_Barbigera_clean-5138_WMUK
NY086_Barbigera_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgttaacatctcgatttcactgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcgaaaacagatgctgcgccatacttacgt
gtcgcaaggacgcctcaaggtccaacacttacttttaagatcgaggaa--
---------------*
>DL;107_Sp7_clean-5138_WMUK
107_Sp7_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------ccagttgtgaaga
cgccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccaggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgttaacatctcga----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------*
>DL;018_Barbigera_clean-5138_WMUK
018_Barbigera_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------ttgtgaagccagttgtgaaga
cgccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgtt--------------actgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcgaaaacagatgctgcgccatacttacgt
gt------------------------------------------------
---------------*
>DL;F41_Edmundoi_clean-5138_WMUK
F41_Edmundoi_clean-5138_WMUK
--------------------------------------------------
-----------actgggattgtttaggattgttcggtcttaatggcgcgg
atgcataatgtaagttcctgtttagtacttgtttaggtttc---------
-------gtcggggcttctagatcattttttttgctgc-------gtggc
aattttccatcagaaaaggaagagggcgtttgtgaagccagttgtgaaga
cgccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccaggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgtttgttaacatctcgatttcactgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcgaaaacagatgctgc-------------
--------------------------------------------------
---------------*
>DL;NY089_Barbigera_clean-5138_WMUK
NY089_Barbigera_clean-5138_WMUK
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------ttgctgc-------gtggc
aattttccatcagaaaaggaagagggcgtttgtgaagccagttgtgaaga
cgccgaagcatgtcgatcacgtaacgggggataagattccgaagagtttt
gtgttctcgagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgttaacatctcgatttcactgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggaccc-------
--------------------------------------------------
--------------------------------------------------
---------------*
>DL;A10_Melastomoides_clean-5138_WMUK
A10_Melastomoides_clean-5138_WMUK
--------------------------------------------------
----------------------ttaggattgtt-ggtcttaatggcgcgg
atgcataatgtaagttcctgtttagttcctgtttgggtttc---------
-------gtcggggcttctagatca-tttttttgctgc-------gtggc
aattttccatcagaaaaggaagagggcgtttgtgaagccagttgtgaaga
cgccgaagcatgtcgatcacgtaacggggaataagattccgaagagtttt
gtgttctcaagggggaagttgccgggacctctgaggcaacttcagatgga
cttgagaaagttgatgcttccttttactgccctcaagctcaaggtataaa
attgttgtgttgatcttggagttaattctggcatatgtctagtaggtctt
gtaaaaacatctcgttcgttcgtt--------------actgcaggcgaa
caagaggaataatctcaaggacttcttgaatgtcgcaggacccatgggtg
tcaccaattttcttattctgtcgaaaacagatgctgcgccatacttacgt
gtcgcaaggacgcctcaaggtccaacactta-------------------
---------------*
