>DL;A29_Angustifolia_clean-5260_ARYD
A29_Angustifolia_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----agttgctgaaggtattggatttggccggatttgttatgtttcgttt
ggtatgaatttgaggctcacgtgcttgaaattggtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgact-ggcgttgtttaccgggcggcag
tttggatgaattgcgtgatttagtg-gaagtaattcga------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY055_Bipenicellata_clean-5260_ARYD
NY055_Bipenicellata_clean-5260_ARYD
ccagattattgtcgttttctgtttgtttcgatctgtgctggtcgtttcag
gatgagtttaggtgacttatg-attttttttgggtgtgggattgcttggg
gcaggtttgatatgcccgctccgacggtgaccccggagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgatgcgttccgttt
ggtatgaatttgaggcttac-tgcttg-ga-tcgtctctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgact-ggtgttgtttaacgggtggcag
tttggatgaattgcatgatttagtg-aaaagagttcgatgatttgttatg
tttcgtttggtgtgaatttgaggcttacttgcttggattcgtcgctgcag
ttgaggaatgtcattgatccgaagaggcactacaagaagagcgactctaa
atcgaaggcgctgcccaagtatttccaggtgaccggcgttgttgaccggg
tggcagtttggatgaattgcatgatttagtgaaagtaattcgattctgtt
gtttatgtggggcagatcggcacagtgatagagccttccacgg-------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY017_Llanorum_2_clean-5260_ARYD
NY017_Llanorum_2_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------gatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttgaaattggtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgaat-ggcgttgtttaccgggcggcag
tttggatgaattgcgtgatttagtg-gaagtaatttgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatg-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;092_Barbigera_aff_clean-5260_ARYD
092_Barbigera_aff_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
------------------------------cccctgagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttg-gattcgtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcactgcccaagtatttccaggtgact-ggtgttgtttaacgggtggcag
tttggatgaattgcgtgatttagtg-aaaataattcggt-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatttgggataggttggcacggtgatagagccatacacggagctcta
cagcggcaggctctccaagaaggagaggaaagccacgcttg---------
--------------------------------------------------
--------------------*
>DL;098_Verticillaris_clean-5260_ARYD
098_Verticillaris_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------ttt
ggtatgaatttgaggcttacatgcttg-ga-tcgtctctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcaaaatcgaag
gcagtgcccaagtatttccaggtgact-ggtgttgtttaacgggtggcag
tttggatgaattgcgtgatttagtg-aaaataata---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY040_Bipenicellata_clean-5260_ARYD
NY040_Bipenicellata_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------cccgctccgacggtgacccctgagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgatacgtttcgttt
ggtatgaatttgaggcttacatgcttg-ga-tcgtctctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgact-ggtgttgtttaacgggtggcag
tttggatgaattgcatgatttagtg-aaaagagttcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgt-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY059_Llanorum_clean-5260_ARYD
NY059_Llanorum_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
------------------------------------------------at
cttcagttgctgaaggtattggatctggccggatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttgaaattggtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgaat-ggcgttgtttaccgggcggcag
tttggatgaattgcgtgatttagtg-gaagtactttgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY090_Barbigera_clean-5260_ARYD
NY090_Barbigera_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------ttgctgaaggtattggatctggccggatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttgaaattggtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgaat-ggcgttgtttaccgggcggcag
tttggatgaattgcgtgatttagtg-gaagagatcgaag-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------agcgtc
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY051_Llanorum_clean-5260_ARYD
NY051_Llanorum_clean-5260_ARYD
--------------------------------------------------
----------------------ttttcttttgggtgtgatattgcttggg
gcaggtttgatatgcccgctcccacggtgacccctgagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttg-gattcgtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgact-ggtgttgtttaccgggtggcag
tttggatgaattgcatgatttagtg-aaa---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY031_Spruceana_clean-5260_ARYD
NY031_Spruceana_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------tggccggattttcggcgtttcgttt
tggtatgaattggggcttacgtgtttg-gattcgtcgccgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcaaaatcgaag
gcgctgcccaagtatttccaggtgattcggcattgtttaacgggtggcag
tttggacgaattgcgtgatttggtg-aaaataattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttacgtggggcaggtcggcac---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY054_Bipenicellata_clean-5260_ARYD
NY054_Bipenicellata_clean-5260_ARYD
--------------------------------------------------
------------------------------------------------gg
gcaggtttgatatgcccgctcccacggtgacccctgagctgaagaaggat
cttcagttgctaaaggtattggatctggccggatttgttatgtttcgttt
ggagtgaatttgaggcttacgttcttg-gattcgtcgatgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactctaaatcgaag
gcgctgcccaagtatttccaggtgacc-ggcgttgttgaccgggtggcag
tttggatgaattgcatgatttagtg-aaagtaattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatgtggggcagatcggcacagtgatagagccttccacggagttcta
cagcggcaggctcaccaagaaggagaggaaggccacccttgcgg------
--------------------------------------------------
--------------------*
>DL;G30_Dubia_clean-5260_ARYD
G30_Dubia_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------ttgctgaaggtattggatttggctgtattttatgcgtttcgttt
ggtatgaa-ttgagccttacatgcttg-gatt------cacagttgagga
atgtcattgatccgaagaggcactacaaaaagagcgactcgaaatcaaag
gcgttgcccaagtatttccaggtgact-ggcattgtttaatgggtggcag
tttggaggaactgcgtgatttggtgtaaaataatttgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tc----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;090_Aegopogon_aff_clean-5260_ARYD
090_Aegopogon_aff_clean-5260_ARYD
--------------------------------------------------
----------------------------------------tttgcttggg
tcaggtttgatatgcccgctccgacggtgatcactgagctgaagaaggat
cttcagttgctgaaggtattgaatttcaccggatttgatacgtttcgttt
ggtatgaatttgaggcttacatgcttg-ga-tcgtctctgcagttgagga
atgtcatcgatccgaagaggcactacaagaagagcgactcgaaatcaaag
gcactgcccaagtatttccaggtgact-ggtgttgtttaacgggtggcag
tttggatgaattgcgtgatttagtg-aaaataattcggt-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatttgggataggtcggcagggtgatagagcca--------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;102_Sp7_clean-5260_ARYD
102_Sp7_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------tgataagtttcgttt
ggtatgaatttgaggcttacatgcttg-ga-tcgtctctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcactgcccaagtatttccaggtgact-ggtgttgtttaacgggtggcag
tttggatgaattgcgtgatttagtg-aaaataattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatttgggataggtcggcgcggtgatagagccatacacggagctcta
cagcggcaggctct------------------------------------
--------------------------------------------------
--------------------*
>DL;NY052_Striphnocalyx_clean-5260_ARYD
NY052_Striphnocalyx_clean-5260_ARYD
--------------------------------------------------
----------------------tttttttttgggtgtgggattgcttggg
gcaggtttgatatgcccgctccgacggtgaccccggagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttg-gattcgtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgacc-ggcgttgtttaccgggtggtag
tttggatgaattgcatgatttagtg-aaagtaattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatgtggggcaggtcggcacggtgatagagccttccacggagttcta
cagcggcaggctcaccaagaaggagaggaaggccacccttgcggatgagc
ttctggctgatcaaacccttaaggattacaggtgagtttcatagtcaaaa
tcgc----------------*
>DL;NY085_Verticillaris_clean-5260_ARYD
NY085_Verticillaris_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------ccgatcttgtttcgttt
tgtatgaatttgaggcttacgtacttg-gattcgtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgaat-ggcgttgtttaccgggtggcag
tttggatgaattgcgtgatttagtg-aaagtaattcaat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tgtgtt
gtttatgtggggcaggtcggcacggtgatagagccttccacgg-------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;NY053_Fraterna_clean-5260_ARYD
NY053_Fraterna_clean-5260_ARYD
-----------------------------------------------cag
gatgagtttaggtgatttatgatttttttttgggtgtgggattgcttggg
gcaggtttgatatgcccgctccgacggtgaccccggagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgttatggttcgttt
ggtatgattttgaggcttacgtgcttg-gattcgtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcactgcccaagtatttccaggtgacc-ggcgttgtttaccgggtggcag
tttggatgaattgcatgatttagtg-aaag--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------*
>DL;F41_Edmundoi_clean-5260_ARYD
F41_Edmundoi_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------ttggccggatttgttatgtttcgttt
agtatgaatttgaggcttacgtgcttgaaattggtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgact-ggcgttgtttaccgggcggcag
tttggatgaattgcgtgatttagtg-gaagtaattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatgtggggcaggtcggcacggtgatagagccttccacggagtttta
cagcggcaggctcaccaagaaggagaggaaggctacccttgcggatgagc
ttctggctgatcaaacccttaaggattacaggtgagttttgtagtca---
--------------------*
>DL;A30_Aspera_clean-5260_ARYD
A30_Aspera_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------gatatgcccgctccgatggtgacgcctgagctgaagaaggat
ctgcagttgctgaaggtatcggat-ttggccggttttatacgtttcgttt
tggtatgaattggggcttacgtaattg-gattcgtcgccgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcaaaatcgaag
gcgctgcccaagtatttccaggtgattcggcattgtttaacgggtggcag
tttggacgaattgcgtgatttggtg-aaaataattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtc
gtttacgtggggcaggtcggcacggtgatagagccttccacggagttcta
cagcagcaggctcaccaagaaggagaggaaggccacgcttgcggatgagc
ttctgtct------------------------------------------
--------------------*
>DL;131_Fraterna_clean-5260_ARYD
131_Fraterna_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
----------------------------gacccctgagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttgaaattggtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgaat-ggcgttgtttaccgggcggcag
tttggatgaattgcgtgatctagtg-gaagtaattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatgtggggcaggtcggcacggtgatagagccttccacagagtttta
cagcggcaggctcaccaagaaggagaggaaggctacccttgcggatgagc
ttctagctgatcaaacccttaaggat------------------------
--------------------*
>DL;A10_Melastomoides_clean-5260_ARYD
A10_Melastomoides_clean-5260_ARYD
--------------------------------------------------
------------------------------------------------gg
gcaggtttgatatgcccgctcccacggtgacccctgagctgaagaaggat
cttcagttgctgaaggtattggatttggccggatttgttatgtttcgttt
ggtatgaatttgaggcttacgtgcttgaaattggtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcgctgcccaagtatttccaggtgact-ggcgttgtttatcgggcggcag
tttggatgaattgcgtgatttagtg-gaagtaattcgac-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatgt-gggcaggtcggcacggtgatagagccttccacggagtttta
cagcggcaggctcaccaagaaggagaggaaggctaccctt----------
--------------------------------------------------
--------------------*
>DL;052a_Melastomoides_clean-5260_ARYD
052a_Melastomoides_clean-5260_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------tggatttcgccggatttgatacgtttcgttt
ggtatgaatttgaggcttacctgcttg-ga-tcgtctctgcagttgagga
atgtcatcgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcactgcccaagtatttccaggtgact-ggtgttgtttaacgggtggcag
tttggatgaattgcgtgatttagtg-gaagtaattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatgtggggcaggtcggcacggtgatagagccttccacggagtttta
cagcggcaggctcaccaagaaggagaggaaggc-----------------
--------------------------------------------------
--------------------*
>DL;NY050_Fraterna_clean-5260_ARYD
NY050_Fraterna_clean-5260_ARYD
--------------------------------------------------
-------------------------------------------------g
gcaggtttgatatgcccgctccgacggtgaccccggagctgaagaaggat
cttcagttgctgaaggttttggatttggccggatttgttacgtttcgttt
ggtatgattttgaggcttacgtgcttg-gattcgtcgctgcagttgagga
atgtcattgatccgaagaggcactacaagaagagcgactcgaaatcgaag
gcactgcccaagtatttccaggtgacc-ggcgttgtttaccgggtggctg
tttggatgaattgcgtgatttactg-aaagtaattcgat-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------tctgtt
gtttatgtggggcaggtcggcacggtgatagagccttccacggagttcta
cagcggcaggctcaccaagaaggagaggaaggccacccttgcggatgaac
ttctggctgatcaaacccttaaggattacaggtgagtttcatagtcaaaa
tcgcttggcaattcctgcga*
