>DL;A29_Angustifolia_clean-5594_BXBF
A29_Angustifolia_clean-5594_BXBF
--------------------------------------------------
------------------------gctctgccgcagggagaaggtcgaca
aggtcccccacttcagcttctacaagagcatggagaagatccacgaggag
gaggccataggacccgaccggctcatgggggacgtcctctactacgggga
caaccactcggcagtggagcagctgcacagcagggaggacgtggagaagc
tcatcgatgcccacaaggccgacgggaagctcctggtgctggacgtgggg
ctgaagcactgcggcccctgcgtgaaggtttacc----------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;NY055_Bipenicellata_clean-5594_BXBF
NY055_Bipenicellata_clean-5594_BXBF
--------------------------------------------------
-------------------cgggagctctgccgcagggagaaggtcgaca
aggtcccccacttcagcttctacaagagcatggagaagatccacgaggag
gaggccataggacccgaccggctcatgggggacgtcctctactacggaga
caaccactcggcggtggagcagctgcatagcagggaggacgtggagaagc
tcattgacgcccacaaggcggacgggaagctcctggtgctggacgtgggg
ctgaagcactgcggcccctgcgtgaaggtttacc----------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;G14_Albescens_clean-5594_BXBF
G14_Albescens_clean-5594_BXBF
--------------------------------------------------
------------------ctgggaactctgccgcagggagaaggtcgaca
aggtcccccacttcagcttttacaagagcatggagaagatccacgaggag
gaggccataggacctgaccggctcatgggggacgtcctctactacggaga
caaccactcggcggtggagcagctgcacagcagggaggacgtggagaagc
tcatggacgcccacaaagcggacgggaagctcctagtgctggacgtgggg
ctgaagcactgcgggccttgtgtgaaggtgagatcgga------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;NY040_Bipenicellata_clean-5594_BXBF
NY040_Bipenicellata_clean-5594_BXBF
--------------------------------------------------
-----------------------------------gggagatggtcgaca
aggtcccccacttcagcttctacaagagcatggagaagatccacgaggag
gaggccataggacccgaccggctcatgggggacgtcctctactacggaga
caaccactcggcggtggagcagctgcatagcagggaggacgtggagaagc
tcattgacgcccacaaggcggacgggaagctcctggtgctgggcgggggg
ctgaagcactgcggcccct-------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;NY031_Spruceana_clean-5594_BXBF
NY031_Spruceana_clean-5594_BXBF
--------------------------------------------------
------------------------------------------------ca
aggtcccccacttcagcttctacaagagcatggagaagatccacgaggag
gaggccatagggcccgaccggctcatgggggacgtcctctactacggaga
caaccactctgcggtggagcagctgcacagcagggaggacgtggagaagc
tcatcggagcccacaaggccgacgggaagctcctggtgcttgacgttggg
a-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;G30_Dubia_clean-5594_BXBF
G30_Dubia_clean-5594_BXBF
gtcgacctcagccgtacctgcggggatgtagatttcctactggtgatggg
ggacgagtccgagaagacccgggagctctgccgcagggagaaggtcgaca
aggtcccccacttcagcttttacaagagcatggagaagatccacgaggag
gaggccataggacctgaccggctcatgggggacgtgctctactacggaga
caaccactcggcggtggagcagctgcacagcagggaggacgtggagaagc
tcatggacgcccacaaagtggacgggaagctcctagtgctggacgtgggg
ctgaagcactgcgggccttgcgtgaaggtgtacccgacggtgatcaagct
atcgagacag----------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;NY030_Spruceana_clean-5594_BXBF
NY030_Spruceana_clean-5594_BXBF
--------------------------------------------------
-------------------------------------------gtcgaca
aggtcccccacttcagcttctacaagagcatggagaagatccacgaggag
gaggccatagggcccgaccggctcatgggggacgtcctctactacggaga
caaccactctgcggtggagcagctgcacaacagggaggacgtggagaagc
tcatcggagcccacaaggccgacgggaagctcctggtgcttgacgttggg
ctgaagcactgcggcccttgcgtga-------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;NY072_Aspera_clean-5594_BXBF
NY072_Aspera_clean-5594_BXBF
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------tgg
ctgaagcactgcggtccctgcgtgaaggtgtacccgacggtgatcaagct
gtcgaggcagatggcggacacggtggtgttcgcaaggatgaacggtgacg
agaacgagagctgtatggacttcctcagggacatggacgtggtggaggtt
cggaccttcctgttcataagggacggggagatatgtgggagg*
>DL;NY042_Bipenicellata_clean-5594_BXBF
NY042_Bipenicellata_clean-5594_BXBF
--------------------------------------------------
-----------------------------gccgcagggagaaggtcgaca
aggtcccccacttcagcttctacaagagcatggagaagatccacgaggag
gaggccataggacccgaccggctcatgggggacgtcctctactacggaga
caaccactcggtggtggagcagctgcatagcagggaggacgtggagaagc
tcatcgacgcccacaaggcggacgggaagctagatcgga-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
>DL;G35_Ramboi_clean-5594_BXBF
G35_Ramboi_clean-5594_BXBF
--------------------------------------------------
-------------aagacccgggagctctgccgcagggagaaggtcgaca
aggtcccccacttcagcttttacaagagcatggagaagatccacgaggag
gaggccataggacctgaccggctcatgggggacgtgctctactacggaga
caaccactcggcggtggagcagctgcacagcagggaggacgtggagaagc
tcatggacgcccacaaagcggatgggaagctcctagtgctggacgtgggg
ctgaagcactgcgggccttgcgtgaaggtgtacccgacggtgatcaagct
atcgagacagatggcagacacggtggtgttcgcgaggatgaacggggacg
agaacaagagctgtatggacttccttagggacatggacgt----------
------------------------------------------*
>DL;A30_Aspera_clean-5594_BXBF
A30_Aspera_clean-5594_BXBF
--------------------------------------------------
---------------------ggagctctgccgcagggagaaggtcgaca
aggtcccccacttcagcttctacaagagcatggagaagatccacgaggag
gaggccatagggcccgaccggctcatgggggacgtcctctactacggaga
caaccactctgcggtggagcagctgcacagcagggaggacgtggagaagc
tcatcggagcccacaaggccgacgggaagctcctggtgcttgacgttggg
ctgaagcactgcggcccttgcg----------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------*
