>DL;NY055_Bipenicellata_clean-5772_BZDF
NY055_Bipenicellata_clean-5772_BZDF
ttgaatggccgtcagtgatttagtggatggctcactggacaatttttagg
gtttttgttgttgttgttgtgacaatggtatctgttagattgtggcagat
aattgtgttggaagataccagcgagtatataagttaccaacccatgtcgg
agattaaagcacaagatagacgagcatttgatctcttggtatgtctgcat
tagtgctatcgcttgtttttgtaaggaa---aatgtgcatttca------
--ctttgttttattccatcggtcctcgggttatgcaggtaataataaacc
ccaagctgaagaagaagagggaccgaactgctcttttctttgaaggatgt
ttgaggtaagtgacccttttgattatagtggagtgtggctggagac----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY073_Aspera_clean-5772_BZDF
NY073_Aspera_clean-5772_BZDF
--------------------------------------------------
----------------gatctacaatggcatctgttagattgtggcagat
aattgtgttggaagataccagcgagtacataagttaccagcccatgtcgg
agattaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tagtgctttcacttgtttgtgtaaggaa---aatattcatttcacgtcca
ccctttgttttattcggtcgatcctgggctcacgcaggtaataat-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY040_Bipenicellata_clean-5772_BZDF
NY040_Bipenicellata_clean-5772_BZDF
--------------------------------------------------
--------------------------tgtatctgttagattgtggcagat
aattgtgttggaagataccagcgagtatataagttaccaacccatgtcgg
agattaaagcacaagatagacgagcatttgatctcttggtatgtctgcat
tagtgctatcgcttgtttttgtaaggaa---aatgtgcatttca------
--ctttgttttattccatcggtcctcgggttatgcaggtaataataaacc
ccaagctgaagaagaagagggaccgaactgctcttttctt----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY070_Aspera_clean-5772_BZDF
NY070_Aspera_clean-5772_BZDF
--------------------------------------------------
--------------------------------------------------
----------------tccagcgagtacataagttaccagcccatgtcgg
agattaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tagtgctttcacttgtttgtgtaaggaa---aatattcatttcacgtcca
ccctttgttttattcggtcgatcctgggctcacgcaggtaataataaacc
ccaagctga-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY054_Bipenicellata_clean-5772_BZDF
NY054_Bipenicellata_clean-5772_BZDF
---------------------------------------ggtttttaggg
tttcttgttgttgttgttgtgacaatggcatctgttagattgtggcagat
agtcgtgttggaagataccagcgagtatataagttaccaacccatgtcgg
agattaaagcacaagatagacgagcatttgatctcttggtatgtctgcat
tagtgctgtcgcttgtttttgtaaggaa---aatatgcatttca------
--ctttgttttattccatcggtcctggggttatgcaggtaataataaacc
ccaagctgaagaagaagagcgaccgaactgctcttttctttgaaggatgt
ttgaggtaagtgaccattttgattatagtggagtgtggctggagactgtg
gagtcctgagtcattgcatttcgattggtacgcctaattcagcggtatat
caataatgcacgatgaatgtcaagattcacctcaggcgcttaaatctagc
ggtccatcatcatgtgttttctttgagaatttggtagtgaggaggacatg
aggacagttgatatccttgtgttcgcttg*
>DL;NY065_Aspera_var_clean-5772_BZDF
NY065_Aspera_var_clean-5772_BZDF
--------------------------------------------------
------------tctgtaatgacaatggcatctgttagattgtggcagat
aattgtgttggaagataccagcgagtacataagttaccagcccatgtcgg
agattaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tagtgctttcacttgtttgtgtaaggaa---aatattcatttcacgtcca
ccctttgttttattcggtcgatcctgggctcacgcaggtaataataaaca
ga------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;G05_Aspera_clean-5772_BZDF
G05_Aspera_clean-5772_BZDF
--------------------------------------------------
--ttagggttttgctgtaatgacaatggcatctgttagattgtggcagat
aattgtgttggaagataccagcgagtacataagttaccagcccatgtcgg
agattaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tagtgctttcacttgtttgtgtaaggaa---aatattcatttcacgtcca
ccctttgttttattcggtcgatcctgggctcacgcaggtaataataaacc
ccaagctga-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY052_Striphnocalyx_clean-5772_BZDF
NY052_Striphnocalyx_clean-5772_BZDF
--------------------------------------------------
----------------agatctacacagagtagaacactctttccctaca
cgacgctattccgatctccagtgagtacataagttaccaacccatgtcgg
agataaaagcacaagatagacgagcattcgatctcttggtatgtctgcat
tagtgctattgctttgttttgtaaggaa---agtatgcatttcacgtccg
ccatttgttttattcggtcggtcctgggcttatgcaggtaataataaacc
agatc---------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;A08_Aspera_clean-5772_BZDF
A08_Aspera_clean-5772_BZDF
-----------------------------------------------caa
ttttagggttttgctgtaatgacaatggcatctgttagattgtggcagat
aattgtgttggaagataccagcgagtacataagttaccagcccatgtcgg
agattaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tagtgctttcacttgtttgtgtaaggaa---aatattcatttcacgtcca
ccctttgttttattcggtcgatcctgggctcacgcaggtaataataaaag
at------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY042_Bipenicellata_clean-5772_BZDF
NY042_Bipenicellata_clean-5772_BZDF
--------------------------------------------------
----------------------------------ttagattgtcgcagat
aattgtgttggaagataccagcgagtatataagttaccaacccatgtcgg
agattaaagcacaagatagacgagcatttgatctcttggtatgtctgcat
tagtgctgtcgcttgtttttgtaaggaa---aatatgcatttca------
--ctttgttttattccatcggtcctggggttatgcaggtaataataaacc
ccaagctgaagaagaagagcgaccgaactgctctt---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;G35_Ramboi_clean-5772_BZDF
G35_Ramboi_clean-5772_BZDF
--------------------------------------------------
------------------------------tatgttagattgtggcagat
aattgtgttggaagataccagcgagtagataagttaccaacccatgtcag
agatcaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tactgctaccacttatttttgtatggaaaagaaaatgcatttcatgtcca
ccctttgttttatagatcgga-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY067_Aspera_var_clean-5772_BZDF
NY067_Aspera_var_clean-5772_BZDF
--------------------------------------------------
------tgttttgctgtaatgacaatggcatctgttagattgtggcagat
aattgtgttggaagataccagcgagtacataagttaccagcccatgtcgg
agattaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tagtgctttcacttgtttgtgtaaggaa---aatattcatttcacgtcca
ccctttgttttattcggtcgatcctgggctcacgcaggtaataataaacc
ccaagctga-----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY056_Aspera_clean-5772_BZDF
NY056_Aspera_clean-5772_BZDF
------------------------------------------------aa
ttttagggttttgctgtaatgacaatggcatctgttagattgtggcagat
aattgtgttggaagataccagcgagtacataagttaccagcccatgtcgg
agattaaagcacaagatagacgagcattcgatctcttggtatgtctgcgt
tagtgctttcacttgtttgtgtaaggaa---aatattcatttcacgtcca
ccctttgttttattcggtcgatcctgggctcacgcaggtaataat-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
>DL;NY020_Karstenii_clean-5772_BZDF
NY020_Karstenii_clean-5772_BZDF
--------------------------------------------------
-----------------------------------------------tat
aattgtgttggaagataccagcgagtatataagttaccaacccatgtcgg
agattaaagcacaagatagacgagcatttgatctcttggtatgtttgcat
tagtgctgtcgcttgtttttgtaaagaa---aatatgcatttca------
--ctttgttttattccatcggtcctggggttatgcaggtaataataaacc
ag------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------*
