>DL;NY060_Aspera_odd1_clean-5842_IMZV
NY060_Aspera_odd1_clean-5842_IMZV
------------------gggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcaatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcgga-------------------------------------
----------*
>DL;A31_Aspera_clean-5842_IMZV
A31_Aspera_clean-5842_IMZV
---------ccaagaggttggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatactct
g---------*
>DL;NY073_Aspera_clean-5842_IMZV
NY073_Aspera_clean-5842_IMZV
--ttctgccacaagaggtgggtcggcagtggtaggatgttgtctgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatgcta-
----------*
>DL;NY074_Aspera_clean-5842_IMZV
NY074_Aspera_clean-5842_IMZV
----------------------cggcgaccaccgagatctacacaaggag
taacactctttccctacac-----------gacgctcttcgatctctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgtttagattgatactct
gt--------*
>DL;NY031_Spruceana_clean-5842_IMZV
NY031_Spruceana_clean-5842_IMZV
-----------------------------cgatctatgttgtccgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggtta-----------------------------------
----------*
>DL;NY065_Aspera_var_clean-5842_IMZV
NY065_Aspera_var_clean-5842_IMZV
--------------------tccgcatggcgttttatttccgatgacggg
ccttggcacttcgcaaacctatagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatactct
gttttatgat*
>DL;G05_Aspera_clean-5842_IMZV
G05_Aspera_clean-5842_IMZV
tcttctgccacaagaggtgggtcggcagtggtaggatgttgtctgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatgctct
gttttatga-*
>DL;A08_Aspera_clean-5842_IMZV
A08_Aspera_clean-5842_IMZV
-----------------tgggtcggcagtggtaggatgttgtctgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatgctct
gttt------*
>DL;NY046_Aspera_clean-5842_IMZV
NY046_Aspera_clean-5842_IMZV
-cttttgccacaagaggttggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatactct
gttttatgat*
>DL;NY061_Aspera_odd1_clean-5842_IMZV
NY061_Aspera_odd1_clean-5842_IMZV
-----------------tgggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcaatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgat-----
----------*
>DL;NY047_Aspera_aspera_clean-5842_IMZV
NY047_Aspera_aspera_clean-5842_IMZV
-----------------------------tgtaggatgttgtctgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttca----------------------------------
----------*
>DL;NY068_Aspera_clean-5842_IMZV
NY068_Aspera_clean-5842_IMZV
tcttttgccacaagaggttggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatactct
gttttatga-*
>DL;NY067_Aspera_var_clean-5842_IMZV
NY067_Aspera_var_clean-5842_IMZV
--------cacaagaggttggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatactct
gtt-------*
>DL;NY048_Aspera_clean-5842_IMZV
NY048_Aspera_clean-5842_IMZV
--ttttgccacaagaggttggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgat-----
----------*
>DL;A07_Aspera_clean-5842_IMZV
A07_Aspera_clean-5842_IMZV
--------cacaagaggttggtcggcagtcgtaggatgttgtccgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattgatactct
ggttta----*
>DL;NY057_Aspera_asperrima_clean-5842_IMZV
NY057_Aspera_asperrima_clean-5842_IMZV
-----tgccacaagaggtgggtcggcagtggtaggatgttgtctgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccaacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttgattg-------
----------*
>DL;NY056_Aspera_clean-5842_IMZV
NY056_Aspera_clean-5842_IMZV
------gccacaagaggtgggtcggcagtggtaggaggttgtctgttgcc
tccgaccactcggcgatgccggagttcatggattacctggattcgctcag
gaactacgagaaatccggagtgcccaaaggcgccggaaccgattccgacg
atgggttcgatctgggtcggatgaggaggttgctgggtcgtcttgggaat
ccccattcgcggttcaaggtgccatcttttattgttttatagatc-----
----------*
