>DL;NY055_Bipenicellata_clean-5910_ZINQ
NY055_Bipenicellata_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------gacgccgccaaagttcgaggtc
agcgacctggaaagcctacgagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcgtacctccactcggagggggacgtggagagggcgc
tgcggaaggtcgggtggaagataaagaagagg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;116_Sp6_clean-5910_ZINQ
116_Sp6_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
-----------------------------tttggcaggcgaaagaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttcta---------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;094_Albescens_cf_clean-5910_ZINQ
094_Albescens_cf_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gac-ggcatccttttggggccctt-tacctttgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataaggaagagg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;092_Barbigera_aff_clean-5910_ZINQ
092_Barbigera_aff_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gacgggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccagggccctc
gaaggcaaccagggcgtacctacactcggagggggacgtcgaaagggcgc
tgcggaaggtcgggtggaagataagg------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;065_Albescens_clean-5910_ZINQ
065_Albescens_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------ttaatatc
tgacggcatccttttggggccctt-tacctttggcaggcgaaggaacaac
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctttctcga
cgtcctgatacactacccacagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagtttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcg---------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;098_Verticillaris_clean-5910_ZINQ
098_Verticillaris_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
-------------------------------------------gaacagc
ctc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaaga-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;080_Sp8_clean-5910_ZINQ
080_Sp8_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
---------------------------------------gaaggaacaga
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccaaagacg
ttctagatcg----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;025_Nigricans_clean-5910_ZINQ
025_Nigricans_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
-------------------------------------------gaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataagg------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;030_Nigricans_clean-5910_ZINQ
030_Nigricans_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gac-ggcatccttttggggccctt-tacctttgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataaggaaga--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;126_Bruniana_clean-5910_ZINQ
126_Bruniana_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
------------------------------------gatctaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttct----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;H40_Nigricans_clean-5910_ZINQ
H40_Nigricans_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
----------------------------ctttgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataaggaagagg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;100_Sp9_clean-5910_ZINQ
100_Sp9_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
-------atccttttggggccctt-tacctttggcaggcgaacgaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
agtcctgatacactacccgcagtataaggcggacaagatgatcggtcact
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccagggccttc
gaaggcaaccagggcttacctacactcggagggggacgtcgaaagggcgc
tgcggaaggtcgggtggaagataaggaagag-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY090_Barbigera_clean-5910_ZINQ
NY090_Barbigera_clean-5910_ZINQ
--------------------------------------------------
-------------------------------------------------t
gacgggcatccttttggggccctt-tacctttggcaggcaaaggaacagc
ttc---------aaggtgatgctgccacagtgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccaaagacg
ttagatcgga----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;071_Nigricans_clean-5910_ZINQ
071_Nigricans_clean-5910_ZINQ
--------------------------------------------------
-------------------------------------------aatatct
gacgggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataag-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;055_Aegopogon_clean-5910_ZINQ
055_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gac-ggcatccttttggggccctt-taccattgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataaggaagagg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY094_Aegopogon_clean-5910_ZINQ
NY094_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------atgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggc--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY031_Spruceana_clean-5910_ZINQ
NY031_Spruceana_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------gaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggccgacaagatgatcggtcacc
tggcttccttggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagctgttcccggggccgtc
caaggcaacaagggcctacctacactcggagggggacatggagagggcgc
tgcagaagagat--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;102_Sp7_clean-5910_ZINQ
102_Sp7_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
----------------------------ctttggcaggcaaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccagggccttc
gaaggcaaccagggcttacctacactcggagggggacgtcgaaagggcgc
tgcggaaggtcgggtagacgataaggaa----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;044_Aegopogon_clean-5910_ZINQ
044_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
---------------ggggccctt-tacctttgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtgaaagataaggaagag-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;066_Aegopogon_clean-5910_ZINQ
066_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gac-ggcatccttttggggccctt-tacctttgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataaggaagag-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY030_Spruceana_clean-5910_ZINQ
NY030_Spruceana_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----ctgatacactacccgcagtatcaggccgacaagatgatcggtcacc
tggcttccttggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagctgttcccggggccgtc
caaggcaacaagggcctacctacactcggagggggacgtggagagggcgc
tgcagaaggtcgggtggaaaataagg------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY085_Verticillaris_clean-5910_ZINQ
NY085_Verticillaris_clean-5910_ZINQ
agttcgaggtcagcgacctggaaagcctacaagggaagtacgacacggtg
gtctgcctcgacgtcctgatacactacccgcagtataaggcggacaagat
gatcggtcacctggcttccctatt-aatatctgacgggcgaaagaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggt---------
----ctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccagggccctc
gaaggcaaccagggcgtacctacactcggagggggacgtcgaaagggcgc
tgcggaaggtcgggtggaagataaggaagagg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY046_Aspera_clean-5910_ZINQ
NY046_Aspera_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------caatatct
gatgggtacccttttggggctctttttcctgtggcaggcgaaggaacagc
ttc---------aaggcgatgccgccacgacgctgcccaagttcgaggtc
agcgacctggaaagcctgcaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcaatatcaggccgacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactacgacatactgaagaggataggggagctgttcccagggccgtc
gaaggcaacaagggcctacctacactcggagggggacgtggagagggcgc
tgcagaaggtcgggtggaagataaggaagagggggctcgtcacgac----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;014_Aegopogon_clean-5910_ZINQ
014_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gac-ggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtgga--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;061_Angustifolia_clean-5910_ZINQ
061_Angustifolia_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
-------------------ccctt-tacctttggcaggcgaaggaacatc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccagggccctc
gaaggcaaccagggcgtacctacactcggagggggacgttgaaagggcgc
tgcggaaggtcgggtggaagata---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY077_Angustifolia_clean-5910_ZINQ
NY077_Angustifolia_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------t
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggatggggatgtcgagagggcgc
tgcggaaggt----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;G17_Aegopogon_clean-5910_ZINQ
G17_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
-------------------------------------------aatatct
gacgggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataagga-----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;42_Angustifolia_clean-5910_ZINQ
42_Angustifolia_clean-5910_ZINQ
--------------------------------------------------
----------------------------------------attaatatct
gacgagcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccagggccctc
gaaggcaaccagggcgtacctacactcggagggggacgtcgaaagggcgc
tgcggaaggtcgggtggaaga-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY079_Albescens_clean-5910_ZINQ
NY079_Albescens_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--t---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
agtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagaggga--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY092_Aegopogon_clean-5910_ZINQ
NY092_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------------ct
gacgggcatccttttggggcccttatacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgc----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;F41_Edmundoi_clean-5910_ZINQ
F41_Edmundoi_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
-acgggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacgtactgaagaggataggggagttgttcccagggccctc
gaaggcaaccagggcgtacctacactcggagggggacgtcgaaagggcgc
tgcggaaggtcgggtggaagataagga-----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;A30_Aspera_clean-5910_ZINQ
A30_Aspera_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
-----------------ggctctttttcctgtggcatgcgaaggaacagc
ttc---------aaggcgatgccgccacgacgctgcccaagttcgaggtc
agcgacctggaaagcctgcaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggccgacaagatgatcggtcacc
tggcttccttggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagctgttcccggggccgtc
caaggcaacaagggcctacctacactcggagggggacgtggagagggcgc
tgcagaaggtcgggtggaaaataaggaag---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;114_Sp5_clean-5910_ZINQ
114_Sp5_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
---------------ggggccctt-tacctttggcaggcgaaggaacaac
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgt-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;109_Sp9_clean-5910_ZINQ
109_Sp9_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--c---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccagggccctc
gaaggcaaccagggcgtacctacactcggagggggacgtcgaaagggcgc
tgcggaaggtcgggtggaagataaggaagagg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;131_Fraterna_clean-5910_ZINQ
131_Fraterna_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------------ct
gacgggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccaaagacg
ttctaa--------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;G09_Verticillaris_clean-5910_ZINQ
G09_Verticillaris_clean-5910_ZINQ
--------------------------------------------------
-------------------------------------------aatatct
gacgggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataaggaagagg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;069_Nigricans_clean-5910_ZINQ
069_Nigricans_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gacgggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataag-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;073_Aegopogon_clean-5910_ZINQ
073_Aegopogon_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
---------------------------cctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttccccgggccctc
gaaggcaaccagggcctacctacactcggagggggatgagatc-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;G27_Desmocelis_clean-5910_ZINQ
G27_Desmocelis_clean-5910_ZINQ
gctattggg-----------------------------------------
--------------------------------------------------
-------------------------ttcctaacaaaggcgaaggaacagc
tgcttgtatccaacggggatgtctccacatcgctgccgaagttcgaggtc
agcgatctggaaagccttcaagggaagtacgacacggtggtttgtctcga
tgtactaatacattaccctcagcatcaagccgacaagatgatcaggcacc
tagcttctctggcgagcaatcggctgatcctcagctttgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccgggcccttc
aaaggcgaccagggcttacctacacgccgagggggacgtcgagagggcat
tgcggaaggtcgggtggaagataaggaagagaggtctcatcacgactcag
ttttactttgcgagactcgtcgaggccgtcccgatctaggtaacggccaa
attgttcgttttccggacggtgttgctcatcgttttatatatgtaaaatt
tcttgctgatgaaaatttcgtattgagtctgaggcggataatttgagaat
ggtgcaaatgactaatttgagcgcattttgtgtgccataatcattttttt
aaaaaaaaaattacaaacatgaaaccattttttcgaaaatttacatttac
taattaattttgtaatgcgtaaatatttttattatatttaataattctta
cacttttataagattcgttcgtattaaatcatttaattctatgt*
>DL;113_Sp5_clean-5910_ZINQ
113_Sp5_clean-5910_ZINQ
--------------------------------------------------
------------------------------------------taatatct
gac-ggcatccttttggggccctt-tacctttgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaatcggctgatcctaagcttcgccccgaagacg
ttctactatgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcctacctacactcggagggggatgtcgagagggcgc
tgcggaaggtcgggtggaagataagga-----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;G21_Papyrus_clean-5910_ZINQ
G21_Papyrus_clean-5910_ZINQ
--------------------------------------------------
-------------------------------------------------c
tgacggcatccttttggggccctt-tacctttggcaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcccaagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccaaagacg
ttctactaaga---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;052a_Melastomoides_clean-5910_ZINQ
052a_Melastomoides_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
----------------ggggcctt-tacctttgacaggcgaaggaacagc
ttc---------aaggtgatgccgccacagcgctgcctgagttcgaggtc
agcgacctggaaagcctacaagggaagtacgacacggtggtctgcctcga
cgtcctgatacactacccgcagtataaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagcttcgccccgaagacg
tt------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
>DL;NY050_Fraterna_clean-5910_ZINQ
NY050_Fraterna_clean-5910_ZINQ
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------tcgctgcccaagtccgaggtc
agcgacctggaaagcctccaagggaagtacgacacggtggtctgccttga
cgtcctgatacactacccgcagtatcaggcggacaagatgatcggtcacc
tggcttccctggcgagcaaccggctgatcctaagctttgccccgaagacg
ttctactacgacatactgaagaggataggggagttgttcccggggccctc
gaaggcaaccagggcgtacctacactcggagggggacgt-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------*
