>DL;NY022_Mathaei_clean-5926_Tibouchina_appended
NY022_Mathaei_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------cgatcttactctatgg
t------------ttgaaatgattgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaagaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatat------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;116_Sp6_clean-5926_Tibouchina_appended
116_Sp6_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------caaataaaagcttgtaatagaaggttg
gagtttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatattttt
ggacatcgattttctattatagaaacta---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcataaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctattacagatattttaatctaaaatagaaatcacgtgcat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaa-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;NY017_Llanorum_2_clean-5926_Tibouchina_appended
NY017_Llanorum_2_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------cataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactg---taaaa-----ggtccaatc
ttatattgttcataagatcataagatcgga--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;080_Sp8_clean-5926_Tibouchina_appended
080_Sp8_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------ccttcgtggaaaattttacaattcaa
attaagtaaaaatcagttcgaaaatattcgaatttaaggtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattgtagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatctatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcatgataagaagaag---ttct
ctttcaagaatgacttgggggtctgttatccattttaacgacaaaaacgt
tgtacagcag-gtgtacaactagattatgtttcaattctgtcaccaacat
aacctcatcaataaccatagtttctggagtaataaaagtttatactccga
ttacaaaacctttgttgttgtctccgaaac--------------------
----------------------------------------------*
>DL;NY059_Llanorum_clean-5926_Tibouchina_appended
NY059_Llanorum_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------ttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactg---taaaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatagatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgcgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgt---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;100_Sp9_clean-5926_Tibouchina_appended
100_Sp9_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------catcgtggaaaattttacaattcaa
attaagtaaaaattagttcgaaaatattcgaatttaa-gtctccaaaaat
tgtttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatttttttaag----tgtg
tcatattttcttgataaacatctcaaataaaagcttgtaatagagggttg
gag-ttcacccttctatacataccttctac----------tactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ct-aaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaacta---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
tgaaatattctgttacaaatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcatgataagaagaag---ttct
ttttcaagaatgacttgggggtctgttatccattttaatgacaaaaacgt
tgtacagcag-gtgtacaactagattatgtttcaattctgtcaccaacag
aacctcatcaataaccgtagtttctggagtaataaaagtttatactccga
ttacaaaacctttgttgttgtctccaaaactcatagaacctccattctac
atttttaggttggat-------------------------------*
>DL;NY088_Barbigera_clean-5926_Tibouchina_appended
NY088_Barbigera_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------tatgg
t------------ttcaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaataatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacattgattttctattgtagaaattg---tagaa-----ggtccaatc
ttacattgttcataagatcatactaacttccaaatatatta---------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;NY091_Barbigera_hirsutula_clean-5926_Tibouchina_appended
NY091_Barbigera_hirsutula_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------agagtagaatactgtttccctacacgacgctcttacg
atctaaacccaaggaaataatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcgggcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattgtagaaactg---tagaaggtccggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagat--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;NY051_Llanorum_clean-5926_Tibouchina_appended
NY051_Llanorum_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------gttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactg---taaaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatagatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgcgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaa----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;NY054_Bipenicellata_clean-5926_Tibouchina_appended
NY054_Bipenicellata_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------cacccttctatacataccttctacatgaggttcatactctgtgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcgaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
agacatcgattttctattatagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcttactaacttccaaatatatttcacaaaatt
aaatattaagatatctctatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctttaatgaaaaa------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;079_Sp8_clean-5926_Tibouchina_appended
079_Sp8_clean-5926_Tibouchina_appended
ccatgaatggagaggaatctgtagaacatatgttccagagacttaacctc
ctggttgatgacttaactcatttag---gcaaacattataggaatatgga
gttagtaagaaaggttctacgcactctcctttaaa----------tcttg
ggaagccaagaaaacggttatagagaagcttcttatagacggaacaacct
tctacaaaacattacatcgaaatattcgaaaataacgtttcctttttcat
agatttcatttgaaaaggaaattcccttcgtggaaaattttacaattcaa
attaagtaaaaatcagttcgaaaatattcaaatttaaggtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttggtaaacatctcaaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattgtagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttctcaatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcatgataagaagaag---ttct
ctttcaagaatgacttgggggtctg-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;102_Sp7_clean-5926_Tibouchina_appended
102_Sp7_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------catcgaaatatttgaaaataacgtttcctttttcat
aaatttcatttgaaaaggaaattcccttcgtggaaaattttacaattcaa
attaagtaaaaattagttcgaaaatattcgaatttaa-gtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgatattttttttaag----tgtg
tcgtattttcttgataaacatctcaaataaaagcttgtaatagagggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaacta---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
tgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcatgataagaagaag---ttct
ttttcaagaatgacttgggggtctgttatccattttaacgacaaaaacgt
tgtacagcag-gtgtacaactagattatgtttcaattctgtcaccaacag
aacctcatcaataaccgtagtttctggagtaataaaagtttatactccga
ttacaaaacctttgttgttgtctccaaaactcatagaacctccattctac
atttttaggttggaaaatttagg-----------------------*
>DL;095_Barbigera_clean-5926_Tibouchina_appended
095_Barbigera_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------atttcctttttcat
agatttcatttgaaaaggaaattcccttcgtggaaaattttacaattcaa
attaagtaaaaatcagttcgaaaatattcgaatttaaggtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaagcttgtaatagaaggttg
gat-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttct--tttcataaaa
ctaaaaacccaaggaaataatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcgggcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattgtagaaactg---tagaaggtccggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtgtagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaataatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttacc----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;G23_Melastomoides_clean-5926_Tibouchina_appended
G23_Melastomoides_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------tcccttcgtggaaaattttacaattcaa
attaagtaaaaatcagttcgaaaatattcgaatttaaggtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaag-ttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatgttttt
ggacatcgattttctattatagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcctactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctattacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcactgacattcttaccaaatctcttgataagaagaag---ttct
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;104_Sp6_clean-5926_Tibouchina_appended
104_Sp6_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------atcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaagcttgtaatagaaggttg
gagtttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcataatttt
ggacatcgattttctattatagaaacta---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcataaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
tgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcatgataagaagaag---ttct
ctttcaagaatgact-----------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;NY086_Barbigera_clean-5926_Tibouchina_appended
NY086_Barbigera_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------attcgaatttaaggtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttggtaaacatctcaaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattgtagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtgtgcttagaacacgtgaatacaaaacg
tcaattcgctggcattcttaccaaacctcttgataagaa-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;107_Sp7_clean-5926_Tibouchina_appended
107_Sp7_clean-5926_Tibouchina_appended
--------------------------------------------------
-----------------------------caaacattatagtaatatgga
gttagtaagaaaggttctacgcactctcctttaaa----------tcttg
ggaagccaagaaaacggttatagagaagcttcttatagacggaacaacct
tctacaaaacattacatcgaaatatttgaaaataacgtttcctttttcat
aaatttaatttgaaaaggaaattcccttcgtggaaaattttacaattcaa
attaagtaaaaattagttcgaaaatattcgaatttaa-gtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgatattttttttaag----tgtg
tcgtattttcttgataaacatctcaaataaaagcttgtaatagagggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaacta---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
tgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcatgataagaagaag---ttct
ttttcaagaatgacttgggggtctgttatccattttaacgacaaaaacgt
tgtacagcag-gtgtacaactagattatgtttcaattctgtcaccaacag
aacctcatcaataaccgtagtttctggaggaataaaagtttatactccga
ttacaaaacctttgttgttgtctccaaaactcatagaacctccattctac
atttttaggttggaaaatttagggatcacc----------------*
>DL;018_Barbigera_clean-5926_Tibouchina_appended
018_Barbigera_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
----gtaagaaaggttctacgcactctcctttaaa----------tcttg
ggaagccaagaaaacggttatagagaagcttcttatagacggaacaacct
tctacaaaacattacatcgaaatattagaaaataacgtttcctttttcat
agatttcatttgaaaaggaaattcccttcgtggaaaattttacaattcaa
attaagtaaaaatcagttcgaaaatattcgaatttaaggtctccaaaaat
tatttttggaaatattgaaatctataaggattgttatcc-tttttgtagt
tattt-agaatattcaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatct-aaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaataatatattactaaagttcacaagaatcaaaat
ctctaaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactgtcatagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaataataagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcttgataagaagaag---ttct
ctttcaagaatgacttgggggtctgttatccattttaacgacaaaaacgt
tattattcta-ttgcgtgattcaattatgtacgagacgttgaacagacaa
aatgcttgttccatgctcgtcatcagagtcatcactttcagcccaggcga
gcatagcactattgcccttatagggagcaga-------------------
----------------------------------------------*
>DL;076_Gracilis_clean-5926_Tibouchina_appended
076_Gracilis_clean-5926_Tibouchina_appended
----ctatacagaagctacgatgagaaggtaacaccttctaccattcatt
tagttcgaatataaaattcgaattacttgaagttcttaaattacaaagta
attaatccaaatgtatcttttcattacttatttcagaaaattttttctta
ataggataatccctttctttcagagaagcttcttatagaaggtacaacgt
tctacggaacgtcacttcgaaat-atttaaattaacatttc---------
--aatttatttcaaaaggaaattgcctttgttgaaaattttcaaattaag
attaaatcgaaattaattcgaaaatgttcaaattagaagcctccaaaaat
tatttttgaaaatatcaaaatctataaggattattatcattttttatata
tatttgagaatattgaaaaagcatcctcgtaatcttctcaaggaaatata
tcgtatttcctt------------agataattgtttcaaacagaagtgtg
tgt-----tatgtcgtcatataccttctaaatgaggtttaccctctatag
ctaaaccctaaacctaaaatgaatgagaaatagtttccaatttaatgaaa
ttagaaatcttataaaagaatatcttcctccggttcataatgatcgaaat
ctctcaaagaactcgaccaatgagaaatttatctcaaagttcatcttttt
ggacatcaattttctattacagaaaatacgcgagaa-----ggttcatca
ttatagaatccgaaagatcatactaatttccaaatatatttttcaaaatt
aaatattaagataacactatcttagtatatttttgttgaaataattattt
tagcttagtttgttacagatatttcaatctacaagagaaatcatggataa
aagcttaaaacttctgtaatgaa-------tccatccttattgggtgaga
gtggacgtaggtaaaacttgtcgaaccactataaaaccttgtatctcact
tttcttttattactgcctgtttgcgtttcaatcaagtcagaat-------
------ggcacgcataggaggtaaaccaaccgacaaatcgggttttaccc
gctataacggaacattcttcgggattatatgtgcttcttatcggt-----
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;F41_Edmundoi_clean-5926_Tibouchina_appended
F41_Edmundoi_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------cttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgtggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttaataaaa
ctaaaaaccc---------atatattactaaagatcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactgtcatataa-----ggtccaatc
ttatgttgtccataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
tgaaatattctattacagatattttaatcgacaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaatatcatttcttatgg
gataatgtccaacaaggttctgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgatattcttaccaaacctcttgataagaagaagttcttct
ctttcaagaatgacttgggggtctgttatccattttaacgacaaaaacat
tgtacagcag-gtgtacaactagattatgtttcatttctgtcaccaactg
aacctcatcaataa------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;109_Sp9_clean-5926_Tibouchina_appended
109_Sp9_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------agcttgtaatagagggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaacta---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
tgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcatgataagaagaag---ttct
ttttcaagaatgacttgggggtctgttatccattttaacgacaaaaacat
tgtacaacag-gtgtccaactagagtatgtttcatttctgtcaccaactg
aacctcatcaataaccatagtttctggagtaataaaagtttatactccga
ttacaaaacctttgttgttgtcaccaaaactcatagaacctccattctac
atttttaggttggaaaatttagggatcaccgatcttgtgcttagag*
>DL;NY089_Barbigera_clean-5926_Tibouchina_appended
NY089_Barbigera_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------ataaacatctcaaataaaagcttgtaatagaaggttg
gat-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaataatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcgggcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattgtagaaactg---tagaaggtccggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtgtagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaa-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;A10_Melastomoides_clean-5926_Tibouchina_appended
A10_Melastomoides_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---aagtaaaaatcagttcgaaaatattcgaatttaaggtctccaaaaat
tatttttggaaatattaaaatctataaggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaag-ttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctattacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaaaatcatttcctatgg
gataatgtccaacaaggttatgtatgcgtagaatacatgaatacaaaacg
tcaat---------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
>DL;052a_Melastomoides_clean-5926_Tibouchina_appended
052a_Melastomoides_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------ttcaaaaataacgtttcctttttcat
agatttcatttgaaaaggaaattcccttcgtggaaaattttacaattcaa
attaagtaaaaatcagttcgaaaatattcgaatttaaggtctccaaaaat
tatttttggaaatattgaaatctat--ggattgttatccttttttgtagt
tattt-agaatattgaaaaa-tatcctgataatcttttcaag----tgtg
tcatatttccttgataaacatctcaaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacataccttctacatgaggttcatactctatgg
t------------ttgaaatgaatgtgttatattttctaatttcataaaa
ctaaaaacccaaggaaagaatatattactaaagttcgcaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacattgattttctattatagaaactgtcatagac-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaatattaagatatcactatcttagtatagttt--ctagaataattattt
cgaaatattctgttacagatattttaatctaaaatagaaatcatgtacat
aagtttaaatcttctgtaatgaaaaatgtgtcgaacatcatttgctatgg
gataatgtccaacaaggttatgtatgcttagaacacgtgaatacaaaacg
tcaattcgctgacattcttaccaaacctcttggtaagaagaag---ttct
ctttcaagaatgacttgggagtctgttatccattttaacgacaaaaacgt
tgtacaacag-gtgtacaactagattatgtttcaattctgtcaccaacag
aacctcatcaataaccatagtttctggagtaataaaagtttatactccga
ttacaaaacctttgttgttgtctccaaaactcatagaacctccattctac
atttttaggttggaaaatttagggatcac-----------------*
>DL;NY020_Karstenii_clean-5926_Tibouchina_appended
NY020_Karstenii_clean-5926_Tibouchina_appended
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------tataaggattgttatctcaag----tgtg
tcatatttccttgataaacatctcaaataaaagcttgtaatagaaggttg
gag-ttcacccttctatacatacctt-tacatgaggtttatactctatgg
t------------ttgaaatgaatgtgttatattttctaatatcataaaa
ctaaaaacccaagggaagaatatattactaaagttcacaagaatcaaaat
ctctcaaggaactcggtcaatgagaaatctatctcaaagttcatcttttt
ggacatcgattttctattatagaaactg---tagaa-----ggtccaatc
ttatattgttcataagatcatactaacttccaaatatatttcacaaaatt
aaagat--------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------*
