>DL;NY060_Aspera_odd1_clean-5990_AXNH
NY060_Aspera_odd1_clean-5990_AXNH
--------------------------------------------------
-----------------attcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtttgtgcatttacaagtggaccttat
tcatctccttt-catgtggtttcccaga----------------------
-------------------------*
>DL;A31_Aspera_clean-5990_AXNH
A31_Aspera_clean-5990_AXNH
a-------------------------------------------------
-------aaatagctaaattcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctccttgcagttcgattctttagttg-cagcccttcccctagctga
gggaggaga----------------*
>DL;NY073_Aspera_clean-5990_AXNH
NY073_Aspera_clean-5990_AXNH
--------------------------------------------------
------------gctaaattcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
tta----------------------*
>DL;NY074_Aspera_clean-5990_AXNH
NY074_Aspera_clean-5990_AXNH
--------------------------------------------------
---------------aaattcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-catatttttcaagcgggcc
ta-----------------------*
>DL;NY070_Aspera_clean-5990_AXNH
NY070_Aspera_clean-5990_AXNH
--------------------------------------------------
------------------ttcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggta-----------------------------
-------------------------*
>DL;NY071_Aspera_clean-5990_AXNH
NY071_Aspera_clean-5990_AXNH
--------------------------------------------------
-------------------------------------ccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaag------
-------------------------*
>DL;NY031_Spruceana_clean-5990_AXNH
NY031_Spruceana_clean-5990_AXNH
--------------------------------------------------
----------------------cgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--caa-----------------------------------
-------------------------*
>DL;NY065_Aspera_var_clean-5990_AXNH
NY065_Aspera_var_clean-5990_AXNH
--------------------------------------------------
-----------------------gtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgaccttcttgatctaggccg*
>DL;G32_Barnebyana_clean-5990_AXNH
G32_Barnebyana_clean-5990_AXNH
--------------------------------------------------
------------------------------------gcctgcaaccatga
ttg--gatttctctattacttagctctactcgcttctctttgcagttcga
ttctttagttgcagcccttcccctggccgagggaggagaagaagctcaga
tgaaacgaattgcagagcttcaggtgcgtgcatttgcaaactgcctttat
taatttccttt-catgtagtttcctagatttcgttatttttaagcaggcc
ttactgaccat--------------*
>DL;G05_Aspera_clean-5990_AXNH
G05_Aspera_clean-5990_AXNH
--------------------------------------------------
-----------------ctcttccatctaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgaccagatcgg---------*
>DL;NY030_Spruceana_clean-5990_AXNH
NY030_Spruceana_clean-5990_AXNH
--------------------------------------------------
------------------------------atttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccg------------------------
-------------------------*
>DL;NY072_Aspera_clean-5990_AXNH
NY072_Aspera_clean-5990_AXNH
--------------------------------------------------
----------------------------------tttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtata-------------
-------------------------*
>DL;A08_Aspera_clean-5990_AXNH
A08_Aspera_clean-5990_AXNH
--------------------------------------------------
-----------------attcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttccagatcg-gaggagcgtcgtgtaggga
aagagtgttctactctg--------*
>DL;NY046_Aspera_clean-5990_AXNH
NY046_Aspera_clean-5990_AXNH
--------------------------------------------------
-----------------attcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactga------------------*
>DL;NY061_Aspera_odd1_clean-5990_AXNH
NY061_Aspera_odd1_clean-5990_AXNH
--------------------------------------------------
--------------------------gcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtttgtgcatttacaagtggaccttat
tcatctccta----------------------------------------
-------------------------*
>DL;NY047_Aspera_aspera_clean-5990_AXNH
NY047_Aspera_aspera_clean-5990_AXNH
--------------------------------------------------
-----------------attcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgac-----------------*
>DL;NY068_Aspera_clean-5990_AXNH
NY068_Aspera_clean-5990_AXNH
--------------------------------------------------
---------------aaattcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggtta--------------------
-------------------------*
>DL;A30_Aspera_clean-5990_AXNH
A30_Aspera_clean-5990_AXNH
--------------------------------------------------
---------------------------caaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgagacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctccttt-cctgtggtttcccggttt-cgtatttt-----------
-------------------------*
>DL;NY067_Aspera_var_clean-5990_AXNH
NY067_Aspera_var_clean-5990_AXNH
--------------------------------------------------
-----------agctaaattcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgaccttcttgatctagg---*
>DL;131_Fraterna_clean-5990_AXNH
131_Fraterna_clean-5990_AXNH
gcaagagcaagcaaatgatatcgcatcaatcgccttcaatacctttggta
ctttacaaagggacgctccccccgtgaggctctcccccaattatcccgaa
ccgccggcaaatccagcagaggatgcagcgaattttgcagagcagcccaa
gctcatgagtgctgccctagtaaaagctgcgaagcagg------------
-------------------tgcttttccttctttaccaataggtcttcat
ccatt-------gatgatgtttttcaattaatttcatattccaacggaag
aatgaaacgtcctgtagttctaca-*
>DL;NY048_Aspera_clean-5990_AXNH
NY048_Aspera_clean-5990_AXNH
--------------------------------------------------
----------------------cgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgaccttctaga---------*
>DL;A07_Aspera_clean-5990_AXNH
A07_Aspera_clean-5990_AXNH
--------------------------------------------------
-------------------tcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgaccttcta-----------*
>DL;NY057_Aspera_asperrima_clean-5990_AXNH
NY057_Aspera_asperrima_clean-5990_AXNH
--------------------------------------------------
-----------------------gtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgaccttcttgatctaggcc-*
>DL;NY056_Aspera_clean-5990_AXNH
NY056_Aspera_clean-5990_AXNH
--------------------------------------------------
-----------------attcacgtagcaaatttcttccctttgtctgga
ttgcccataaccttggtacttagctccacttgcttctccttgcagttcga
ttctttagttgcagcccttcccctagctgagggaggagaagaagcacagc
tgaaacgaattgcggagcttcaggtgtgtgcatttacaagtggaccttat
tcatctcctt--catgtggtttcccggttt-cgtatttttcaagcgggcc
ttactgaccttc-------------*
