>DL;A29_Angustifolia_clean-6130_HYZL
A29_Angustifolia_clean-6130_HYZL
----ctgttaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactatcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;NY038_Bipenicellata_clean-6130_HYZL
NY038_Bipenicellata_clean-6130_HYZL
------------------------------------ttgttcagcaaccc
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcataagcatgc
ctcaagcata----------------------------------------
-----------------------------*
>DL;NY060_Aspera_odd1_clean-6130_HYZL
NY060_Aspera_odd1_clean-6130_HYZL
--------------------------------------tttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttggtttggttttcca
ga---------------------------*
>DL;A31_Aspera_clean-6130_HYZL
A31_Aspera_clean-6130_HYZL
aagatcggtaatgatgggaaacccttgtgatacctcatgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
ttca-------------------------*
>DL;NY055_Bipenicellata_clean-6130_HYZL
NY055_Bipenicellata_clean-6130_HYZL
----tctgtaatgatgagaaacccttgtgatatctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctttctctaattatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;083_Sp3_2_clean-6130_HYZL
083_Sp3_2_clean-6130_HYZL
-------------atgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttcttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;NY073_Aspera_clean-6130_HYZL
NY073_Aspera_clean-6130_HYZL
t-tccgatctatgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;A18_Pogonanthera_2_clean-6130_HYZL
A18_Pogonanthera_2_clean-6130_HYZL
--------------------------------------tttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatggggc----a-------------------------------
-----------------------------*
>DL;NY074_Aspera_clean-6130_HYZL
NY074_Aspera_clean-6130_HYZL
------------------------------------------agcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattccagatc---------ggagagcgtcgtgtagggaaagagtgttac
tccttgtgtagatc----tcggtggtcgccg-tatcattaaaaaa-----
-----------------------------*
>DL;116_Sp6_clean-6130_HYZL
116_Sp6_clean-6130_HYZL
-------ttaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaattatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
t----------------------------*
>DL;NY045_Aegopogon_clean-6130_HYZL
NY045_Aegopogon_clean-6130_HYZL
----------atgatgggaaacacttgtgatatctcatcttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttcgca-ggttgctttg--------
-----------------------------*
>DL;NY017_Llanorum_2_clean-6130_HYZL
NY017_Llanorum_2_clean-6130_HYZL
---------atctatgggaaacccttttggtacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagaatgggac----tggtttga------------------------
-----------------------------*
>DL;094_Albescens_cf_clean-6130_HYZL
094_Albescens_cf_clean-6130_HYZL
----ttccgatctatgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcct
ta---------------------------*
>DL;092_Barbigera_aff_clean-6130_HYZL
092_Barbigera_aff_clean-6130_HYZL
-----cggtaatgatgggaaaaccttgtgatatctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgcgtc----tagtttgttccaa-cgt---------------
-----------------------------*
>DL;065_Albescens_clean-6130_HYZL
065_Albescens_clean-6130_HYZL
--------taatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcatctctctaatcatgagcatgc
ctcaagcatgggactggttggtttgttccaa-cgttggtt----------
-----------------------------*
>DL;G14_Albescens_clean-6130_HYZL
G14_Albescens_clean-6130_HYZL
-----------tgatgggaaaccattgtggtaccttgcgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcattcctttataccaat-ccccctacttgcacagga
ctgtggctggcactagaagatgcaactgtcagtaatggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatggacatgc
ctgaagcatgggac----tggttcgttctaa-cattggt-----------
-----------------------------*
>DL;098_Verticillaris_clean-6130_HYZL
098_Verticillaris_clean-6130_HYZL
------------gatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggttagatcgga--
-----------------------------*
>DL;NY093_Aegopogon_clean-6130_HYZL
NY093_Aegopogon_clean-6130_HYZL
-------atcttgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgtagatcggaa------
-----------------------------*
>DL;NY040_Bipenicellata_clean-6130_HYZL
NY040_Bipenicellata_clean-6130_HYZL
aagatcgttaatgatgggaaacccttttgatacctcgtgttcagcaaccc
gggattggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctttctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttggtttggtagatcg
-----------------------------*
>DL;080_Sp8_clean-6130_HYZL
080_Sp8_clean-6130_HYZL
-------------atgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-tgttggtttggttttcct
t----------------------------*
>DL;025_Nigricans_clean-6130_HYZL
025_Nigricans_clean-6130_HYZL
-----------tgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttga------------
-----------------------------*
>DL;NY059_Llanorum_clean-6130_HYZL
NY059_Llanorum_clean-6130_HYZL
----tcgttaatgatgggaaacccttttggtacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagaatgggac----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;030_Nigricans_clean-6130_HYZL
030_Nigricans_clean-6130_HYZL
-----------tgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttaga--
-----------------------------*
>DL;126_Bruniana_clean-6130_HYZL
126_Bruniana_clean-6130_HYZL
----------atgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgcttagatcgga--
-----------------------------*
>DL;NY070_Aspera_clean-6130_HYZL
NY070_Aspera_clean-6130_HYZL
---------ttccgatctagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
-----------------------------*
>DL;H40_Nigricans_clean-6130_HYZL
H40_Nigricans_clean-6130_HYZL
----------atgatgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggagaagtag---------------------------ttcc
tcatcaggacaactcattcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaaatgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;100_Sp9_clean-6130_HYZL
100_Sp9_clean-6130_HYZL
--------taatgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaaatgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggtt-----
-----------------------------*
>DL;NY090_Barbigera_clean-6130_HYZL
NY090_Barbigera_clean-6130_HYZL
----------atgacgggaaacccttgcgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctatggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaaacatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcct
t----------------------------*
>DL;071_Nigricans_clean-6130_HYZL
071_Nigricans_clean-6130_HYZL
---------aatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggtttt---
-----------------------------*
>DL;NY080_Papyrifera_clean-6130_HYZL
NY080_Papyrifera_clean-6130_HYZL
-----------------taaacccttttgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttgcactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctctagcatgggac----tggtttgttccaa-cgt---------------
-----------------------------*
>DL;110_Sp6_clean-6130_HYZL
110_Sp6_clean-6130_HYZL
----gatctaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-cctcctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcct
t----------------------------*
>DL;G08_Albescens_clean-6130_HYZL
G08_Albescens_clean-6130_HYZL
-----------ccgatctaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcatctctctaatcatgagcatgc
ctcaagcatgggactggttggtttgttccaa-cgttggtttggtt-----
-----------------------------*
>DL;NY088_Barbigera_clean-6130_HYZL
NY088_Barbigera_clean-6130_HYZL
----------ttccgatctaacccttgcgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctatggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaaacatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcc-
-----------------------------*
>DL;NY091_Barbigera_hirsutula_clean-6130_HYZL
NY091_Barbigera_hirsutula_clean-6130_HYZL
----tctgtaatgacgggaaacccttgcgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctatggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-tgttggtttgga------
-----------------------------*
>DL;NY071_Aspera_clean-6130_HYZL
NY071_Aspera_clean-6130_HYZL
a-------------------------atgatacggcgaccaccgagatct
acacagagtagaacactctttccctacacga---------------cgct
ctccgatcttaactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggagatcgg
-----------------------------*
>DL;NY011_Catharinae_2_clean-6130_HYZL
NY011_Catharinae_2_clean-6130_HYZL
-------------------------------------tgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgccactgtcagtaacggttgcctatgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggaa------------------------------------
-----------------------------*
>DL;055_Aegopogon_clean-6130_HYZL
055_Aegopogon_clean-6130_HYZL
-----------tgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcct
tt---------------------------*
>DL;NY051_Llanorum_clean-6130_HYZL
NY051_Llanorum_clean-6130_HYZL
-----------tgatgggaaacccttttggtacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctgtacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagaatgggac----tggtttgttccaa-cgttggtttggagatc--
-----------------------------*
>DL;NY094_Aegopogon_clean-6130_HYZL
NY094_Aegopogon_clean-6130_HYZL
----------atgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctgg----------agtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
agatcgga---------------------*
>DL;NY031_Spruceana_clean-6130_HYZL
NY031_Spruceana_clean-6130_HYZL
----------tccgatctaaacacttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcttgggac----tggtttgttccaatcgttggtttggtttt---
-----------------------------*
>DL;NY054_Bipenicellata_clean-6130_HYZL
NY054_Bipenicellata_clean-6130_HYZL
-------------atgggaaacccttttgatacctcttgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaaacatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;079_Sp8_clean-6130_HYZL
079_Sp8_clean-6130_HYZL
-----cggtaatgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-tgttggtttggttttcct
t----------------------------*
>DL;G30_Dubia_clean-6130_HYZL
G30_Dubia_clean-6130_HYZL
--------------------------gtggtaccttgcgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcattcctttataccgat-ccccctacttgcacagga
ctgtggttggcactagaagatgcaactgtcagtaatggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctattcatggacatgc
ctgaagcatgggac----tggttcattctaa-cat---------------
-----------------------------*
>DL;NY087_Barbigera_clean-6130_HYZL
NY087_Barbigera_clean-6130_HYZL
---------------tggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatggga-------------------------------------
-----------------------------*
>DL;090_Aegopogon_aff_clean-6130_HYZL
090_Aegopogon_aff_clean-6130_HYZL
-------gtaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
ta---------------------------*
>DL;127_Johnwurdackiana_clean-6130_HYZL
127_Johnwurdackiana_clean-6130_HYZL
----------tccgatctaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttagatcgga------
-----------------------------*
>DL;NY065_Aspera_var_clean-6130_HYZL
NY065_Aspera_var_clean-6130_HYZL
---------aatgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
t----------------------------*
>DL;102_Sp7_clean-6130_HYZL
102_Sp7_clean-6130_HYZL
----------aagatgggaaaccctttttatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcgtgggtc----tagtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;G02_Johnwurdackiana_clean-6130_HYZL
G02_Johnwurdackiana_clean-6130_HYZL
-------------------------------------------tctacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcct
t----------------------------*
>DL;044_Aegopogon_clean-6130_HYZL
044_Aegopogon_clean-6130_HYZL
----tcggtaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcc-
-----------------------------*
>DL;A34_Bruniana_clean-6130_HYZL
A34_Bruniana_clean-6130_HYZL
--------------------------------------------------
---ttcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----taga----------------------------
-----------------------------*
>DL;NY082_Verticillaris_clean-6130_HYZL
NY082_Verticillaris_clean-6130_HYZL
----------atgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggat----tggtttgttccaa-cgt---------------
-----------------------------*
>DL;G05_Aspera_clean-6130_HYZL
G05_Aspera_clean-6130_HYZL
---------aatgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;NY052_Striphnocalyx_clean-6130_HYZL
NY052_Striphnocalyx_clean-6130_HYZL
----------atgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgttggtttggttttcct
t----------------------------*
>DL;A35_Bruniana_clean-6130_HYZL
A35_Bruniana_clean-6130_HYZL
-------gtaatgatgggaaacccttgtgatatctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttgagatcgg------
-----------------------------*
>DL;095_Barbigera_clean-6130_HYZL
095_Barbigera_clean-6130_HYZL
-------gtaatgatgggaaacccttttgatacctcgtattcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-tgttggtttggttttcct
t----------------------------*
>DL;111_Sp5_clean-6130_HYZL
111_Sp5_clean-6130_HYZL
---------aatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctagatcggaa--
-----------------------------*
>DL;066_Aegopogon_clean-6130_HYZL
066_Aegopogon_clean-6130_HYZL
------ggtaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat--cccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-tgttgctt----------
-----------------------------*
>DL;NY030_Spruceana_clean-6130_HYZL
NY030_Spruceana_clean-6130_HYZL
-------------atgggaaacccttgtgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgac-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcttgggac----tggtttgttccaatcgttggtttggttttcct
t----------------------------*
>DL;NY072_Aspera_clean-6130_HYZL
NY072_Aspera_clean-6130_HYZL
---------------------cccttgtgattcctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgtta----------------------
-----------------------------*
>DL;NY085_Verticillaris_clean-6130_HYZL
NY085_Verticillaris_clean-6130_HYZL
----cgatctatgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;A08_Aspera_clean-6130_HYZL
A08_Aspera_clean-6130_HYZL
-----------tgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;NY046_Aspera_clean-6130_HYZL
NY046_Aspera_clean-6130_HYZL
aagatcggtaatgatgggaaacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;G23_Melastomoides_clean-6130_HYZL
G23_Melastomoides_clean-6130_HYZL
---------aatggcgggaaacccttgtgatatctcatgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-tgttggtttggttttcct
t----------------------------*
>DL;085_Aegopogon_aff_clean-6130_HYZL
085_Aegopogon_aff_clean-6130_HYZL
----------ctgccgatctacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagaag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcattaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttggtttggttttcct
t----------------------------*
>DL;NY018_Llanorum_2_clean-6130_HYZL
NY018_Llanorum_2_clean-6130_HYZL
----tcgggaatgacgggaaacccttgtgatatctcatgttcagcaacct
gggattggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ca------------------------------------------------
-----------------------------*
>DL;014_Aegopogon_clean-6130_HYZL
014_Aegopogon_clean-6130_HYZL
---atcggtaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttc--
-----------------------------*
>DL;NY032_Spruceana_clean-6130_HYZL
NY032_Spruceana_clean-6130_HYZL
----------------------------tatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatga
--------------------------------------------------
-----------------------------*
>DL;NY007_Duidae_clean-6130_HYZL
NY007_Duidae_clean-6130_HYZL
-------------cgatctaacccttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgttggtttgg-------
-----------------------------*
>DL;NY009_Duidae_2_clean-6130_HYZL
NY009_Duidae_2_clean-6130_HYZL
--------------tgggaaacccttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgttggtttggtaga---
-----------------------------*
>DL;104_Sp6_clean-6130_HYZL
104_Sp6_clean-6130_HYZL
-------gtaatgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-cctcctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttg--------
-----------------------------*
>DL;NY061_Aspera_odd1_clean-6130_HYZL
NY061_Aspera_odd1_clean-6130_HYZL
----------atgatgggaaacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
ctttagcatgggac----tgttttgttccaa-cgttggtttggttttc--
-----------------------------*
>DL;NY028_Spruceana_clean-6130_HYZL
NY028_Spruceana_clean-6130_HYZL
---------------------cgatcttgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatga
--------------------------------------------------
-----------------------------*
>DL;039_Verticillaris_clean-6130_HYZL
039_Verticillaris_clean-6130_HYZL
----------atgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggactggttggtttgttccaa-cgttggtttggttttcct
t----------------------------*
>DL;NY002_Dissitiflora_clean-6130_HYZL
NY002_Dissitiflora_clean-6130_HYZL
---------------------tccttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaacgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgttggtttgg-------
-----------------------------*
>DL;NY003_Sipapoana_clean-6130_HYZL
NY003_Sipapoana_clean-6130_HYZL
----------ttccgatctaacccttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaacgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgttggtttgg-------
-----------------------------*
>DL;061_Angustifolia_clean-6130_HYZL
061_Angustifolia_clean-6130_HYZL
----tcggtaatgatgggaaaccctttttatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgatcccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcatctctctaatcatgagcatgc
ctcaagcatgggactggttggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;NY042_Bipenicellata_clean-6130_HYZL
NY042_Bipenicellata_clean-6130_HYZL
----------atgacgggaaacccttgcgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagtatgggtc----tagtttgttccaa-cgttgctttggttttcct
-----------------------------*
>DL;NY086_Barbigera_clean-6130_HYZL
NY086_Barbigera_clean-6130_HYZL
----------atgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgtagatcggaa------
-----------------------------*
>DL;NY047_Aspera_aspera_clean-6130_HYZL
NY047_Aspera_aspera_clean-6130_HYZL
--------------tgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
tt---------------------------*
>DL;NY078_Angustifolia_clean-6130_HYZL
NY078_Angustifolia_clean-6130_HYZL
------------------------------------ttgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcattcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggt-------------------------------------
-----------------------------*
>DL;NY068_Aspera_clean-6130_HYZL
NY068_Aspera_clean-6130_HYZL
------ggtaatgagtggaaacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;NY023_Edmundoi_clean-6130_HYZL
NY023_Edmundoi_clean-6130_HYZL
----------ccgatctgaaacccttttgataccccgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttgg------------
-----------------------------*
>DL;107_Sp7_clean-6130_HYZL
107_Sp7_clean-6130_HYZL
--------taaggatgggaaaaccttgtgatatctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcgtgggtc----tagtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;NY024_Edmundoi_clean-6130_HYZL
NY024_Edmundoi_clean-6130_HYZL
----------------------------------gcgaccaccgagatct
acacaaggagtaacactctttccctacacgacgctcttcaggtctgttac
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttcca--------------------
-----------------------------*
>DL;018_Barbigera_clean-6130_HYZL
018_Barbigera_clean-6130_HYZL
-----tggtaatgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggagatc--
-----------------------------*
>DL;NY053_Fraterna_clean-6130_HYZL
NY053_Fraterna_clean-6130_HYZL
----tctttaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcattcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgttggagat--------
-----------------------------*
>DL;NY077_Angustifolia_clean-6130_HYZL
NY077_Angustifolia_clean-6130_HYZL
-----------ctatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaaagc
ctgaagcaagatcg----gaa-----------------------------
-----------------------------*
>DL;G17_Aegopogon_clean-6130_HYZL
G17_Aegopogon_clean-6130_HYZL
-----------------gaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttgagatcgg------
-----------------------------*
>DL;A26_Rosanae_2_clean-6130_HYZL
A26_Rosanae_2_clean-6130_HYZL
---------------tggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaatggttgcctttgggc
tattcctggatctcaaaatagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgtt--------------
-----------------------------*
>DL;42_Angustifolia_clean-6130_HYZL
42_Angustifolia_clean-6130_HYZL
-----------tgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgcttagatcgga--
-----------------------------*
>DL;NY079_Albescens_clean-6130_HYZL
NY079_Albescens_clean-6130_HYZL
------------gatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggat----tggttta-------------------------
-----------------------------*
>DL;050_Aegopogon_clean-6130_HYZL
050_Aegopogon_clean-6130_HYZL
-----------tgatgggaaacccttgtgatatctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatggggc----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;NY092_Aegopogon_clean-6130_HYZL
NY092_Aegopogon_clean-6130_HYZL
-----------tgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttatactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;F41_Edmundoi_clean-6130_HYZL
F41_Edmundoi_clean-6130_HYZL
----------ccgatctgaaacccttgtgatatctcatgttcagcaacct
gggattggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcct
t----------------------------*
>DL;NY081_Papyrus_clean-6130_HYZL
NY081_Papyrus_clean-6130_HYZL
----------atgatgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctctagcatgggac----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;NY016_Kunhardtii_clean-6130_HYZL
NY016_Kunhardtii_clean-6130_HYZL
-------------------------tttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaattgttggtttggttttcct
t----------------------------*
>DL;088_Sp3_clean-6130_HYZL
088_Sp3_clean-6130_HYZL
------------gatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataagtcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggattgttccaa-cgttggtttggttttcct
t----------------------------*
>DL;A30_Aspera_clean-6130_HYZL
A30_Aspera_clean-6130_HYZL
---------ttccgatctaaacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
tcagatgg-acttgtgagaaaatttatc-*
>DL;A37_Exasperata_clean-6130_HYZL
A37_Exasperata_clean-6130_HYZL
---gatcttaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat--cccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggagatcg------
-----------------------------*
>DL;NY067_Aspera_var_clean-6130_HYZL
NY067_Aspera_var_clean-6130_HYZL
--gatcggtaatgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;A01_Aegopogon_clean-6130_HYZL
A01_Aegopogon_clean-6130_HYZL
-------------atgggaaacccttgtgatatctcatgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgatcccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcatctctctaa------------
--------------------------------------------------
-----------------------------*
>DL;114_Sp5_clean-6130_HYZL
114_Sp5_clean-6130_HYZL
----cgatctatgatgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggat----tggtttgttccaa-cgttggtttggttagatc
-----------------------------*
>DL;109_Sp9_clean-6130_HYZL
109_Sp9_clean-6130_HYZL
----------------ggaaacacttgtgatatctcatgttcagcaacct
ggaatcggtggagaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
t----------------------------*
>DL;131_Fraterna_clean-6130_HYZL
131_Fraterna_clean-6130_HYZL
aagatcggtaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cattggtttggttttcct
t----------------------------*
>DL;G09_Verticillaris_clean-6130_HYZL
G09_Verticillaris_clean-6130_HYZL
--------tattcgtgcttgtgtgtgagcccgaccagtgtccagcaacct
gggatcgatggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctccagcatgggat----tggtttgttccaa-cgttggtttggttttcct
t----------------------------*
>DL;069_Nigricans_clean-6130_HYZL
069_Nigricans_clean-6130_HYZL
-------gtaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttttcct
tt---------------------------*
>DL;NY089_Barbigera_clean-6130_HYZL
NY089_Barbigera_clean-6130_HYZL
-----------ccgatctaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-tgttggtttggttttcct
-----------------------------*
>DL;NY021_Karstenii_clean-6130_HYZL
NY021_Karstenii_clean-6130_HYZL
-------atcttgatgggaaacccttttgatacctcatgttcagcaaccc
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggagatcgg
-----------------------------*
>DL;011_Papyrus_clean-6130_HYZL
011_Papyrus_clean-6130_HYZL
----tccgatctgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcct
tt---------------------------*
>DL;A10_Melastomoides_clean-6130_HYZL
A10_Melastomoides_clean-6130_HYZL
----tctgtaatgacgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggttgtcct
ttcagatggacttgtgagaaaatttatcc*
>DL;003_Aegopogon_clean-6130_HYZL
003_Aegopogon_clean-6130_HYZL
---------------------------tgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat--cccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgaacatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcc-
-----------------------------*
>DL;NY048_Aspera_clean-6130_HYZL
NY048_Aspera_clean-6130_HYZL
aagatcggtaatgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
tt---------------------------*
>DL;073_Aegopogon_clean-6130_HYZL
073_Aegopogon_clean-6130_HYZL
----------------ggaaacccttttgatacctcgtgttcagcaacct
gggatcggcggagaagtag---------------------------ttcc
tcatcaggacaactcgttcctatacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagaatgc
ctgaagcatgggtc----tagtttgttccaa-cgttgctttggtttt---
-----------------------------*
>DL;A07_Aspera_clean-6130_HYZL
A07_Aspera_clean-6130_HYZL
----ctggtaatgatgggaaacccttgtgataccttgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;113_Sp5_clean-6130_HYZL
113_Sp5_clean-6130_HYZL
----------atgatgggaaacccttgtgatatctcatgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggacaactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggat----tggtttgttccaa-cgttggtttggttttcct
-----------------------------*
>DL;NY057_Aspera_asperrima_clean-6130_HYZL
NY057_Aspera_asperrima_clean-6130_HYZL
aagatcggtaatgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;G21_Papyrus_clean-6130_HYZL
G21_Papyrus_clean-6130_HYZL
----------atgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttgcactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctctagcatgggac----tggtttgttccaa-cgttggtttggttttcct
t----------------------------*
>DL;052a_Melastomoides_clean-6130_HYZL
052a_Melastomoides_clean-6130_HYZL
------ggtaatgatgggaaacccttttgatacctcgtgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaa-cgttggtttggttttcca
tt---------------------------*
>DL;NY056_Aspera_clean-6130_HYZL
NY056_Aspera_clean-6130_HYZL
---------aatgatgggagacccttgtgatacctcgtgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttc--gtctctaatcatgagcatgc
cttaagcatgggac----tggtttgttccaa-cgttgttttggttttcct
ttca-------------------------*
>DL;NY020_Karstenii_clean-6130_HYZL
NY020_Karstenii_clean-6130_HYZL
-----------tgatgggaaacccttttgatacctcttgttcagcaacct
gggatcggtggtgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacactgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcattaacggttgcctttgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgt
ctcaagcatgggac----tggtttgttccaa-cgttggtttgagatcg--
-----------------------------*
>DL;NY034_Spruceana_clean-6130_HYZL
NY034_Spruceana_clean-6130_HYZL
-------------------------------tcctcttgttcagcaacct
gggatcggtggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcactgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaattttgtctctctaatcatgagcatga
--------------------------------------------------
-----------------------------*
>DL;NY050_Fraterna_clean-6130_HYZL
NY050_Fraterna_clean-6130_HYZL
------gttaatgatgggaaacccgtttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgcaactgtcagtaacggttgcctttgggc
tattcctggatctcaaaaaagtaattttctctctttaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgttggtttggttttcct
t----------------------------*
>DL;NY010_Catharinae_clean-6130_HYZL
NY010_Catharinae_clean-6130_HYZL
-----------------------cttttgatacctcgtgttcagcaacct
gggatcggcggcgaagtag---------------------------ttcc
tcatcaggataactcgttcctttacaccgat-ccccctacttgcaccgga
ctgtggctggcactagaagatgccactgtcagtaacggttgcctatgggc
tattcctggatctcaaaaaagtaatttcctctctctaatcatgagcatgc
ctcaagcatgggac----tggtttgttccaatcgt---------------
-----------------------------*
