>DL;A29_Angustifolia_clean-6221_UPZX
A29_Angustifolia_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------ctgttagatgccggggtggcaatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacgaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttca-------*
>DL;NY055_Bipenicellata_clean-6221_UPZX
NY055_Bipenicellata_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------agatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagcttagatgcaag
tcacaaaggt-----gggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgtccggggtcaggtcagccatc-ttttggcttgtg
gacaatgaatgcgataatcaggtgatctagacgtggcacaaac-attttg
ggtattcatattttagat-------------------------------*
>DL;083_Sp3_2_clean-6221_UPZX
083_Sp3_2_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------agggtggcaatatca
actctctcctcctatggtgcaatgctttttggagaaagctttgatgcaag
ttacaaatgtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaag-----*
>DL;A18_Pogonanthera_2_clean-6221_UPZX
A18_Pogonanthera_2_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------gtgtgctttccgatctatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
gga----------------------------------------------*
>DL;116_Sp6_clean-6221_UPZX
116_Sp6_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------cctcctatggtgcaatgctttttggagaaagctttgatgcaag
ttacaaatgtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacatggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagta---*
>DL;NY045_Aegopogon_clean-6221_UPZX
NY045_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------ggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcatttta-------------------*
>DL;NY017_Llanorum_2_clean-6221_UPZX
NY017_Llanorum_2_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------agcaatatca
actctctcctcctatggtgcaatgctttttggagaaagctttgatgcaag
ttacaaatgtggaaagggacagtctctgtttagttggcacgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggc-----
--------------------------------------------------
-------------------------------------------------*
>DL;094_Albescens_cf_clean-6221_UPZX
094_Albescens_cf_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------ccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
ggtattcatattttcaggtggctcatgttactccgccttt---------*
>DL;092_Barbigera_aff_clean-6221_UPZX
092_Barbigera_aff_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-attttg
ggtattcatattttcaggttgctcattttattacgcctttca-------*
>DL;065_Albescens_clean-6221_UPZX
065_Albescens_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------cagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttaacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggttgctcattttattacgcctttca-------*
>DL;G14_Albescens_clean-6221_UPZX
G14_Albescens_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------tttcatgctagggtggcaatatca
actctctcctcccacggtacagtgcgttttggagaaagctttgacgcaaa
taacaaagttggaaagggacggtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtctgttttc-ttctggctcgtg
gagaatgaatacgatactcagctgatctagacgtggcacatac-tttgtg
gatattcatatttccaggtggctcattttatcacacc------------*
>DL;098_Verticillaris_clean-6221_UPZX
098_Verticillaris_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------tatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcagga------------------------------*
>DL;NY093_Aegopogon_clean-6221_UPZX
NY093_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
tctctctcctcctaaggtgcaattctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattagatcggaa----------------------------------*
>DL;080_Sp8_clean-6221_UPZX
080_Sp8_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------ggatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcgggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcagg-------------------------------*
>DL;025_Nigricans_clean-6221_UPZX
025_Nigricans_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------cgatctatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcagctgatctagacgtggcacaaac-tttttc
ggaattcatattttcaggtggctcattttactccgca------------*
>DL;NY059_Llanorum_clean-6221_UPZX
NY059_Llanorum_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaag-----*
>DL;030_Nigricans_clean-6221_UPZX
030_Nigricans_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagtac--*
>DL;126_Bruniana_clean-6221_UPZX
126_Bruniana_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------agatgccggggtggaaatatca
actctctcctcctatggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcacgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagaga--*
>DL;H40_Nigricans_clean-6221_UPZX
H40_Nigricans_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------agatgccggggtggcaatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcacgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
gatattcatattttcaggtggctcattttagtacgcctttcaa------*
>DL;100_Sp9_clean-6221_UPZX
100_Sp9_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------cttgccggggtggcaatatca
actctctccttctacggtgcaatgctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-attttg
ggtattcatattttcaggttgctcattttattacgccttt---------*
>DL;NY090_Barbigera_clean-6221_UPZX
NY090_Barbigera_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------tatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcataaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagtacaa*
>DL;NY080_Papyrifera_clean-6221_UPZX
NY080_Papyrifera_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
tctctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctgtgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgc-------------*
>DL;110_Sp6_clean-6221_UPZX
110_Sp6_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------acacgacgctctcccgatctca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattagatcg----------------*
>DL;G08_Albescens_clean-6221_UPZX
G08_Albescens_clean-6221_UPZX
----tgtggaaatcgttctgcgaatgaagaatttcgtttgagttatgggg
tcaggatttgaagctgcttggtttttgcgcatttagctcttgggtatcaa
ctgaatgtcggtagacgatgtgttgctttcgccctgatatctgagggctc
gagttttgggaacgggctagtgttgttgatggaagcttctttgtcagatt
tgtgcttctcgtgagacat-ttaactattaaaaaatagttggcaaactac
ttgtattttgttttgaaattccaccgttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgctggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttac------------------*
>DL;NY088_Barbigera_clean-6221_UPZX
NY088_Barbigera_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
tctctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcataaac-tttttg
ggt----------------------------------------------*
>DL;NY091_Barbigera_hirsutula_clean-6221_UPZX
NY091_Barbigera_hirsutula_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ccaccgagatctacacagagtaga
acactctttccctac---acgacgctcttcgatctaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcataaac-tttttg
ggtattcatattttcaggtgga---------------------------*
>DL;NY011_Catharinae_2_clean-6221_UPZX
NY011_Catharinae_2_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------tcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagacgtggtacaaac-tttttg
ggtattcatattttcaggtggctca------------------------*
>DL;055_Aegopogon_clean-6221_UPZX
055_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------cgttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaag-----*
>DL;NY051_Llanorum_clean-6221_UPZX
NY051_Llanorum_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tagatgccggggtagcaatatca
actctctcctcctatggtgcaatgctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacatggcacaaac-tttttg
ggtattcatattttcagga------------------------------*
>DL;NY094_Aegopogon_clean-6221_UPZX
NY094_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcacggttaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
gg-----------------------------------------------*
>DL;NY054_Bipenicellata_clean-6221_UPZX
NY054_Bipenicellata_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------ccagggtggcaatgtca
actctctcctcctacggtgcaatgctttttggagaaagctttgacacgag
ttacaaaggtggaaagggacagtctctgtttagctggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggttagccatc-ttttggcttgtg
gacaatgaatgtgataatcaggtgatctagacgtggcacaacc-tttttg
ggtattcatattttcaggtggag--------------------------*
>DL;079_Sp8_clean-6221_UPZX
079_Sp8_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------agatgccggggtggcaatatca
actctctcctcctatggtgcaatgctttttggagaaagctttgatgcaag
ttacaaatgtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gatgatcaggtgacctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattt---------------------*
>DL;G30_Dubia_clean-6221_UPZX
G30_Dubia_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------gggtggcaataaca
actctctcctcccacggtacagtgcattttggagaaagctttgacgcaaa
ttacaaagttggaaagggacggtttctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtctgttttc-ttctggctcgtg
gagaatgaatacgatactcagctgatctagacgtggcacatac-tttgtg
gatattcatatttccaggtggctcattttattacaccttag--------*
>DL;090_Aegopogon_aff_clean-6221_UPZX
090_Aegopogon_aff_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------atgccggggtggcaatatca
actctctcctcctacggtgcaatgctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcgcggataggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcatt----------------------*
>DL;127_Johnwurdackiana_clean-6221_UPZX
127_Johnwurdackiana_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------tgccggggtggcaatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
gatattcatattttcaggtggctcattttattac---------------*
>DL;102_Sp7_clean-6221_UPZX
102_Sp7_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------ccgttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgctataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggttgctcattttattac---------------*
>DL;G02_Johnwurdackiana_clean-6221_UPZX
G02_Johnwurdackiana_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------gatgccggggtggcaatatca
actctctcctcatacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcacggttaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgccttt---------*
>DL;044_Aegopogon_clean-6221_UPZX
044_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcacgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttca-------*
>DL;G32_Barnebyana_clean-6221_UPZX
G32_Barnebyana_clean-6221_UPZX
gtaatgtggacatcgatttgcgaatgaagaatttaatttgagttatgggg
tcaggatttgaagctgcttgg-ttttgcgcatttagcacttgggtatgga
ctgaatgtcgggagaagatgtgtttctttctccctgaaa-----------
-------------------------------------tctttgtcagatt
tgtgcttctcatgagatat-ataacaattaaaaaatggttggcaaacacg
ttgtattttgttttaaaagtccactgttagatgccagggtggcaatatca
actctctcctcccacggtacagtgcgttttggagaaagctttgacacaaa
ttacaaagttggaaagggacggtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagttttc-ttctggctcgtg
gagaatgaatacgatactcggctgatctagacgtggcacaaac-tttgtg
gatattcatatttccaggtggctcattttattacacctttca-------*
>DL;NY082_Verticillaris_clean-6221_UPZX
NY082_Verticillaris_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------ttccgatctcaatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
gatattcatatagatc---------------------------------*
>DL;NY052_Striphnocalyx_clean-6221_UPZX
NY052_Striphnocalyx_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------ccgttagatgccagggtggcaatgtca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaa------*
>DL;A35_Bruniana_clean-6221_UPZX
A35_Bruniana_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------ctgttagatgccggggtggaaatatca
actctctcctcctatggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcacgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagtacaa*
>DL;095_Barbigera_clean-6221_UPZX
095_Barbigera_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------cgatctgatgccggggtggcaatatca
actctctcctcctacggtgcaattctttttggagaaagcttcgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcggccatc-ctttggcttgtg
gacaat------gataatcaggtgatctagatgtggcacaaac-tttttg
ggtattcatattttcag--------------------------------*
>DL;111_Sp5_clean-6221_UPZX
111_Sp5_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------caatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcc------------*
>DL;066_Aegopogon_clean-6221_UPZX
066_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tagatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttca-------*
>DL;NY085_Verticillaris_clean-6221_UPZX
NY085_Verticillaris_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacagtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggttgctcattttattacgcctttca-------*
>DL;G23_Melastomoides_clean-6221_UPZX
G23_Melastomoides_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------gacat-ataactattaaaaaatagttggcaaactac
ttgtattttgttttgaaattccaccattcgatgccagggtggcaatatca
actctctcctcctatggtgcaatgctttttggagaaa-ctttgatgcaag
ttacaaatgtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gatgatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttca-------*
>DL;085_Aegopogon_aff_clean-6221_UPZX
085_Aegopogon_aff_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggttagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-ttttt-
ggtattcatattttcaggtggctcattttattacgcc------------*
>DL;014_Aegopogon_clean-6221_UPZX
014_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaacttttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagta---*
>DL;NY007_Duidae_clean-6221_UPZX
NY007_Duidae_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------ttccgatctccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagacgtggtacaaac-tttttg
ggtattcatattttccggtggctcattttattacgcctttca-------*
>DL;104_Sp6_clean-6221_UPZX
104_Sp6_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------tgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacatggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagtacaa*
>DL;039_Verticillaris_clean-6221_UPZX
039_Verticillaris_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------gtgagacatataaacaattaaaaaatggtcgggaaacttg
ttgtattttgtttttaaagtccactgttagatgccggggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaag------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagta---*
>DL;NY002_Dissitiflora_clean-6221_UPZX
NY002_Dissitiflora_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------ctcaatgctttttggagaaagctttgacgcaag
ttacaaaggtgaaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagacgtggtacaaac-tttttg
ggtattcatattttcaggta-----------------------------*
>DL;G13_Johnwurdackiana_2_clean-6221_UPZX
G13_Johnwurdackiana_2_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------cgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggc---------------------------*
>DL;NY003_Sipapoana_clean-6221_UPZX
NY003_Sipapoana_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tagatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatttagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaag-----*
>DL;061_Angustifolia_clean-6221_UPZX
061_Angustifolia_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------tgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttggttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggc-----
--------------------------------------------------
-------------------------------------------------*
>DL;NY042_Bipenicellata_clean-6221_UPZX
NY042_Bipenicellata_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------aaattccaccattagatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
tcacgaaggtggaaagggacggtctatgtttagttggcgctggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatctttttggcttgtg
gacaatgaatgcgataatcaggtgatctagacgtggcacaaac-ata---
-------------------------------------------------*
>DL;NY086_Barbigera_clean-6221_UPZX
NY086_Barbigera_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcgggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggttgctcatttt--------------------*
>DL;NY078_Angustifolia_clean-6221_UPZX
NY078_Angustifolia_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------gatgccggggtggcaatatca
actctctcctcctatggtgcaatgctttttggagaaagctttgatgcaag
ttacaaatgtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtgga---------------------------*
>DL;107_Sp7_clean-6221_UPZX
107_Sp7_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------cccgggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggttgctcattttat------------------*
>DL;018_Barbigera_clean-6221_UPZX
018_Barbigera_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacacaag
ctacaaaggtggaaagggacggtttatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatt---------------------------------------*
>DL;076_Gracilis_clean-6221_UPZX
076_Gracilis_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------atgccagggtggcaatatca
actctctcctcctacggttcaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctctgtttagttggcgccggtaggact
gatgcaggagttcatgccaggggtcaggtcagccatc-ttttggcttgtg
gacaatgaatgcgataatcatctgatctagacgtggcacaaac-ttagtg
ggtacacata---------------------------------------*
>DL;NY053_Fraterna_clean-6221_UPZX
NY053_Fraterna_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------gttagatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagacgtggtacaaac-tttttg
ggtattcatattttcaggtggctcattt---------------------*
>DL;NY077_Angustifolia_clean-6221_UPZX
NY077_Angustifolia_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------cgatc
tctctctcctcctacggtacaatgctttttggagaaagctttaacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcaa-----------
-------------------------------------------------*
>DL;G17_Aegopogon_clean-6221_UPZX
G17_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ctacaaaggtggaaagggacggtttatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
gatattcatattttcaggtggctcattttattacgcctttca-------*
>DL;A26_Rosanae_2_clean-6221_UPZX
A26_Rosanae_2_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------tatca
actctctcctcctacggtacaatgctttttggagaaagctttgatgcaag
ttacaaatgtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcgtgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacatgga-------------
-------------------------------------------------*
>DL;42_Angustifolia_clean-6221_UPZX
42_Angustifolia_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------ggtggcaatatta
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacgaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttca-------*
>DL;NY079_Albescens_clean-6221_UPZX
NY079_Albescens_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------ttccgatctgtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaacgtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttagat-----*
>DL;050_Aegopogon_clean-6221_UPZX
050_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------agatgccggggtggcaatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcacgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaa------*
>DL;NY092_Aegopogon_clean-6221_UPZX
NY092_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------tatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactcc---------------*
>DL;F41_Edmundoi_clean-6221_UPZX
F41_Edmundoi_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------tgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcaataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggttgctcattttattacgcctttca-------*
>DL;NY081_Papyrus_clean-6221_UPZX
NY081_Papyrus_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------gttagatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttagagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctgtgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttca-------*
>DL;NY016_Kunhardtii_clean-6221_UPZX
NY016_Kunhardtii_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------tcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagatgtggtacaaac-tttttg
ggtattcatattttcaggtggctcatttagatcg---------------*
>DL;G35_Ramboi_clean-6221_UPZX
G35_Ramboi_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------gctagggtggcaatatca
actctctcctcccacggtacagtgtgttttggagaaagctttgacgcaaa
ttacaaagttggaaagggacggtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtctgttttc-ttctggctcgtg
gagaatgaatacgatattcgactgatctaggcgtggcacaaac-tttgtg
gatattcatatctccaggtggctcat-----------------------*
>DL;088_Sp3_clean-6221_UPZX
088_Sp3_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tggatgtcagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-attttg
ggtattcatattttcaggtggctcatttt--------------------*
>DL;A37_Exasperata_clean-6221_UPZX
A37_Exasperata_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
tctctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
gatattcatattag-----------------------------------*
>DL;114_Sp5_clean-6221_UPZX
114_Sp5_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------cgttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattc------------------------------------------*
>DL;109_Sp9_clean-6221_UPZX
109_Sp9_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
tctctctccttctacggtgcaatgctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagta---*
>DL;131_Fraterna_clean-6221_UPZX
131_Fraterna_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------ccggggtggcaatatca
actctctcctcctacggtgcaattctttttggagaaagctttgatgcaag
ttacaaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagatgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactctgcctttcaa------*
>DL;G09_Verticillaris_clean-6221_UPZX
G09_Verticillaris_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------ca
actctctcctcctacggggcaattctttttggagaaagctttgatgcaag
ttacgaaggtggaaagggacagtctctgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaag-----*
>DL;NY089_Barbigera_clean-6221_UPZX
NY089_Barbigera_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaa------*
>DL;NY021_Karstenii_clean-6221_UPZX
NY021_Karstenii_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------ca
actctctcctcctacggtgcaatgctttttggagaaagctttgacacgag
ttacaaagatggaaagggacagtctctgtttagctggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggttagccatc-ttttggcttgtg
gacaatgaatgtgataatcaggtgatctagacgtggcacaacc-tttttg
ggtattcatatagatcg--------------------------------*
>DL;011_Papyrus_clean-6221_UPZX
011_Papyrus_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------gttagatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgtgataatcaggtgatctggatgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaag-----*
>DL;A10_Melastomoides_clean-6221_UPZX
A10_Melastomoides_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacacaag
ctacaaaggtggaaagggacggtttatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcattttttcaggttgctcattttattacgcctttcaa------*
>DL;003_Aegopogon_clean-6221_UPZX
003_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------tccgatctatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagtac--*
>DL;073_Aegopogon_clean-6221_UPZX
073_Aegopogon_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacatggcacaaac-tttttg
gatattcatattttcaggtggctcattttattacgccttt---------*
>DL;G27_Desmocelis_clean-6221_UPZX
G27_Desmocelis_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------tagggtggcagtatca
actctctcctcctaccgtacaatgcgttttggagaaagctttgacgcaaa
ttacaaaggtggaaagggacggtctctgtttggttggtgcgggtaggact
gatgcaggagttcacgcctggggtcaggtcagtcatc-ttttggctcgcg
gagaaggaatacaacggtcagtttatgaaattgttgcacaaac-tttctg
ggcatttgtattttcaggtggagatcgg---------------------*
>DL;113_Sp5_clean-6221_UPZX
113_Sp5_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacagtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggcttgtg
gacaat------gataatcaggtgatctagacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttactccgcctttcaagtac--*
>DL;G21_Papyrus_clean-6221_UPZX
G21_Papyrus_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------aatatca
actctctcctcctacggtacaatgctttttagagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctgtgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcaggtgatctggacgtggcacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaag-----*
>DL;052a_Melastomoides_clean-6221_UPZX
052a_Melastomoides_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgatgccagggtggcaatatca
actctctcctcctacggtgcaatgctttttggagaaagctttgacgcaag
ctacaaaggtggaaagggacggtttatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgatgatcaggtgatctggacgtggcacaaac-tttttg
ggtattcattttttcaggttgctcattttattacgcctttcaa------*
>DL;NY020_Karstenii_clean-6221_UPZX
NY020_Karstenii_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------atatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
tcacgaaggtggaaagggacggtctatgtttagttggcgctggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatctttttggcttgtg
gacaatgaatgcgataatcaggtgatctagacgtggcaaaaac-attttg
ggtattcatattttcaggtggcccattttattacgcctttcaa------*
>DL;NY050_Fraterna_clean-6221_UPZX
NY050_Fraterna_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------gcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagacgtggtacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaag-----*
>DL;NY010_Catharinae_clean-6221_UPZX
NY010_Catharinae_clean-6221_UPZX
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------ttagatgccagggtggcaatatca
actctctcctcctacggtacaatgctttttggagaaagctttgacgcaag
ttacaaaggtggaaagggacggtctatgtttagttggcgcgggtaggact
gatgcaggagttcatgcctggggtcaggtcagccatc-ttttggctcgtg
gacaatgaatgcgataatcagctgatctagacgtggtacaaac-tttttg
ggtattcatattttcaggtggctcattttattacgcctttcaag-----*
