>DL;A31_Aspera_clean-6226_HKMQ
A31_Aspera_clean-6226_HKMQ
-------ctaacctcatgtcgctaaaatgatcacagacatatttacgcag
gaattctggaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgcctacattctgatggag
tagagttttctaatgtaaacatctttatctagttaaacgtgaaaatttac
aagtagcttacaaac*
>DL;NY073_Aspera_clean-6226_HKMQ
NY073_Aspera_clean-6226_HKMQ
tctattttaaacctcatgtcgctaaaatgatcacagacatatttacgcag
gaattctggaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgcctacattctgatggag
tagaga--------------------------------------------
---------------*
>DL;NY070_Aspera_clean-6226_HKMQ
NY070_Aspera_clean-6226_HKMQ
--------------------gctaaaatgatcacagacatatttacgcag
gaattctggaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgcctacattctgattgtc
atgtgcggacgcacat----------------------------------
---------------*
>DL;H40_Nigricans_clean-6226_HKMQ
H40_Nigricans_clean-6226_HKMQ
--aattttaaacctcatgtcgctaaaatgatcgcagacatatttacgcag
gaattctggaggcggggtagcggcagatggtgaaatctgggctgctccat
acagatggggctgtatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgtctacattatgatggtc
actggaattcttaacttgtttgaagcaggcactgatataatatgttgatg
atggtgttcatga--*
>DL;110_Sp6_clean-6226_HKMQ
110_Sp6_clean-6226_HKMQ
-------------------------------cgcagacatatttacgcag
gaattctggaggcgggatagcggcagatggtgaaatctgggctgctccat
acagatggggctgtatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagtctaatgtctacattatgatggtc
actggaattcttaacttgtttgaagca-----------------------
---------------*
>DL;NY082_Verticillaris_clean-6226_HKMQ
NY082_Verticillaris_clean-6226_HKMQ
-------------------cgctaaaatgatcgcagacatatttacgcag
gaattctggaggcggggtagcggcagatggtgaaatctgggctgctccat
acagatggggctgtatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgtctacattatgatggtc
actggaattcttaacttgtttgaagca-----------------------
---------------*
>DL;NY072_Aspera_clean-6226_HKMQ
NY072_Aspera_clean-6226_HKMQ
---------tacctcatgtcgctaaaatgatcatagacatatttacgcag
gaattctggaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
ctaggcctggatcccatagaggtaagcctaatgcctacattctgatggag
tagagttttctaatgtaaac------------------------------
---------------*
>DL;NY046_Aspera_clean-6226_HKMQ
NY046_Aspera_clean-6226_HKMQ
-------------tcatgtcgctaaaatgatcacagacatatttacgcag
gaattctagaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgcctacattctgatggag
tagagttttctaatgtaaacatctttatcagatcgga-------------
---------------*
>DL;42_Angustifolia_clean-6226_HKMQ
42_Angustifolia_clean-6226_HKMQ
-----------------gtcgctaaaatgatctcagacatatttacgcag
gaattctggaggcggggtagcggcagatggtgaaatctgggctgctccat
acagatggggctgtatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgtctacattatgatggtc
actggaattcttaacttgtttgaagcaggcactgata-------------
---------------*
>DL;F41_Edmundoi_clean-6226_HKMQ
F41_Edmundoi_clean-6226_HKMQ
-------taaacctcatgtagctaaaatgatcgcagacatatttacgcag
gaattctggaggcggggtagcggcagatggtgaaatctgggctgctccat
accgatggggctgtatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgtctacattatgtgttag
aaccttgccgaagtaacgacggttagaaccttgccgaagtaacg------
---------------*
>DL;NY081_Papyrus_clean-6226_HKMQ
NY081_Papyrus_clean-6226_HKMQ
---------------------------------cagacatatttacgcag
gaattctggaggcggggtagcggcagatggtgaaatctgggctgctccat
acagatggggctgtatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgtctacattatgatggtc
actggaattcttaacttgtttgaagcaggcactgatagaatatgttga--
---------------*
>DL;NY067_Aspera_var_clean-6226_HKMQ
NY067_Aspera_var_clean-6226_HKMQ
----------aactcatgtcgctaaaatgatcacagacatatttacgcag
gaattctggaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgcctacattctgatggag
tagagttttctaatgtaaacatctttatctagttaaacgtgaaaatttac
aagt-----------*
>DL;131_Fraterna_clean-6226_HKMQ
131_Fraterna_clean-6226_HKMQ
-------taaacctcatgtcgctaaaatgatcgcagacatatttacgcag
gaattctggaggcggggtagcggcagatggtgaaatctgggctgctccat
acagatggggctgtatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgtcaacattatgatggtc
actggaattcttaacttgtttgaagcgggcactgatataatatgttga--
---------------*
>DL;NY057_Aspera_asperrima_clean-6226_HKMQ
NY057_Aspera_asperrima_clean-6226_HKMQ
------ttaaacctcatgtcgctaaaatgatcacagacatatttacgcag
gaattctggaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgcc-acattctga-----
--------------------------------------------------
---------------*
>DL;NY056_Aspera_clean-6226_HKMQ
NY056_Aspera_clean-6226_HKMQ
---------tctctcatgtcgctaaaatgatcacagacatatttacgcag
gaattctggaggtggggtagctgcagatggtgaaatctgggctgctccat
acagatggggctgcatggtgatagcatacaagaaaagtaaatttgaaaag
cttggcctggatcccatagaggtaagcctaatgcctacattctgatgaga
tcgga---------------------------------------------
---------------*
