>DL;A29_Angustifolia_clean-6387_HKMQ
A29_Angustifolia_clean-6387_HKMQ
------------------------------------agctcttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccgtttatgg
agtgagcatca---------------------------------------*
>DL;NY022_Mathaei_clean-6387_HKMQ
NY022_Mathaei_clean-6387_HKMQ
--------------------------------------------------
------------------------ccgatctcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacgc
caagagtgattgcatcttgcctcgcattacctttgttaacacttatgtgc
tttactat------------------------------------------
--------------------------------------------------*
>DL;NY055_Bipenicellata_clean-6387_HKMQ
NY055_Bipenicellata_clean-6387_HKMQ
----------------------------ggtgttctagcccttgcgttct
ccagggagttaagtcccgtcgttacagccatcgtcgttgctggttgcata
ggtagtgcctttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggactggcg--------------cgcagatgccatttatgg
agtgagcatcaacatcatctttgattcagcccaaagggcccttcgatggt*
>DL;092_Barbigera_aff_clean-6387_HKMQ
092_Barbigera_aff_clean-6387_HKMQ
---gttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccatttatgg
agtgagcatcaacatcatctt-----------------------------*
>DL;098_Verticillaris_clean-6387_HKMQ
098_Verticillaris_clean-6387_HKMQ
----------------------------ggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcaagcgctctactcgcagatgccgtttatgg
agtgagcatcaacatt----------------------------------*
>DL;080_Sp8_clean-6387_HKMQ
080_Sp8_clean-6387_HKMQ
--------------------------------------------------
------------gtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttcttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccatttatgg
agtgagcatcaacatcatct------------------------------*
>DL;025_Nigricans_clean-6387_HKMQ
025_Nigricans_clean-6387_HKMQ
---gttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgcaggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattaccttttttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgcc--------
--------------------------------------------------*
>DL;NY059_Llanorum_clean-6387_HKMQ
NY059_Llanorum_clean-6387_HKMQ
----ttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcatgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccatttatgg
agtgagcatc----------------------------------------*
>DL;071_Nigricans_clean-6387_HKMQ
071_Nigricans_clean-6387_HKMQ
----ttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcctttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccgtttatg-
--------------------------------------------------*
>DL;G08_Albescens_clean-6387_HKMQ
G08_Albescens_clean-6387_HKMQ
------------------------tggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcaagcgctctactcgcagatgccgtttatgg
agtgagc-------------------------------------------*
>DL;055_Aegopogon_clean-6387_HKMQ
055_Aegopogon_clean-6387_HKMQ
--------------------------------------------------
---------------------------ccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattaccttttttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccgtttatgg
agtgagcatcaaca------------------------------------*
>DL;127_Johnwurdackiana_clean-6387_HKMQ
127_Johnwurdackiana_clean-6387_HKMQ
-----------------------ttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgtattaccttttttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgctgtttatgg
agtgagcatc----------------------------------------*
>DL;044_Aegopogon_clean-6387_HKMQ
044_Aegopogon_clean-6387_HKMQ
-cggttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattaccttttttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccgtttatgg
agtgagcatcaacattatctttgattcggc--------------------*
>DL;NY052_Striphnocalyx_clean-6387_HKMQ
NY052_Striphnocalyx_clean-6387_HKMQ
---------------------------------tctagcccttgcgttct
ccagggagttgagtcccgtggttacagccatcgtcgttgccggtcgcata
ggcagtgcctttgctgctgagttaggaacaatgcaggtgtctgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcatgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcatcgagcgctctactcgcagatgccatttatgg
agtgagcatcaacatc----------------------------------*
>DL;095_Barbigera_clean-6387_HKMQ
095_Barbigera_clean-6387_HKMQ
-------------------------------------gcccttgcgttct
acagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacgc
caagagtgattgcatcttgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcaagtgctctactcgcagatgccatttatgg
ggtgagca------------------------------------------*
>DL;NY085_Verticillaris_clean-6387_HKMQ
NY085_Verticillaris_clean-6387_HKMQ
--ggttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
tgacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgcc--------
--------------------------------------------------*
>DL;G23_Melastomoides_clean-6387_HKMQ
G23_Melastomoides_clean-6387_HKMQ
----------------cgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcatcgagcgctctactcgcagatgccatttatgg
agtgagcatcaacatcatctttgattcg----------------------*
>DL;014_Aegopogon_clean-6387_HKMQ
014_Aegopogon_clean-6387_HKMQ
---gttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
ta------------------------------------------------
--------------------------------------------------*
>DL;NY086_Barbigera_clean-6387_HKMQ
NY086_Barbigera_clean-6387_HKMQ
------------gaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccatttatgg
agtgagcatcaacatcatctttgattcggcccaaagg-------------*
>DL;42_Angustifolia_clean-6387_HKMQ
42_Angustifolia_clean-6387_HKMQ
---------tttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattaccttttttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccgtttatgg
agtgagcatcaacattatctttgatt------------------------*
>DL;F41_Edmundoi_clean-6387_HKMQ
F41_Edmundoi_clean-6387_HKMQ
--------------------------------------------------
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccatttatgg
agtgagcatcaacatcatctttgatt------------------------*
>DL;NY081_Papyrus_clean-6387_HKMQ
NY081_Papyrus_clean-6387_HKMQ
---gttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattaccttttttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccgtttatgg
agtgagcatcaacat-----------------------------------*
>DL;G09_Verticillaris_clean-6387_HKMQ
G09_Verticillaris_clean-6387_HKMQ
tcggttgggtttgaatcgatctgttggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatgccgtttatgg
agtgagcatcaacatt----------------------------------*
>DL;A10_Melastomoides_clean-6387_HKMQ
A10_Melastomoides_clean-6387_HKMQ
--------------------------------------------------
--------------cccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgttaacacttatgtgc
tttactattggaatggcatcgagcgctctactcgcagatgcc--------
--------------------------------------------------*
>DL;073_Aegopogon_clean-6387_HKMQ
073_Aegopogon_clean-6387_HKMQ
--------------------------------------cccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgctggtcgcata
ggtagtgcttttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattaccttttttaacacttatgtgc
tttactattggaatggcgtcgagcgctctactcgcagatg----------
--------------------------------------------------*
>DL;NY050_Fraterna_clean-6387_HKMQ
NY050_Fraterna_clean-6387_HKMQ
--ggttgggtttgaatcgatctgtcggtggtgttctagcccttgcgttct
ccagggagttaagtcccgtggttacagccatcgtcgttgccggtcgcata
ggcagtgcctttgctgctgagttaggaacaatgcaggtgtccgagcaaac
agacaccctgagggttcttggatcaaatcccgtagactacttggtgacac
caagagtgattgcatcgtgcctcgcattacctttgctaacactaatgtgc
tttactattggaatggcatcgagcgctctactcgcagatgccatttatgg
agtgagcatcaacatcatctttgattcag---------------------*
