>DL;A29_Angustifolia_clean-6459_Torricelli
A29_Angustifolia_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------gtctggc
aattgatgtcggagcggtagctgtttttgcttttctcttctctcgcgaga
acaccgctaagaatgcccaactggcgaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgatgaaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgccgggccggcttccttca
tctctgaggcgtttaaatttagtgagccatacacgaagggccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaattcgatgagacagaggagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgctgcggagtggaccgggttagtg
cgtatatacataggcttaagacatttggctactcgggttgtcagtctgtc
tggcttggtttggctttacctcgatggtttcatccatttgtgaaaacatt
cgggagctctgatggtgtcagtttagatctccgtgatcctttggtcgttc
agattccgtttctcaatccagaactttgctgtcttaattcttgttccaaa
tcct----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY093_Aegopogon_clean-6459_Torricelli
NY093_Aegopogon_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------cttgtgatatgtgccgggccggcttccttca
tctctgaggcgtttaaattcagtgagccatacacgaagggccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaatacgccttcttt
cgaattcgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgctgcggagtggaca---------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;100_Sp9_clean-6459_Torricelli
100_Sp9_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------ggc
aattgatgtcggagcggtagctgtttttgcttttctcttctctcgcgaga
acaccgctaagaatgcccaactggcgaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgatgaaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgccgggccggcttccttca
tctctgaggcgtttaaattcagtgagccatacacgaaggaccttctggaa
agaggggtgctcgtagtgccttttcccactgacggaaacacgccttcttt
cgaattcgatgagacagaagagatgaaagatctgacaagcagaaggagaa
ggctttggcagttaaaccctgtttatgccacggagtggaccgggtaagtg
ggcatatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttacctcgatggtttcatccatttgtgaa------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY090_Barbigera_clean-6459_Torricelli
NY090_Barbigera_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------gcgaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgatgaaaagaggataataccggtcagctt
gctcagaggagccgcccgtcttgtgatatatgccgggccggcttccttca
tttctgaggcgtttaaattcagtgaaccatacacgaaggaccttctggaa
agaggggtgctcgtagtgccctttaccactgacggaaatacgccttcttt
cgaattcgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgctgcggagtggaccgggtaagtg
catatatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttacctcgatggtttcatccatttgtgaaaacatt
cgggagctctgatggtgtcagtttagat----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY088_Barbigera_clean-6459_Torricelli
NY088_Barbigera_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------ctgaagctccgtattgatgaaaagaggataataccggtcagctt
gctcagaggagccgcccgtcttgtgatatatgccgggccggcttccttca
tttctgaggcgtttaaattcagtgaaccatacacgaaggaccttctggaa
agaggggtgctcgtagtgccctttaccactgacggaaatacgccttcttt
cgaattcgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgctgcggagtggaccgggtaagtg
catatatacataggcttaagacatttggctactcaggttgtcagtctgt-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY011_Catharinae_2_clean-6459_Torricelli
NY011_Catharinae_2_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------ggagagcctt
tctagtctgaagctccgtattgacgaaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgacgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgccgcggagtggaccaggtaagtg
cgtgtatacataggcttaagacatttggctactcaggttgtcagtctgt-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;102_Sp7_clean-6459_Torricelli
102_Sp7_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
-----------------------cacggccaagatacggagcgaagttct
gtccccgttccgttccgttcggatgttcttttacgtcgccttcatggcaa
gtggtgctcttggaggcctcattgccaccacccagttgatcgctgctcta
tcgaaccctgccagggctgttgatgttccggagatttcgaaaggtctggc
aattgatgtcggagcggtagctgtttttgcttttctcttctctcgcgaga
acaccgctaagaatgcccaactggcgaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgatgaaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgccgggccggcttccttca
tctctgaggcgtttaaattcagtgagccatacacgaaggaccttctggaa
agaggggtgctcgtagtgccttttcccactgacggaaacacgccttcttt
cgaattcgatgagacagaagagatgaaagatctgacaagcagaaggagaa
ggctttggcagttaaaccctgtttatgccacggagtggaccgggtaagtg
ggcatatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttacctcgatggtttcatccatttgtgaaaacatt
cgggagctctgatggtgccagtttagatctccgtgatcctttggtcgttc
agattccgtttttcaacccagaactttgctgtcctaattcttgttccaaa
tccttggcaggtggctagaagagcaaaagaaactcgcaggcgtctccccg
gactcacccgtgtaagccgcttcgcgacctcatcaaagctt---------
------------cgaagagaa-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;G02_Johnwurdackiana_clean-6459_Torricelli
G02_Johnwurdackiana_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------gatgaaagggggataatatcagtcagctc
acttagaggagctgcccgtcttgtgatatgtgctggcccagtttctttca
ttgccgaggcattcaagcttagtgagccatacactgagggccttctggag
agggcggtgctcgtagtgccttttgctactgatggaaatacgccttcttt
cgaatttgatgagacagaggagatgaaagatttgacaggcaaaagaaaaa
ggctttggaagttggctcctgtttatgcatcagagtggtcgaggtaagag
tctgaga-tcgg--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY052_Striphnocalyx_clean-6459_Torricelli
NY052_Striphnocalyx_clean-6459_Torricelli
aatgcttggtggttggattcttgattagtttttgtgatctgagcaccggc
gatgcaattagtccatgcctatcgtggtcacctggtgggctctgtactaa
cgacttattgtccgtttcagctccacggccaagatacgtagcgaagttct
gtccccgttccgttccgttcggatgttcttttacgtcgccttcatggcaa
gtggtgctcttggaggcctcattgccactacccagttgatcgctgctcta
tcgaaccctgccagggctgttgacgttccggagatttcgaaaggtctggc
aatcgatgtcggagcggcggctgtttttgcttttctcttctctcgcgaga
acaccactaagaatgcccaactggcgaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgacgaaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgccgcagagtggaccgggtaagtg
cgtgtatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttaccttgatggtttcatccgtttgtgaaaacatt
cgggagctctgatgttgtcagtatagatctccgtgatcctatggtcattc
agattccgtttctcaatccagaactttgccgtcttaattcttgttccaac
tccttggcaggtggctagaagagcaaaagaaactcgcaggcgtctccccg
gactcacccgtgtaagatgcttcacgacctcatcagggattgtcttgctc
ctcgtaaagcctcaaaaacaacgctcacactcgatg--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY007_Duidae_clean-6459_Torricelli
NY007_Duidae_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------ggcaaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgacgaaaagaggataataccagtcagctt
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgacgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatccactgtttatgccgcggagtggactgggtaagtg
cgtgtaa-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY009_Duidae_2_clean-6459_Torricelli
NY009_Duidae_2_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------ggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgacgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctatttatgccgcggagtggactgggtaagtg
cgtgtatacataggc-taagacatttggcagat-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY002_Dissitiflora_clean-6459_Torricelli
NY002_Dissitiflora_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------gctt
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctatggcagttatcccctgtttatgccgcagagtggaccgggtaagtg
cgtgtatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtt----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY003_Sipapoana_clean-6459_Torricelli
NY003_Sipapoana_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---aatctgaagctccgtattggcgaaaagaggataataccggtcagctt
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgccgcagagtggaccgggtaagtg
cgtgtatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttaccttggtggtttcatccgtttgtgaaaacatt
cgggagctctgatgttgtcagtatagatctccgtgatcctatgg------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY023_Edmundoi_clean-6459_Torricelli
NY023_Edmundoi_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------ctgcccgtcttgtgatatgtgctggcccagtttctttca
ttgccgaggcattcaagcttagtgagccatacactgaggcccttctggag
agggcggtgctcgtagtgccttttgctaccgatggaaatacgccttcttt
cgaatttgatgagacagaggagatgaaagatttgacaggcaaaagaaaaa
ggctttggcagttggctcctgtttatgcatcagagtggtcgagga-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;107_Sp7_clean-6459_Torricelli
107_Sp7_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------gttgatcgctgctcta
tcgaaccctgccagggctgttgatgttccggagatttcgaaaggtctggc
aattgatgtcggagcggtagctgtttttgcttttctcttctctcgcgaga
acaccgctaagaatgcccaactggcgaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgatgaaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgccgggccggcttccttca
tctctgaggcgtttaaattcagtgagccatacacgaaggaccttctggaa
agaggggtgctcgtagtgccttttcccactgacggaaacacgccttcttt
cgaattcgatgagacagaagagatgaaagatctgacaagcagaaggagaa
ggctttggcagttaaaccctgtttatgccacggagtggaccgggtaagtg
ggcatatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttacctcgatggtttcatccatttgtgaaaacatt
cgggagctctgatggtgccagtttagatctccgtgatcct----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY053_Fraterna_clean-6459_Torricelli
NY053_Fraterna_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------gggaggagagcctt
tctaatctgaagctccgtattgacgaaaagaggataataccagtcagctt
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgacgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgccgcggagtggactgggtaagtg
cgtgtatacataggc-taagacatttggctactcaggttgtcagtcagtc
tggcttggtttggctttaccttgatggtttcatccgtttgtgaaaacatt
cgggagctctgatgttgtcagtatagatctccgtcatcctatggtcattc
a-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;050_Aegopogon_clean-6459_Torricelli
050_Aegopogon_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------aaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgccgggccggcttccttca
tctctgaggcgtttaaattcagtgagccatacacgaagggccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacaccttcttt
cgaatttgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgctgcggagtggaccgggtaagtg
cgtatatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttacatcgatggtttcatccttttgtgaaaacatt
cgggagc-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY016_Kunhardtii_clean-6459_Torricelli
NY016_Kunhardtii_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------taccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctccgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgacgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgccgcggagtggaccaggtaagtg
cgtgtatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggtttggtttggctttaccttggtggtttcatccgtttgtgaaaacatt
cggga---------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;G35_Ramboi_clean-6459_Torricelli
G35_Ramboi_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------tatgtgctggcccagcttctttca
tcgccgaggcattcaagcttagtgagccatacactgagggccttctggag
aggggggtgctcgtagtgccttttgctaccgatggaaatacgccttcttt
cgaatttgatgagacagaggagatgaaagatttgacaggcaaaagaaaaa
ggctttggcagttagctccagtttatgcatcagagtggtcgaggtaagag
tctgttt-caaggaaaatgtatgtgtagacacacgtgttgaatgtccaaa
ttttttgcaaaagatataacctagtcctaaacttttttcaa---------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY089_Barbigera_clean-6459_Torricelli
NY089_Barbigera_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------gataataccggtcagctt
gctcagaggagccgcccgtcttgtgatatatgccgggccggcttccttca
tttctgaggcgtttaaattcagtgaaccatacacgaaggaccttctggaa
agaggggtgctcgtagtgccctttaccactgacggaaatacgccttcttt
cgaattcgatgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgctgcggagtggaccgggtaagtg
catatatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggcttggtttggctttacctcgatggtttcatccatttgtgaaaacatt
cgggagctctgatggtgtcagtttagatctccgtgatcctttggtcgttc
agattccgttgctcaatccagaactttgctgtcttaattcttgttccaaa
tccttggcaggtggctagaagagcaaaagaaactcgcaggcgtctccccg
gactcacccgtgtaagccgcttcgtgacctcatcaag-------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;011_Papyrus_clean-6459_Torricelli
011_Papyrus_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------tcagtcagctc
acttagaggagctgcccgtcttgtgatatgtgctggcccagcttctttca
ttgtggaggcattcaagcttagtgagccatacactgagggccttctggag
agggcggtgctcgtagtgccttttgctaccgatggaaatacgccttcttt
cgaatttgatgagacagaggagatgaaagatttgacaggcaaaagaaaaa
ggctttggcagttagctcctgtttatgcatcagagtggtcgaggtaagag
tctgttt-tgaggaaaatgtatgtctagacacacgtttttaatgtccaaa
ttttttgcaaaag-------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
>DL;NY050_Fraterna_clean-6459_Torricelli
NY050_Fraterna_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
-gacttattgtccgtttcagctccacggccaagatacgtagcgaagttct
gtccccgttccgttccgttcggatgttcttttacgtcgccttcatggcaa
gtggtgctcttggaggcctcattgccactacccagttgatcgctgctcta
tcgaaccctgccagggctgttgacgttccggagatttcgaaaggtctggc
aatcgatgtcggagcagtggctgtttttgcttttctcttctctcgcgaga
acaccgctaagaatgcccaactggcaaggctgtccagggaggagagcctt
tctaatctgaagctccgtattgacgaaaagaggataataccagtcagctt
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgacgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgccgcggagtggactgggtaagtg
cgtgtatacataggc-taagacatttggctactcaggttgtcagtcagtc
tggcttggtttggctttaccttgatggtttcatccgtttgtgaaaacatt
cgggagctctgatgttgtcagtatagatctccgtcatcctttggtcattc
agattccgtttctcaatccagaactttgccgtcttaattcttgttccaac
tccttggcaggtggctagaagagcaaaagaaactcgcaggcgtctctccg
gactcacccgtgtaagatgcttcgcgacctcatcagggcttgtcttgctc
ctcataaagcctcgaagacaacgctcacactcgatgaatacggtcattac
aggtacttatccctaaggttggacggccgcgtgcgtgggagcggggttgg
ctaccctccatggaacgcgttcgtcgtacaactccctccggtcaagggca
tgtggtcggggctgctcgacggtatggacggaagagtgctctgaactaat
tcacggcacctaccgatagacagactactccggcgaaggaggccccaaga
cagcacagcgtg*
>DL;NY010_Catharinae_clean-6459_Torricelli
NY010_Catharinae_clean-6459_Torricelli
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--taatctgaagctccgtattgacgaaaagaggataataccggtcagctc
gctcagaggagccgcccgtcttgtgatatgtgctgggccggcttccttca
tctctgaggcgtttaaactcagtgagccatacacaaaggaccttctggaa
agaggggtgctcgtagtgccctttcccactgacggaaacacgccttcttt
cgaatttgacgagacagaagagatgaaagatctgacaagcaaaaggagaa
ggctttggcagttatcccctgtttatgccgcggagtggaccaggtaagtg
cgtgtatacataggcttaagacatttggctactcaggttgtcagtctgtc
tggc----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------*
