>DL;A29_Angustifolia_clean-6488_KBRW
A29_Angustifolia_clean-6488_KBRW
---------------------------------------------agttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
t-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;A18_Pogonanthera_2_clean-6488_KBRW
A18_Pogonanthera_2_clean-6488_KBRW
--------------------------------------------------
--------tattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagcgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttagatcgggag
agcgtcgtgtagggaaagagtgttactccttg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;094_Albescens_cf_clean-6488_KBRW
094_Albescens_cf_clean-6488_KBRW
--------------------------------------------------
------------------gtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagcgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggctcttgagaaccgatt-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;065_Albescens_clean-6488_KBRW
065_Albescens_clean-6488_KBRW
-------------------------------------------------g
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgaga------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;098_Verticillaris_clean-6488_KBRW
098_Verticillaris_clean-6488_KBRW
-------------------------------------gtagaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacaaaactc
tg------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;NY093_Aegopogon_clean-6488_KBRW
NY093_Aegopogon_clean-6488_KBRW
--------------------------------------------------
--------tattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttga---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;025_Nigricans_clean-6488_KBRW
025_Nigricans_clean-6488_KBRW
------------------------------------------agtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgatt-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;030_Nigricans_clean-6488_KBRW
030_Nigricans_clean-6488_KBRW
--------------------------------------tagaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
tg------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;H40_Nigricans_clean-6488_KBRW
H40_Nigricans_clean-6488_KBRW
----------------------------------------------gttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagagtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaa---
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;071_Nigricans_clean-6488_KBRW
071_Nigricans_clean-6488_KBRW
---------------------------------------agaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ccgttctttgtcgtgtcctttggttcttgagaaccgattctacagaacta
g-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;055_Aegopogon_clean-6488_KBRW
055_Aegopogon_clean-6488_KBRW
--------------------------------------------------
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagcgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
tg------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;NY094_Aegopogon_clean-6488_KBRW
NY094_Aegopogon_clean-6488_KBRW
--------------------------------------------------
-------------gttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagcgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtccagatcg--------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;127_Johnwurdackiana_clean-6488_KBRW
127_Johnwurdackiana_clean-6488_KBRW
--------------------------------------------------
---acatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtccttcggt--------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;G02_Johnwurdackiana_clean-6488_KBRW
G02_Johnwurdackiana_clean-6488_KBRW
--------------------------------------------------
-----------------tgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
tgtgatgttatatttctgcaagaagtatgatgcttctcatgtgatgccgt
taggtggttaatggaagggtatgcggcgacattgcagtgtctcgagcttt
tggggacatacgtttcaagacaaagaaacaggagttggtttctgaatccc
tttgatcaaacagcttagatattgcggaagattaatgtattcaaggctaa
tgtttactgttatttttactg*
>DL;NY082_Verticillaris_clean-6488_KBRW
NY082_Verticillaris_clean-6488_KBRW
--------------------------------------------------
---tcatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagcgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcct-------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;111_Sp5_clean-6488_KBRW
111_Sp5_clean-6488_KBRW
--------------------------------------------------
-tctcatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcc--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;066_Aegopogon_clean-6488_KBRW
066_Aegopogon_clean-6488_KBRW
---------------------------------------agaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagcgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
t-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;014_Aegopogon_clean-6488_KBRW
014_Aegopogon_clean-6488_KBRW
----------------------------------------------gttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattcta--------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;039_Verticillaris_clean-6488_KBRW
039_Verticillaris_clean-6488_KBRW
--------------------------------------------------
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattgtggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgtgaaccgattc----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;061_Angustifolia_clean-6488_KBRW
061_Angustifolia_clean-6488_KBRW
--------------------------------------------------
taaacatgaattggttttgtactcttggcgatatctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgat------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;42_Angustifolia_clean-6488_KBRW
42_Angustifolia_clean-6488_KBRW
-----------------------------------------aagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgtgaaccgattctacagaactc
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;NY079_Albescens_clean-6488_KBRW
NY079_Albescens_clean-6488_KBRW
----------------------------------------gaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
t-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;NY092_Aegopogon_clean-6488_KBRW
NY092_Aegopogon_clean-6488_KBRW
--------------------------------------tagaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttcttta----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;114_Sp5_clean-6488_KBRW
114_Sp5_clean-6488_KBRW
--------------------------------------------------
-------------------tactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;G09_Verticillaris_clean-6488_KBRW
G09_Verticillaris_clean-6488_KBRW
----------------------------------------cgatctgttg
taaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtccagatcggaaagagcgtcgtgtagggaaag---
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;069_Nigricans_clean-6488_KBRW
069_Nigricans_clean-6488_KBRW
g-----------------------------------agtagaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaactc
tgtgatgttatatttctgcaagaagtatgatgcttctcatgtgatgccgt
taggtggttaatggaagggtatgcggcgacattgcagtgtctcgagcttt
tggggacatacgtttcaagacaaagaaacaggagttggtttctgaatccc
tttgatcaaacagc------------------------------------
---------------------*
>DL;073_Aegopogon_clean-6488_KBRW
073_Aegopogon_clean-6488_KBRW
--------------------------------------------------
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagcgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaact-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;G27_Desmocelis_clean-6488_KBRW
G27_Desmocelis_clean-6488_KBRW
ggttttgatgatttctctcgttttctcgcgtgaattagtatccctatgac
tggaacgcaactggaattgtcctgccagca-----ttaagttcagtgggg
atttgctcgtcgcatctccagatgtatatcaagtaccgctaggttcagat
gcagagttcgtcgtattagcgtccgatggtctatgggacttcatgagcag
gtattagcgtggtgataa------tctgttaggattcataagattcttac
atctgcttag----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
>DL;113_Sp5_clean-6488_KBRW
113_Sp5_clean-6488_KBRW
--------------------------------------tagaagtagttg
caaacatgaattggttttgtactcttggcgatttctcatcttggaagttg
atatattcattttggatgaaggttctttctagatcagggaaggcagaagt
gctgacagatcctcaccggccttatgggagcggtaaagtgtcccttgcag
agatcaggaggataagagaagcaggtggatgggtgtgtttgttttgtcct
ctgttctttgtcgtgtcctttggttcttgagaaccgattctacagaa---
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------*
