>DL;NY060_Aspera_odd1_clean-6506_UPZX
NY060_Aspera_odd1_clean-6506_UPZX
-------------------------------gtgtgggcgctggccaggt
ac-ttccattacgacgtcgatgggaaatatgatgaacttcggcatttgct
tgcgaagtaaatgtttccaatcaataacaggtgattaaggggcttgacga
agggatcctcggcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaaccccattctgtcatttc-------------------
------------------------*
>DL;A31_Aspera_clean-6506_UPZX
A31_Aspera_clean-6506_UPZX
-------------------tatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcaacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccaatcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcagagttggtactcagtgt*
>DL;NY073_Aspera_clean-6506_UPZX
NY073_Aspera_clean-6506_UPZX
-------------------------------gtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actaga------------------*
>DL;NY011_Catharinae_2_clean-6506_UPZX
NY011_Catharinae_2_clean-6506_UPZX
----------aaggacagttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcaacaggagatatgatggactttggcatttgct
tgcgaagtaaatgtttccgatcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggtcggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaaccccattctgccatttcacgatagaagactgttaat
acaga-------------------*
>DL;NY033_Spruceana_clean-6506_UPZX
NY033_Spruceana_clean-6506_UPZX
----------------------------------tgggtgctggccaggt
acgttccattacgacgtcagcggggaatatgatgatctttggcatttgct
tgcgaagtaaatatttccgattaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcctag
gatccgtaagttgacaccattctgccatttcgcaaaagaagactgttatt
accagc------------------*
>DL;NY065_Aspera_var_clean-6506_UPZX
NY065_Aspera_var_clean-6506_UPZX
-------ccgatctacagttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttagcaaaagaagactgttatt
actagcagagt-------------*
>DL;G05_Aspera_clean-6506_UPZX
G05_Aspera_clean-6506_UPZX
-----------------------catattccgtgtgggcgctggccaggt
ac-ttccattacaacatcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcagagttggta--------*
>DL;A08_Aspera_clean-6506_UPZX
A08_Aspera_clean-6506_UPZX
---------aaaggacagttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actggcagagttggtactcagtg-*
>DL;NY046_Aspera_clean-6506_UPZX
NY046_Aspera_clean-6506_UPZX
---------aaaggacagttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcagagttg-----------*
>DL;NY061_Aspera_odd1_clean-6506_UPZX
NY061_Aspera_odd1_clean-6506_UPZX
-----------------------catattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccaatcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgagatcggga---------
------------------------*
>DL;NY068_Aspera_clean-6506_UPZX
NY068_Aspera_clean-6506_UPZX
--------ttccgatctgttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccaatcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcag----------------*
>DL;A30_Aspera_clean-6506_UPZX
A30_Aspera_clean-6506_UPZX
--------ccgatctcagttatacatattccgtgtgggtgctggccaggt
acgttccattacgacgtcagcggggaatatgatgatctttggcatttgct
tgcgaagtaaatatttccgattaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggaggaaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcagagttg-----------*
>DL;NY067_Aspera_var_clean-6506_UPZX
NY067_Aspera_var_clean-6506_UPZX
---------aaaggacatgtatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcagagttggtactcagt--*
>DL;A07_Aspera_clean-6506_UPZX
A07_Aspera_clean-6506_UPZX
------------------ttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcggcatttgct
tgcgaagtaaatgtttccaatcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcagagttggtactcagaga*
>DL;NY057_Aspera_asperrima_clean-6506_UPZX
NY057_Aspera_asperrima_clean-6506_UPZX
catggacccggtgaaattgaattcatatctccttcggctggtcgagaagg
ga------ggtggaactggactgtgactcctctattacattacgtagaag
tccatagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcag----------------*
>DL;NY056_Aspera_clean-6506_UPZX
NY056_Aspera_clean-6506_UPZX
------gagaaaggacagttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcgacgggaaatatgatgaacttcagcatttgct
tgcgaagtaaatgtttccagtcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggttggagggaaaaggcgtctgtatatcccgg
gatccgtaagttaatcccattctgtcatttcgcaaaagaagactgttatt
actagcagagtagatcgga-----*
>DL;NY010_Catharinae_clean-6506_UPZX
NY010_Catharinae_clean-6506_UPZX
-------------gacagttatacatattccgtgtgggcgctggccaggt
ac-ttccattacgacgtcaacaggagatatgatggactttggcatttgct
tgcgaagtaaatgtttccgatcaataacaggtgattaaggggcttgacga
agggatcctcagcatgaaggtcggagggaaaaggcgtctgtatatcccgg
aatccgtaagttaaccccattctgccatttcacgatagaag---------
------------------------*
