>DL;A29_Angustifolia_clean-6679_IMZV
A29_Angustifolia_clean-6679_IMZV
--------------------------------------------------
-------------agcatctgtcaattcttcattttctctaagtgatcat
tgtacttta-caggcagtcattttgcagcctctaggagagaggggaattg
cagtcattggtggtgacaggataaggggcttcactacatctgatcaggtt
tatcttttgtactttaatgaagactacatttagcagctcaattattcaaa
tcg-----------------------------------------------
----------------------------------*
>DL;G14_Albescens_clean-6679_IMZV
G14_Albescens_clean-6679_IMZV
--------------------------------------------------
--tgcgctgggcttgcatctatcaattctttgttttctgtaagtgatcat
tgtacttta-caggcagtcattttgcaacctctaggggagaggggaattg
cagtcattggtggtgacatgatacggggcttcactacatctgatcaggtt
tatcttttatactttactgaagagtacatttagcagctcaattattctat
tttactatgccgagctctgtttgcattaaactgtca--------------
----------------------------------*
>DL;025_Nigricans_clean-6679_IMZV
025_Nigricans_clean-6679_IMZV
--------------------------------------------------
--tgcgtgggccttgcatcagtcaattcttcgttttctgtaagtgatcat
tgtacttta-caggcagtcattttgcagcctctaggagagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tatcttttgtactttaatgaagactacatttagcagctcaattattctat
tttaccatgccaggctttgtttgcattaaactgtctatgaatgtgt----
----------------------------------*
>DL;NY059_Llanorum_clean-6679_IMZV
NY059_Llanorum_clean-6679_IMZV
--------------------------------------------------
------------------------attcttcattttctctaagtgatcat
tgtacttta-caggcagtcattttgcagcctctaggagagaggggaattg
cagtcattggtggtgacaggataaggggcttcactacatctgatcaggtt
tatcttttgtactttactgaagtctacatttatcag------aattctat
tttactattccgggctttgtttgcattaaactg-----------------
----------------------------------*
>DL;G30_Dubia_clean-6679_IMZV
G30_Dubia_clean-6679_IMZV
--------------------------------------------------
------------------------tttctttgttttctgtaagtgatcat
tgtacttta-caggcagtcattttgcaacctctaggggagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tatcttttatactttactgaagagtacatttagcagctcaattattctat
tttactatgccga-------------------------------------
----------------------------------*
>DL;G32_Barnebyana_clean-6679_IMZV
G32_Barnebyana_clean-6679_IMZV
--------------------------------------------------
------ctgggcttgcatctgtcaattctttgttttccgtaagtgatcat
tgtacttta-caggcagtcattttgcaacctctaggggagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tatcttttatactttactgaagagtacatttagcagctcaattattctat
tttaatatgccgagctctgtttgca-------------------------
----------------------------------*
>DL;NY052_Striphnocalyx_clean-6679_IMZV
NY052_Striphnocalyx_clean-6679_IMZV
------------------------------------------------gt
gccatcgctatagagcatcagtcaattcttcattttctgtaagcgatcat
tgtacttta-caggcagtcattttgcagcctcttggagagaggggaattg
cagtcattggtggtgacaggataaggggcttcactacatctgatcaggtt
tatcttttgtactttactgaagactacatttagcag------aattctat
tttactattccgggctttgtttgcattaaactg-----------------
----------------------------------*
>DL;A35_Bruniana_clean-6679_IMZV
A35_Bruniana_clean-6679_IMZV
--------------------------------------------------
------------------------------------------ttgatcat
tgtacttta-caggcagtcattttgcagcccttaggggagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tatcttttgtactttaatgaagactacatttagcagctcagttattctat
tttaccatgccaggctttgtttgcattaaactgt----------------
----------------------------------*
>DL;014_Aegopogon_clean-6679_IMZV
014_Aegopogon_clean-6679_IMZV
--------------------------------------------------
--tgcgtgggccttgcatcagtcaattcttcgttttctgtaagtgatcat
tgtacttta-caggcagtcattttgcagcccctaggggagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tatcttttgtactttactgaagtctacatttatcag------aattctat
tttactattccgggctttgtttgcattaaactgtctatgaatgtgttcca
tccacagacatggataaca---------------*
>DL;42_Angustifolia_clean-6679_IMZV
42_Angustifolia_clean-6679_IMZV
--------------------------------------------------
--gatctctatagagcatctgtcaattcttcattttctctaagtgatcat
tgtacttta-caggcagtcattttgcagcccctaggggagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tatcttttgtactttaatgaagaccacatttagcagctcaattattca--
--------------------------------------------------
----------------------------------*
>DL;NY081_Papyrus_clean-6679_IMZV
NY081_Papyrus_clean-6679_IMZV
--------------------------------------------------
----ttccgatctagcatctgtcaattcttcattttctctaagtgatcat
tgtacttta-caggcagtcattttgcagcctctaggagagaggggaattg
cagtcattggtggtgacaggataaggggcttcactacatctgatcaggtt
tatcttttgtactttactgaagtctacatttatcaa------aattctat
tttactattccgggctttgtagatc-------------------------
----------------------------------*
>DL;G35_Ramboi_clean-6679_IMZV
G35_Ramboi_clean-6679_IMZV
--------------------------------------------------
----cgctgggcttgcatctgtcaattctttgttttctgtaagtgaccat
tgtacttta-caggcagtcattttgcaacctctaggggagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tatcttttttacttaactgaagagtacatttagcagctcaattattctat
tttactatgccgagctttgtttg---------------------------
----------------------------------*
>DL;A30_Aspera_clean-6679_IMZV
A30_Aspera_clean-6679_IMZV
--------------------------------------------------
--tgcgctggccttgcatcggtcaattctttgtttcctttaagtgatcac
tgtacttta-caggcagtgattttgcagcctctaagggagaggggaattg
cagtcattggtggtgacatgataaggggcttcactacatctgatcaggtt
tac--------------tgaagagtatatttagcagctcaattattctat
tttactatac--ggctttgtttgcattaaactgtccatggatgtgtt-ca
tctacagacttggataacataccttgcagacaag*
>DL;131_Fraterna_clean-6679_IMZV
131_Fraterna_clean-6679_IMZV
--------------------------------------------------
----------ccttgcatcagtcaattcttcgttttctgtaagtgatcat
tgtacttta-caggcagtcattttgcagcccctaggggagaggggaattg
cagtcattggtggtgacatgattaggggcttcactacatctgatcaggtt
tatcttttgtactttaatgaagactacatttagcagctcaattattctat
ttta----------------------------------------------
----------------------------------*
>DL;G27_Desmocelis_clean-6679_IMZV
G27_Desmocelis_clean-6679_IMZV
catctatgactgttttcttgtgccattgctgtacctcttgagttctctta
tttgcattgggtttgcagccgtcaatactttgagtt-tgtaagtaatcat
tgtgctttagtaggcggtcattttgcaacctctaggggacaggggaattg
cagtcattggtggtgacacgataaggggcttcactacatctgatcaggta
tctctttcatctgtttgagta-actctctttattttcctgataatgccac
tgatggatacgtatctgattggtcattttttctgacatttttttaat-ca
ctccagctccagtatgc-----------------*
