>DL;NY060_Aspera_odd1_clean-6780_AXNH
NY060_Aspera_odd1_clean-6780_AXNH
--------------------------------------------------
-------tcagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcggggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaaca----
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;A31_Aspera_clean-6780_AXNH
A31_Aspera_clean-6780_AXNH
-tggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactcttttt---------------------------------
--------------------------------------------------
----------------*
>DL;NY073_Aspera_clean-6780_AXNH
NY073_Aspera_clean-6780_AXNH
-tggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactctt------------------------------------
--------------------------------------------------
----------------*
>DL;A18_Pogonanthera_2_clean-6780_AXNH
A18_Pogonanthera_2_clean-6780_AXNH
-tggtcattcctcttgtagtttgccggtgtcgatccattacaggcaggga
atgttgttcagttagtcctggtcctgggactgactgttgggtggatatca
acttacatatttcgggtctcgaacaaggagatgacatatgctcaacagtt
acgagactatgaatacaaggtcatggaggtaaatatcagcgaaaacatcg
acacttcta-----------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY074_Aspera_clean-6780_AXNH
NY074_Aspera_clean-6780_AXNH
--------------------------------------------------
ttgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcggggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaaca----
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY090_Barbigera_clean-6780_AXNH
NY090_Barbigera_clean-6780_AXNH
-------------------------------tatccattacaggcaggga
atgttgttcagttagtcctggtcctgggactgactgttgggtggatatca
acttacatatttcgggtctcgaacaaggagatgacatatgctcaacagtt
acgagactatgaatacaaggtcatggaggtaaatatcagcggaaacatcg
acgcttctttgacatttttccgaaatga----------------------
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY071_Aspera_clean-6780_AXNH
NY071_Aspera_clean-6780_AXNH
----------------------tccggagtcgatccattacaggcaggga
atgacgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacga----------------------
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY065_Aspera_var_clean-6780_AXNH
NY065_Aspera_var_clean-6780_AXNH
-------------gtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatta------------------------------------------
--------------------------------------------------
----------------*
>DL;G05_Aspera_clean-6780_AXNH
G05_Aspera_clean-6780_AXNH
-tggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtccagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactcttt-----------------------------------
--------------------------------------------------
----------------*
>DL;NY072_Aspera_clean-6780_AXNH
NY072_Aspera_clean-6780_AXNH
--------------------------------------------------
-------tcagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcggggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacag---
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;A08_Aspera_clean-6780_AXNH
A08_Aspera_clean-6780_AXNH
--ggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactctttttt--------------------------------
--------------------------------------------------
----------------*
>DL;NY046_Aspera_clean-6780_AXNH
NY046_Aspera_clean-6780_AXNH
-tggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcggggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactctttttttttttttttgggcaagcagaagcggatcgaaa
gcctgatggaagctgaacatccggcgctgctcgaacaggtcaaaatagag
aaggagactcttggcc*
>DL;G23_Melastomoides_clean-6780_AXNH
G23_Melastomoides_clean-6780_AXNH
-----------------agtttgccggtgtcgatccattacaggcaggga
atgttgttcagttagtcctggtcctgggactgactgttgggtggatatca
acttacatatttcgggtctcgaacaaggagatgacatatgctcaacagtt
acgagactatgaatacaaggtcatggaggtaaatatcagcgaaaacatcg
acacttctttgacatttttccaaaatgttc-tcgtctaattgaacaaacc
ggtcgtttac----------------------------------------
--------------------------------------------------
----------------*
>DL;NY061_Aspera_odd1_clean-6780_AXNH
NY061_Aspera_odd1_clean-6780_AXNH
-----------------------------------------tggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcggggaaaacttcg
acgcttctttgacattgttccgaaacgttt--------------------
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY047_Aspera_aspera_clean-6780_AXNH
NY047_Aspera_aspera_clean-6780_AXNH
----tcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcga-------
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY068_Aspera_clean-6780_AXNH
NY068_Aspera_clean-6780_AXNH
----tcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcggggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactctttttttt------------------------------
--------------------------------------------------
----------------*
>DL;F41_Edmundoi_clean-6780_AXNH
F41_Edmundoi_clean-6780_AXNH
-tggtcattcctcttgtagtttgccggagtcgatccattacaggcaggga
atgttgttcagttagtcctggtcctgggactgactgttgggtggatatca
acttacatatttcgggtctcgaacaaggagatgacatatgctcaacagtt
acgagactatgaatacaaggtcatggaggtaaatatcagcgaaaacatcg
acgcttctttgacatttttccgaaatgttc-tcgtctaattgaaca----
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY067_Aspera_var_clean-6780_AXNH
NY067_Aspera_var_clean-6780_AXNH
----tcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttact---------------------------------------
--------------------------------------------------
----------------*
>DL;131_Fraterna_clean-6780_AXNH
131_Fraterna_clean-6780_AXNH
-------------ttgtagtttgccggagtcgatccattacaggcaggga
atgttgttcagttagtcctggtcctgggactgacagttgggtggatatca
acttacatatttcgggtctcgaacaaggagatgacatatgctcaacagtt
acgagactatgaatacaaggtcatggaggtaaatatcagcgaaaacatcg
acgcttcttggacatttttccgaaatgttc-tcgtctaattgaacaaacc
g-------------------------------------------------
--------------------------------------------------
----------------*
>DL;A10_Melastomoides_clean-6780_AXNH
A10_Melastomoides_clean-6780_AXNH
---------------------------------------------tggga
atgttgttcagttagtcctggtcctgggactgactgttgggtggatatca
acttacatatttcgggtctcgaacaaggagatgacatatgctcaacagtt
acgagactatgaatacaaggtcatggaggtaaatatcagcgaaaacatcg
acacttctttgacatttttccgaaacgt-------ctaattgaacaaact
--------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY048_Aspera_clean-6780_AXNH
NY048_Aspera_clean-6780_AXNH
-tggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactc--------------------------------------
--------------------------------------------------
----------------*
>DL;A07_Aspera_clean-6780_AXNH
A07_Aspera_clean-6780_AXNH
gtggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcggggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
g-------------------------------------------------
--------------------------------------------------
----------------*
>DL;NY057_Aspera_asperrima_clean-6780_AXNH
NY057_Aspera_asperrima_clean-6780_AXNH
-tggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacacttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcattta-----------------------------------------
--------------------------------------------------
----------------*
>DL;NY056_Aspera_clean-6780_AXNH
NY056_Aspera_clean-6780_AXNH
-tggtcattcctcgtgtagtttgccggagtcgatccattacaggcaggga
atgtcgtacagttagtcctggtcctgggactgactgttggatggatatca
acttacatattccggttcccgaacaaggagatgacatatgctcaacaatt
acgagactacgaatacaaggtcgtggaggtaaatatcagggaaaacttcg
acgcttctttgacattgttccgaaacgtttctcatctaatcgaacaaaac
ggtcatttactctagatc--------------------------------
--------------------------------------------------
----------------*
