>DL;NY045_Aegopogon_clean-6947_ARYD
NY045_Aegopogon_clean-6947_ARYD
gataagtaaggaaaagttatgtaaaataaaataaaaatatatgtatttat
ttatttatttttgataagtatgtagtggtatagacatcaaaatgtacaat
ggtgaaggggcattataccccagagaaatcaaaaccctttacatgtatcg
atcatatggattttggattgtttaaaccctttccattagtccaaagactg
gttccgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagaatgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatgttttcaatcttatat
atatcatcaatcactttctgtttattcagattgcagcttttaatactgct
ctgagtgttcagaacttcaagttggccatgtccgttcctgctgctcttgg
tcttgatccaggtgttgcagggtcaggtataattgtccttgcttttatcc
tttttctagttaagatggctttgctcactttgtgcacggcaaatgtcttt
tggtgattgaaagttgctggaatgattttatccatttttaagtatcgaca
gttttgcatttttttggctcagtacgtgaa*
>DL;025_Nigricans_clean-6947_ARYD
025_Nigricans_clean-6947_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----cgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagaatgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatgttttcaatcttatat
atatcataaatcactttctgtttattcagattgcggcttttaatactgct
ctgagtgttcagaacttcaagttggccatgtccgttcctgctgctcttgg
tcttgatccaggtgttgcagggtcaggtataattgtccttgcttttatcc
tttttctagttaagatggctttgctc------------------------
--------------------------------------------------
------------------------------*
>DL;NY070_Aspera_clean-6947_ARYD
NY070_Aspera_clean-6947_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------taaatgcacttgtgtttga
tctactttaaaagcaacaaatgtcattccagggatgaataccgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtacct
cgccatcttcatttcttgagacatatgaagtggaacgtaagcctgtacga
aaaactttaacatgcttgaga-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------*
>DL;H40_Nigricans_clean-6947_ARYD
H40_Nigricans_clean-6947_ARYD
--------------------------------------------------
--------------------------------------------------
------------------cccagagaaatcaaaaccctttagatgtatcg
atcatatggattttggattgtttaaaccctttccattagtccaaagactg
gttccgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagaatgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatgttttcaatcttatat
atatcataaatcactttctgtttattcagattgcg---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------*
>DL;071_Nigricans_clean-6947_ARYD
071_Nigricans_clean-6947_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------aaccctttccattagtccaaagactg
gttccgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagattgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatgttttcaatcttatat
atatcataaatcactttctgtttattcagattgcggcttttaatactgct
ctgagtgttcagaacttcaagttggccatgtccgttcctgctgctcttgg
tcttgatccaggtgttgcagggtcaggtataattgtccttgcttt-----
--------------------------------------------------
--------------------------------------------------
------------------------------*
>DL;NY094_Aegopogon_clean-6947_ARYD
NY094_Aegopogon_clean-6947_ARYD
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---atatggattttggattgtttaaaccctttccattagtccaaagactg
gttccgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagaatgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatg---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------*
>DL;044_Aegopogon_clean-6947_ARYD
044_Aegopogon_clean-6947_ARYD
--------------------------------------------------
-------------------------------------caaaatgtacaat
ggtgaaggggcattataccccagagaaatcaaaaccctttagatgtatcg
atcatatggattttgaattgtttaaaccctttccattagtccaaagactg
gttccgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagaatgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatgttttcaatcttatat
atatcatcaatcactttctgtttattcagattgcggcttttaatactgct
ctgagtgttcagaacttcaagttggccatgtccgttcctgctgctcttgg
tcttgatccaggtgttgcagggtcaggtataattgtccttgcttttatcc
tttttctagttaaga-----------------------------------
--------------------------------------------------
------------------------------*
>DL;066_Aegopogon_clean-6947_ARYD
066_Aegopogon_clean-6947_ARYD
--------------------------------------------------
-----------------------------atagacatcaaaatgtacaat
ggtgaaggggcattataccccagagaaatcaaaaccctttagatgtatcg
atcatatggattttggattgtttaaaccctttccattagtccaaagactg
gttccgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagaatgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatgttttcaatcttatat
atatcatcaatcactttctgtttattcagattgcggcttttaatactgct
ctgagtgttcagaacttcaagttggccatgtccgttcctgctgctcttgg
tcttgatccaggtgttgcagggtcaggtataattgtccttgcttttatcc
tttttct-------------------------------------------
--------------------------------------------------
------------------------------*
>DL;A08_Aspera_clean-6947_ARYD
A08_Aspera_clean-6947_ARYD
-----------------------------------------tgtatttat
ttatttatttttgataagtaaacagtggtataga---caaaatgtacaat
ggtgaaggggc---atacccctgaggaatcaaaaccctttagatgtattg
atcatactgattttggactgtttaaacccctttcatgagtccaaagactg
attccgtgtttatggtatgtcttgtttatgtgaaatgcacttgtgtttga
tctactttaaaagcaacaaatgtcattccagggatgaataccgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtacct
cgccatcttcatttcttgagacatatgaagtggaacgtaagcctgtacga
aaaactttaacatgcttgagttctatttccacttgttttcaatc--atct
atatcatcaatcactttctgtttattcaggttgcggcttttaatacggct
ctgagtgttcagaacttcaagttggccatgtccgtacctgctgctcttgg
tcttgatccaggtgtcgcggggtcaggtatacttctccttgcttttatcc
tttttctagt----------------------------------------
--------------------------------------------------
------------------------------*
>DL;014_Aegopogon_clean-6947_ARYD
014_Aegopogon_clean-6947_ARYD
--------------------------------------------------
--atttatttttgataagtatgtagtggtatagacatcaaaatgtacaat
ggtgaaggggcattataccccagagaaatcaaaaccctttacatgtatcg
atcatatggattttggattgtttaaaccctttccattagtccaaagactg
gttccgtgtttatggcatgtc--gtgcatgtgaaatgcacttgtgtttga
tctacttcaaaagcaaagaatgtcattccagggatgaatactgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtactt
cgccatcttcatttcttgagacatatgaagtggaacgtaagccggtacga
aaaactttaacatacttaagttctatttccacatgttttcaatcttatat
atatcatcaatcactttctgtttattcagattgcggcttttaatactgct
ctgagtgttcagaacttcaagttggccatgtccgttcctgctgctcttgg
tcttgatccaggtgttgcagggtcaggtataattgtccttgct-------
--------------------------------------------------
--------------------------------------------------
------------------------------*
>DL;NY047_Aspera_aspera_clean-6947_ARYD
NY047_Aspera_aspera_clean-6947_ARYD
--------------------------------------------------
-----------------------------------------------aat
ggtgaaggggc---atacccctgaggaatcaaaaccctttagatgtattg
atcatactgattttggactgtttaaacccctttcatgagtccaaagactg
attccgtgtttatggtatgtcttgtttatgtgaaatgcacttgtgtttga
tctactttaaaagcaacaaatgtcattccagggatgaataccgggattca
agatgcacataatcttgcatggaaattggcatctgttttgaatggtacct
cgccatcttcatttcttgagacatatgaagtggaacgtaagcctgtacga
aaaactttaacatgcttgagttctatttccact-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------*
