>DL;A29_Angustifolia_clean-6954_IDAU
A29_Angustifolia_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------atcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatttttgtctgagttctataatcttccccta
gatgacgaagttgtatgtagact---------------------------
-----------------------------------------------tc-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY045_Aegopogon_clean-6954_IDAU
NY045_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------atcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctactcctg
gatgacgaagttatatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtag---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;094_Albescens_cf_clean-6954_IDAU
094_Albescens_cf_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------ctctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaaca-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;092_Barbigera_aff_clean-6954_IDAU
092_Barbigera_aff_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------ataatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgttgatgaactat
gactcgttctactccaagctgctggactttctggatgcttgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
acaattcggaagccttgacatatttgtccgagttctataatctccccctg
gatgacaaagttgtatgtagact---------------------------
-----------------------------------------------tca
aaactgtcctaactaggaagtagacaggagtat-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;065_Albescens_clean-6954_IDAU
065_Albescens_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------tgtttgagataatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcatgaactg
gggaacggttgccgaaggagaagtcacctccctatggaaggtctgcgaca
ataattcagaagccttgaaatttttgtccgagttctataatctccccctg
gatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggagtatcctgag-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;098_Verticillaris_clean-6954_IDAU
098_Verticillaris_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------tgattcagt
tagagaggatcggatcgactctccctgtgcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaaca-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY093_Aegopogon_clean-6954_IDAU
NY093_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------tcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataatccggaagccttgacatatttgtccgagttctataatctacccctg
gatgacg-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;025_Nigricans_clean-6954_IDAU
025_Nigricans_clean-6954_IDAU
--------------------------------------------------
----------------agaagcaggagagaggacagcctcgaatttccac
ccctacctgcctggagaatcctatctcacttgcaggtaggcaatgcttga
ttactttcttgtccttaggaacttcatcgctgagatgccgattaatgacc
tgcaaattgctaggttcttctctgcaaggaaacatggattggtggatgca
gcagttagaaatagcgagtccgataggactgcagttatcgctctccctgg
tggaattggcactctggatgaaatgttcgagatcatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcatgaactg
gggaacggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattccgaagccttgaaatttttgtccgagttctatactctccccctg
aatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggaatatcctgagcaagcaaaacg
ca------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;030_Nigricans_clean-6954_IDAU
030_Nigricans_clean-6954_IDAU
--------------------------------------------------
-------gattggtaaagaagcaggagagtggacagcctcgaatttccac
ccctacctgcctggagaatcctatctcacttgcaggtaggcaatgcttga
tttctttcttgtccttaggaacttcatcgctgagatgccgattaatgacc
tgcaaattgctaggttcttct--------aaacatggattggtggatgca
gcagttagaaatagcgagtccgataggactgcagttatcgctctccctgg
tggaattggcactctggatgaaatgttcgagatcatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcatgaactg
gggaacggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattccgaagccttgaaatttttgtccgagttctatactctccccctg
aatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggaatatcctgagcaagcaaaacg
catccacccaacatttctcttcgaatacctcccgagtattccaatccgtt
gaaagaaacaat--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;H40_Nigricans_clean-6954_IDAU
H40_Nigricans_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------cgagatcatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcatgaactg
gggaacggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattccgaagccttgaaatttttgtccgagttctatactctccccctg
aatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagta----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;071_Nigricans_clean-6954_IDAU
071_Nigricans_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------caccctgtttccttcctgttgatgaactat
gactcgttctactccaagctgctggactttctggatgattgcgttaactg
gggaacggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatttttgtctgagttctataatcttccccta
gatgacgaagttgtatgtagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggagtatcctgagcaagcaaaacg
catccacccaacatttctcttcgaatacctcccgagtattccaatccgt-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY080_Papyrifera_clean-6954_IDAU
NY080_Papyrifera_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------tcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgattgcgtgaactggggaacag-------------------------
-------------------------------------ttgccgaaggaga
agtcgcatccctatggaaggtctgtgacaataatt---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;055_Aegopogon_clean-6954_IDAU
055_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------cggaagggatcaccttgttcccttcctgttgatgaactat
gactcgttctactccaagctgctggactttctggatgattgcgttaactg
gggagcggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaac------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY094_Aegopogon_clean-6954_IDAU
NY094_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------gatctctctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaa-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;044_Aegopogon_clean-6954_IDAU
044_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------atcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagc----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;A35_Bruniana_clean-6954_IDAU
A35_Bruniana_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------ccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaac------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;111_Sp5_clean-6954_IDAU
111_Sp5_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------tccgataagactgcagttattgctttccctgg
tggaattggcactctggatgaaatttttgagatcatggcgctgattcagt
tagagaggatcggatcgactctcccagttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgctgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaacaaaaca
catccacccaacatttctcttcgtatacctcccgagtactccaatccatt
gacagaaacgattacagagacttgcctaacctggccattatcggtgtaaa
agattaactgtctcaaaatctcaactgatgtccacataagtttccgagca
ctacatcctggcaca-----------------------------------
--------------------------------------*
>DL;066_Aegopogon_clean-6954_IDAU
066_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------ctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatccggagcaaa-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;G23_Melastomoides_clean-6954_IDAU
G23_Melastomoides_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------cgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacagga---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;014_Aegopogon_clean-6954_IDAU
014_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------tgcggaagggatcaccctgttcccttcctgttgatgaactat
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagt------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;039_Verticillaris_clean-6954_IDAU
039_Verticillaris_clean-6954_IDAU
aatggatgccgcgacaaagggtgcattagatgctgggcagccggtcgccg
gactcaagattggtaaagaagcaggagagtggacagcctcgaatttccac
ccctacctgcctggagattcctatctcacttgcaggtaggcaatgcttga
ttactttcttgtccttaggaacttcatcgctgagatgccgattaatgacc
tgcaaattgccaggttcttctctgcaaggaaacatggattggtggatgca
gcagttagaaatagcgagttcgataggactgcagttatcgctctccctgg
tggaattggcactctggatgaaatgttcgagataatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcatgaactg
gggaacggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattccgaagccttgaaatttttgtccgagttctataatctccccctg
gatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggagtatcctgagcaagcaaaacg
catccacccaacatttctcttcgaatacctcccgagtattccaatccgtt
gaaagaaacaattacatagccttgcctgacccggccattatcgatgtaaa
aga-----------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;018_Barbigera_clean-6954_IDAU
018_Barbigera_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------tcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccga------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;076_Gracilis_clean-6954_IDAU
076_Gracilis_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------atcggatcgactctcccggttcccttcctgttgatgaactat
gactcgttctactccaagctgctggaatttctggatgattgcgtgaactg
gggaacggtttccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattccgaagccttgacatttttgtccgagttctataatctccccctg
gatgaggaagttgttgttagact---------------------------
-----------------------------------------------tca
aaacggtcctaagtaggaagcaggcaggactactccaagg----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;G17_Aegopogon_clean-6954_IDAU
G17_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------ttgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaa-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;42_Angustifolia_clean-6954_IDAU
42_Angustifolia_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------g
tggaattggcactctggatgaaatgttcgagataatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcatgaactg
gggaacggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattccgaagccttgaaatttttgtccgagttctatactctccccctg
gatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggagtatcctgagcaagcaaaacg
catccacccaaca-------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY079_Albescens_clean-6954_IDAU
NY079_Albescens_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------tcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataatttggaagccttgacatatttgtcagagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaag-------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;050_Aegopogon_clean-6954_IDAU
050_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------tgatcaccctgttcccttcctgttgatgaactat
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggacgccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagac-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY092_Aegopogon_clean-6954_IDAU
NY092_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----aggatcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaa--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;F41_Edmundoi_clean-6954_IDAU
F41_Edmundoi_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------gagataatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcggtctactccaagctgctggactttctggatgcttgcgtgaactg
gggaacagttaccgaaggagaagtcgcatccctatggaaggtctgtgaca
acaattcggaagccttgacatatttgtccgagttctataatctccccctg
gatgacaaagtt--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY081_Papyrus_clean-6954_IDAU
NY081_Papyrus_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------ggatcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaac------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;G35_Ramboi_clean-6954_IDAU
G35_Ramboi_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------ttgctctccctgg
tggaatcgggactctggatgaaatgtttgagatcatggccctgattcagt
tagagaggattggatcgactctcccagtgcccttcctgttgatgaactac
gacttgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgctgaaggagaagtcgcatccttatggaaggtctgcgacg
ataattccaaagccttgacatttttgtccgagttctataatctc------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;A37_Exasperata_clean-6954_IDAU
A37_Exasperata_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------atcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtcagagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcct----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;114_Sp5_clean-6954_IDAU
114_Sp5_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------atcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagca---------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;131_Fraterna_clean-6954_IDAU
131_Fraterna_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------aagggatcaccctgttcccttcctgttgatgaactat
gacccgttctactccaagctgctggactttctggatgattgcgttaactg
gggagtggttgctgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatttttgtctgagttctataatcttccccta
gatgacgaagttgtatgtagact---------------------------
-----------------------------------------------tca
aaactgccctaagtaggaagtagacagga---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;069_Nigricans_clean-6954_IDAU
069_Nigricans_clean-6954_IDAU
aatggatgccgcgacaaagggtgcattagatgccgggcagccggtcgccg
gactcaaaattggtaaagaagcaggagagtggacagcctcgaatttccac
ccctacctgcctggagaatcctatctcacttgcaggtaggcaatgcttga
ttactttcttgtccttaggaacttcatcgctgagatgccgattaatgacc
tgcaaattgctaggttcttctctgcaaggaaacatggattggtggatgca
gcagttagaaatagcgagtccgataggactgcagttatcgctctccctgg
tggaattggcactctggatgaaatgttcgagatcatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcctgctgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcatgaactg
gggaacggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattccgaagccttgaaatttttgtccgagttctatactctccccctg
aatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggaatatcctgagcaagcaaaacg
catccacccaacatttctcttcgaatacctcccgagtattccaatccgtt
gaaagaaacaattacatagccttgcctgacccggccattatcggtgtaaa
agattaacggtctcaaaatgtcaactgatattcacgaacgtttccgagca
gtacatcatggcacaactaatgtggcttcctacaattcaccatgtgcaac
ttggcaaatttccttcttttcgcttgctcatggacttg*
>DL;011_Papyrus_clean-6954_IDAU
011_Papyrus_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------tgcggaagggatcaccctgttcccttcctgttgatgaactat
gactcgttctactccaagctgctggactttctggatgattgcgttaactg
gggagcggttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatttttgtctgagttctataatcttccccta
gataacgaagttgtatgtagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacagga---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;A10_Melastomoides_clean-6954_IDAU
A10_Melastomoides_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------attcagt
tagagaggatcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagcaaa-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;003_Aegopogon_clean-6954_IDAU
003_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------ggatcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tc-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;073_Aegopogon_clean-6954_IDAU
073_Aegopogon_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----gaggatcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggcagccttgacatatttgtcagagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaa-------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;113_Sp5_clean-6954_IDAU
113_Sp5_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------aaacatggattggtggatgca
gcagttagaaatagcgagtccgataggactgcagtcatcgctctccctgg
tggaattggcactctggatgaaatgtttgagataatggccttgattcagt
tagagaggatcggatcgactctccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgaaatttttgtccgagttctataatctccccctg
gatgacaaagttgttattagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacgggagtatcctgagcaagaaaaacg
catccacccaacatttctcttcgaatacctcccgagtattccaatccgtt
gaaagaaacaattacatagccttgcctgacccggccattatcggtgtaaa
agattaacggtctcaaaatgtcaactgatattcacaaacgtttccg----
--------------------------------------------------
--------------------------------------*
>DL;G21_Papyrus_clean-6954_IDAU
G21_Papyrus_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------ccctgttcccttcgtgttgatgaactac
gactcgttctactccaagctgctggactttctggatgattgcgtgaactg
gggaacagttgccgaaggagaagtcgcatccctatggaaggtctgtgaca
ataattcggaagccttgacatatttgtccgagttctataatctacccctg
gatgacgaagttgtatgcagact---------------------------
-----------------------------------------------tca
aaactgtcctaagtaggaagtagacaggagtatcccgagc----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
>DL;NY050_Fraterna_clean-6954_IDAU
NY050_Fraterna_clean-6954_IDAU
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------tcttgtttattgccgcgtgcggttctat
gttacgagattgttcttatctcaccaggtggcaaaacttttggactgcac
aacatggtcgggcgctggt--cctggcctaatggatgctgcgacaaaggg
tgcattagatgccgggcagccggtcgccggactaaaga------ttggta
aagaagcaggagagtggacagcctcaaatttccacccctacctgcctgca
gaatcctatctcacttgcaggtagacggttttgcttgattactttcttgt
ccttaggaacttcatcgttgagatgccgattaatgacctgcaaattgcca
ggttcttctctgccaggaaacatggattggtagatgcagc----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------*
