>DL;A31_Aspera_clean-6977_DZLN
A31_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------tgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgtcaaatggcaactcgcacatgttccctgta
attatctaaatacatatatcaacttaaccagcaaagattaaaccattttg
tgggataaaaatttgaaaag---gtggcatataatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatggt
tgattcctt----tcttatttggataattcc--tttgtacttctcccatt
tt--atcaaataatttacaagtaatacttttatggtagcctgcatcttat
aatttttc-------------gt---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY055_Bipenicellata_clean-6977_DZLN
NY055_Bipenicellata_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--ggataaaaatttgaaaagaaaatggcatatgatgagctttaatttatt
agtattagagactc--tgtaacttctagttggcctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgcactgttctcgtctgcactagt------cttaagatcaaatgat
tgattgctt----tcttattgggattattcctttttgtaattctcctatt
tttctttgaataatttacaaataatacttttatggttgcctgcat-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;A18_Pogonanthera_2_clean-6977_DZLN
A18_Pogonanthera_2_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------attgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttggttctttaaggactagacaggtctttcttcatggatgcca
ttagat--------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;116_Sp6_clean-6977_DZLN
116_Sp6_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------ttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttggttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttg------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;092_Barbigera_aff_clean-6977_DZLN
092_Barbigera_aff_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------cagggcaga
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagcgatccatggttaggtgttaagtggaaactcccacttgttccctgta
attaattatctatgtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agttgaagagactctttgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
t-------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;065_Albescens_clean-6977_DZLN
065_Albescens_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------tatcc
acgtgatccatggttaggtgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatgtaatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttggttctttaaggactaaacaggtctttcttcatggatgcca
ttcttgcactgttgtcgtgtgcact-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;G14_Albescens_clean-6977_DZLN
G14_Albescens_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------tacatgtatcaaattaacaagcaaagattaaaccattttg
tgggataaaaatttgaaaggacaatggaatataataagctttaattaatt
agtattagagactctatgtatcttctagttgatctcttacttgggtgaga
cttacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatcaattgaaagtatg
tctaaaattgtagctttaaggactcgtggatgctgttagt----------
-tgctgcactgttgtcgtgtgcactagt------attaacatcaattgat
tgattcc-------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY093_Aegopogon_clean-6977_DZLN
NY093_Aegopogon_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------t
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcccgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatattgtttctttaaggactagacaggtctttctta----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY040_Bipenicellata_clean-6977_DZLN
NY040_Bipenicellata_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------tctgactc--tgtaacttctagttggcctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgcactgttctcgtctgcactagt------ct--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;080_Sp8_clean-6977_DZLN
080_Sp8_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------ggttgtcagagcagaacataaccagcagggcaga
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
aatttaagagactctctgtaacttctaattgatctcgtacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttct----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;025_Nigricans_clean-6977_DZLN
025_Nigricans_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------agctttaattgatt
agtttaagagactctcggtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaa-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY059_Llanorum_clean-6977_DZLN
NY059_Llanorum_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------tatctaagtaca---------------------aaaacattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
aatttaagaaactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tgtaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttctagcactga--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;030_Nigricans_clean-6977_DZLN
030_Nigricans_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------cccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctcggtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatg---
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;126_Bruniana_clean-6977_DZLN
126_Bruniana_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------taattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tataatcttgtttctttaaggactagacgggtctttcttcatggatgccg
ttcttgcactgttgtcgtgtgcactagt------attgagatcaaatgat
tgattcctt----t------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;H40_Nigricans_clean-6977_DZLN
H40_Nigricans_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------ttaattgatt
agtttaagagactctcggtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gttgaataatttacaaataatacttttatggtagcctgcaccttat
gatttttcagtaa------------tacaagttgtaatatcatccagtaa
gcctccccttggtacacacatgttgcagagatatttgttgaggagaagtc
tttcacgtgtatgtgcacgatggatgatgaggtggccttgatagagtatg
tacgacaggccattttgacttttggttgctttgtcatcaatgtttatatt
taatctcttattcatgca*
>DL;NY090_Barbigera_clean-6977_DZLN
NY090_Barbigera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------taattgatt
aatttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtacg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatg---
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;110_Sp6_clean-6977_DZLN
110_Sp6_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------tactgttataggttgtcagagcagaacataaccagcagggcaga
ggatctgccatgattcaggtgcttgcaactgtaaccatag---gttattc
aagtgatccgcggttaggtgttaaatggcaactcccacgtgtcccctgta
attatctaaataaatgtatcaaattaac-----------aaatcattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaatcgatt
agttttagagactctatgtaccttctaattgatctcttacttgggctaga
ctgacttcct------tgcctgcaggtggaacttcgcgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tataatcttgtttctttaaggactagacgggtctttcttcatggatgccg
ttcttgcactgttgtcgtgtgcactagt------attaagatcaaatgat
ttattcctt----ttgtaattctcctatttt-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;G08_Albescens_clean-6977_DZLN
G08_Albescens_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------actgttataggttgtcagagcagaacataaccagcagggcaga
ggatctgcaatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatgtaatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtca---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY088_Barbigera_clean-6977_DZLN
NY088_Barbigera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------ccgatc
tatttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttctagcactgttgtcat--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY011_Catharinae_2_clean-6977_DZLN
NY011_Catharinae_2_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------tccgatctcttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgcactgttgtcgtgtgcactagt------attaagatcaaatgat
tgattgctt----tcttat-------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY051_Llanorum_clean-6977_DZLN
NY051_Llanorum_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------ttc
aagtgatccatggttaggtgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaacattttg
tgagataaaaatttgaaaggacaatggcatataatgagctttaattgatt
aatttaagaaactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tgtaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttctagcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gtcgaataatttacaaataatacttgtatggtagcctgcaccttat
gatttttcagta--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY033_Spruceana_clean-6977_DZLN
NY033_Spruceana_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------ttaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgtaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgtactgttgtcgtgtgcactaat------attaagatcaagtga-
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY031_Spruceana_clean-6977_DZLN
NY031_Spruceana_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------aatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgcaggtggagcttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatgat
tgattcctt----tctaattgggataattcc--tttgtacttctcccatt
tt--atcaaataatttacaagtaatacttttatggtagcctgc-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY054_Bipenicellata_clean-6977_DZLN
NY054_Bipenicellata_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------attaacaagcaaagattacaccattttg
tgggataaaaatttgaaaagaaaatggcatatgatgagctttaatttatt
agtattagagactc--tgtaacttctagttggcctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgcactgttctcgtctgcactagt------cttaagatcaaatgat
tgattgctt----tcttattgggattattcctttttgtaattctcctatt
tttctttgaataatttacaaataatacttttatggttgcctgcatcttat
gatttttc-------------gtaacacaagttgtcgtatcatccgataa
gccttagcttggtacacacatgttgcagagatatttgttg----------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;079_Sp8_clean-6977_DZLN
079_Sp8_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-gggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
aatttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttctagcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gtcgaataatttacaaataatact----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;G05_Aspera_clean-6977_DZLN
G05_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
-----------------tgttgtggactaatgaagattgattttctgaga
ttttccagaacgtctttacgaggttagctttgtttttggctttcctcg-c
ctttttgtttttttcatgtggaatcttgac-atggagttttctgaagttt
tcattttactgttacaggttgtcaaagcagaacataaccagcagggcagg
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgtcaaatggcaactcgcacatgttccctgta
attatctaaatacatatatcaacttaaccagcaaagatcaaaccattttg
tgggataaaaatttgaaaag---gtggcatataatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgccagcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatggt
tgattcctt----tcttattgggataattcc--tttgtacttctcccatt
tt--atcaaataatttac--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY052_Striphnocalyx_clean-6977_DZLN
NY052_Striphnocalyx_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------------c
tttttgtttttcttcatgtggaatcttgac-atggagttttctgaagttc
tcattttactcttataggttgttagagcagaacataaccagcagggcaga
ggatctgccatgattcaggtgcttgcaactataagcatag---gttattc
aagtgaaccatggttaggtgttgagtggcacctcgcacatgttccctgta
attttctaaatacatgtatcaaattaacaagcaaagattacaccattttg
tgggataaaattttgaaaagacaatggcatatgatgagctttaatttatt
agtattagagactc--tgtaacttctagttgatctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgcactgttgtcgtgtgcactagt------attaagatcaaatgat
tgattgattgatttcttattgggattattcc-ttttgtaattctcctatt
tttcttcgaataatttacaaataatatttttatggtagcctgcatcttat
gatttttc-------------gtaacacaagttg----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;A35_Bruniana_clean-6977_DZLN
A35_Bruniana_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------atgagctttaatcgatt
agttttagagactctatgtactttctaattgatctcttacttgggctaga
ctgacttcct------tgcctgcaggtggaacttcgcgatgtggagagcg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tataatctggtttctttaaggactagacgggtctttcttcatggaa----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY085_Verticillaris_clean-6977_DZLN
NY085_Verticillaris_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------tttctgaagttc
tcattttactgttataggttgtcagagcagaacataaccagcagggcaga
ggatctgccatgattcaggtgcttgcaactataaccataggttgttattc
aagtgatccatggttaggtgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gcaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--atcgaataatttacaaataatacttttatggtagcctgcaccttat
gatttttcagtaa------------tacaagttgtaatatcatccagtaa
gcctccccttggtacacacatgttgcagagatatttgttgaggagaagtc
tttcacgtgtatgtgcacgatggatgatgaggtggccttgatagagtat-
--------------------------------------------------
------------------*
>DL;A08_Aspera_clean-6977_DZLN
A08_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------ttgtcaaagcagaacataaccagcagggcagg
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgtcaaatggcaactcgcacatgttccctgta
attatctaaatacatatatcaacttaaccagcaaagatcaaaccattttg
tgggataaaaatttgaaaag---gtggcatataatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgccagcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatggt
tgattcctt----tcttattgggataattcc--tttgta-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY046_Aspera_clean-6977_DZLN
NY046_Aspera_clean-6977_DZLN
------------------------------------------------tg
gtggaaaggaaaggtagtagcatcatcaatctatttctcaactagattgt
cgtcactccaaatgtactgttgtggactaatgaagattgattttctgaga
ttttccagaacgtctttacgaggttagctttgtttttggctttcctcg-c
ctttttgtttttttcatgtggaatattgac-atggagttttctgaagttt
tcattttactgttacaggttgtcaaagcagaacataaccagcagggcagg
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgttacatgacaactcacacatgttccctgta
attatctaaatacatatatcaacttaaccagcaaagattaaaccattttg
tgggataaaaatttgaaaag---atggcatataatgagctctaatttatt
tgtgttagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatggt
tgattcctt----tcttattgggataattcc--tttgtacttctcccatt
tt--atcaaataatttacaagtaatacttttatggtagcctgcatcttat
aatttttc-------------gtaacacaagttttagtatcttgcgataa
tcctctccttggtacacacatgtttcagagatatttgttgaggagaagtc
tttcacgtgtatgtacacgatggatgatgaggtggccttgatagagtatg
ca------------------------------------------------
------------------*
>DL;G23_Melastomoides_clean-6977_DZLN
G23_Melastomoides_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------aagttc
tcattttactgttataggttgtcagagcagaacataaccagcagggcaga
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggcgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttggttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcgtgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgg----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;085_Aegopogon_aff_clean-6977_DZLN
085_Aegopogon_aff_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------gatt
agttttagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gtcgaat---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;039_Verticillaris_clean-6977_DZLN
039_Verticillaris_clean-6977_DZLN
atgggcggaatgcaagtgctgttgaatttcaggttagaccagggaacgtg
gtggaaaggaaaggtagcatcacc----aattatttctcaactagattgt
cgtcactccaaatgtactgttgtggactaatgaagattgattttctgaga
tttttcaggacgtctttatgaggttagctttgattttggctttcctcg--
----ccttttttttcatgtggaatcttgacaatggagttttctgaagttc
tcattttactgttataggttgtcagagcagaacataaccagcagggcaga
ggatctgcaatgattcaggtggttgcaactataaccatag---gttattc
aagtgatccatggttaggtgttaagtggaaaatcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagg--ctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagcg
gcaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactggt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gttgaataatttacaaataatacttttatggtagcctgcaccttat
gatttttcagtaatacaagttgtaatacaagttgtaatatcatccagtaa
gcctccccttggtacacacatgttgcagagatatttgttgaggagaagtc
tttcacgtgtatgtgcacgatggatgatgaggtggccttgatagagtatg
tacgacaggccattttgaattttggttgcttt------------------
------------------*
>DL;NY002_Dissitiflora_clean-6977_DZLN
NY002_Dissitiflora_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------tgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaagaactagatgggtctgccgt-----------
-tcttgcactgttgtcgtgtgcac---------------gatcaaatgat
tgattgctt----tcttattgggataa-----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY042_Bipenicellata_clean-6977_DZLN
NY042_Bipenicellata_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------atttatt
agtattagagactc--tgtaacttctagttggcctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacgggtctttcttcatggatgcc-
-attcttactgttgacatgtgcactagt------attaagatcaaatgat
tgattcct------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY086_Barbigera_clean-6977_DZLN
NY086_Barbigera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------ttgcaactataaccatag---gttattc
aagtgatccatggttaggtgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
aatttaagagactctctgtaacttctaattgatctcgtacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttctagcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggatt------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY068_Aspera_clean-6977_DZLN
NY068_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------tatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaa-----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY023_Edmundoi_clean-6977_DZLN
NY023_Edmundoi_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------tctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagcg
gcaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tctta--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;107_Sp7_clean-6977_DZLN
107_Sp7_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------tgatt
aatttaagagactctctgtaacttctaattgatctcttactt-gatgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggaccagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactaga------attaagatcaa-----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY053_Fraterna_clean-6977_DZLN
NY053_Fraterna_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------taatttatt
agtattagagactc--tgtaacttctagttgatctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaagaactagatgggtctgccgt-----------
-tcttgcactgttgtcgtgtgcactagt------attaagatcaaatgat
tgattgctt----tcttattgggattattcc-ttttgtaattctcctatt
tttcttcgaataatttacaaataatacttttatggtagcctgcatcttat
gatttttc-------------g----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;A26_Rosanae_2_clean-6977_DZLN
A26_Rosanae_2_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------tataatgagctttaattgatt
agtttaagagactctctgcaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
tta-----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY079_Albescens_clean-6977_DZLN
NY079_Albescens_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------gactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttga-----------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;F41_Edmundoi_clean-6977_DZLN
F41_Edmundoi_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----ttaccgttataggttgtcagagcagaacataaccagcagggcaga
ggatctgccatgattcaggtgcttgcaactataaccataggtcgttattc
aagtgatccatggttaggtgttaagtggaaactcccacatgttccatgta
attaattatctaagtaca---------------------aaacgattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagataggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactaga------attaagatcaaatgat
tgattcctg----tcttatcgggattattcc--ttttgtaattcctattt
tc--gtcgaataatttacaaataatacttttatggtagcctgcaccttat
gatttttcaataa------------tacaagttgtaatatcatccagtaa
gcctccccttggtacaca--------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY081_Papyrus_clean-6977_DZLN
NY081_Papyrus_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--ggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattggg---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY016_Kunhardtii_clean-6977_DZLN
NY016_Kunhardtii_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------gcatatcatgagctttaatttatt
agtattagagactc--tgtaacttctagttgatctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgcactgttgtcgtgtgcactagt------attaagatcaaatgat
tgattgctt----t------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;G35_Ramboi_clean-6977_DZLN
G35_Ramboi_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------taattaatt
agtattagagactctatgtatcttctaggtgatctcttacttgggtcaga
cttacttcctttgacatgcctgcaggtggaacttcgcgatgtggagagtg
ataacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgcttctttaaggacttgacgggtctttcttcatatatgttg
ttag----------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;A30_Aspera_clean-6977_DZLN
A30_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------ttccctgta
attatctaaatacatatatcaacttaaccagcaaagattaaaccattttg
tgggataaaaatttgaaaag---gtggcatataatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagataaaatgat
tgattcct------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY067_Aspera_var_clean-6977_DZLN
NY067_Aspera_var_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------cttaaccagcaaagatcaaaccattttg
tgggataaaaatttgaaaag---gtggcatataatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgccagcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatggt
tgattcctt----tcttattgggataattcc--tttgtacttctcccatt
tt--atcaaat---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;114_Sp5_clean-6977_DZLN
114_Sp5_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------atgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattg-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;131_Fraterna_clean-6977_DZLN
131_Fraterna_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------catgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatatgatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggatt------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;G09_Verticillaris_clean-6977_DZLN
G09_Verticillaris_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------------------ccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gttgaataatttaca-------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;069_Nigricans_clean-6977_DZLN
069_Nigricans_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-ttaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctcggtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gttgaataattta---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY089_Barbigera_clean-6977_DZLN
NY089_Barbigera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--ggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
aatttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttctttatggatgcca
ttctagcactgttgtcatgt------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;011_Papyrus_clean-6977_DZLN
011_Papyrus_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-gtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgt------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;A10_Melastomoides_clean-6977_DZLN
A10_Melastomoides_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------taatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatcacttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttggttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcgtgtgcactagt------attaagatcaaa----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY048_Aspera_clean-6977_DZLN
NY048_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------aactcgcacatgttccctgta
attatctaaatacatagatcaacttaaccagcaaagatcaaaccattttg
tgggataaaaatttgaaaag---gtggcatataatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgccagcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatggt
tgattcctt----tcttattgggataattcc--tttgtacttctcccatt
tt--atcaaataatttacaagtaatacttttatggtagcctgcatcttat
aatttttc-------------gtaacacaagttttagtatcttgcgataa
tcctctccttggtacacacatgtttcagagatatttgttgaggagaagtc
tttcacgtgtatgtacacgatggatgatgaggtggccttgatagagtatg
cactactggccattctgaattttggttgctttgtcctcgatgttta----
------------------*
>DL;A07_Aspera_clean-6977_DZLN
A07_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------tccg
atctttagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcaagatc----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY057_Aspera_asperrima_clean-6977_DZLN
NY057_Aspera_asperrima_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------agctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactag-----------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;G21_Papyrus_clean-6977_DZLN
G21_Papyrus_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------ttctgaagttc
tcattttactgttataggttgtcagagcagaacataaccagcagggcaga
ggatctgcaatgattcaggtggttgcaactataaccatag---gttattc
aagtgatccatggttaggtgttaagtggaaactcccacatgttccctgta
attaattatctaagtaca---------------------aaaccattttg
tgggataaaaatttgaaaggacaatggcatataatgagctttaattgatt
agtttaagagactctctgtaacttctaattgatctcttacttgggtgagg
ctgacttcgt------tgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagacaggtctttcttcatggatgcca
ttcttgcactgttgtcatgtgcactagt------attaagatcaaatgat
tgattcctg----tcttattgggattattcc--ttttgtaattcctattt
tc--gttgaataatttacaaataat-------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY056_Aspera_clean-6977_DZLN
NY056_Aspera_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
---------------------------------------------tgaga
ttttccagaacgtctttacgaggttagctttgtttttggctttcctcg-c
ctttttgtttttttcatgtggaatcttgac-atggaggtttctgaagttt
tcattttactgttacaggttgtcaaagcagaacataaccagcagggcagg
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgtcaaatggcaactcgcacatgttccctgta
attatctaaatacatatatcaacttaaccagcaaagatcaaaccattttg
tgggataaaaatttgaaaag---gtggcatataatgagctctaatttatt
tgtattagagactctatgtaacttctagttgatatcttacttgagtgaga
ctgacttcctttgtcatgccagcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctattgaaagtatg
tctaatcttgtttctttaaggactagactggtctgacgt-----------
-tcttgcactgttcttgtgtgcactagcactagtattaagatcaaatggt
tgattcctt----tcttattgggataattcc--tttgtacttctcccatt
tt--atcaaataatttacaagtaatacttttatggtagcctgcatcttat
aatttttc-------------gtaacacaagttttagtatcttgcgataa
tc------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
>DL;NY050_Fraterna_clean-6977_DZLN
NY050_Fraterna_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------atgaggttagctttgtttttggctttcctcgtc
tttttgtttttcttcatgtggaatcttgac-atggagttttctgaagttc
tcattttactcttataggttgttagagcagaacataaccagcagggcaga
ggatctgccatgattcaggtgcttgcaactataaccatag---gttattc
aagtgatccatggttaggtgttaagtggcaactcgcacatgttccctgta
attttctaaatacatgtatcaaattaacaagcaaagattacaccattttg
tgggataaaaatttgaaaagacaatggcatatgatgagctttaatttatt
agtattagagactc--tgtaacttctagttgatctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaagaactagatgggtctgccgt-----------
-tcttgcactgttgtcgtgtgcactagt------attaagatcaaatgat
tgattgctt----tcttattgggattattcc-ttttgtaattctcctatt
tttcttcgaataatttacaaataatacttttatggtagcctgcatcttat
gatttttc-------------gtaacacaagttgtcgtatcatccgataa
gcctcaccttggtacacacatgttgcagagatatttgtcgaggagaagtc
tttcacgtgtatgtgcacaatggatgatgaggtggccttgatagagtatg
taccacgggccactttgaattttggttactt-------------------
------------------*
>DL;NY010_Catharinae_clean-6977_DZLN
NY010_Catharinae_clean-6977_DZLN
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------ccgat--cttaacttctagttgatctcttacttgggtgaga
ctgacttcctttgacatgcctgcaggtggaacttcgtgatgtggagagtg
gtaacaaagttaatgcacggtttaatacagacgaatctgttgaaagtatg
tctaatcttgtttctttaaggactagatgggtctgccgt-----------
-tcttgcaca----------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------*
