>DL;A29_Angustifolia_clean-7602_VMNH
A29_Angustifolia_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------aggcccgtcttggcgact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatagttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagtt---------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;A18_Pogonanthera_2_clean-7602_VMNH
A18_Pogonanthera_2_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------tg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttggga---
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;116_Sp6_clean-7602_VMNH
116_Sp6_clean-7602_VMNH
--------------------------------------------------
-----gaacttcatcttgtgggaaagggagaagtaacaaggagaatcatt
catgagcgaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----ccacggccaatcccttcgagaaggcccggcttggcgact
ctgtcgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaggctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcggtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacggactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
tacctgctcacgacggcctttgggattcagccatggctacctctaaaagt
ctgctggctcgtcttgccgttgagcat---------------------*
>DL;094_Albescens_cf_clean-7602_VMNH
094_Albescens_cf_clean-7602_VMNH
--------------------------------------------------
---aggaacttcatcttgtgggaaagggagaagtaagaaggagaatcatc
catgagcgaagtggcggagagggagacactggtggaagccgcggttcgag
tgctga-----acacggccgatcccttcgagaaggcccagcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgcttatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggatataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatcctt-----------
--------------------------------------------------
------------------------------------------------*
>DL;065_Albescens_clean-7602_VMNH
065_Albescens_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---ctcgggtgg----------------acgttccagtacccgatagccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgctatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatctgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcaactaggttgcaagagctgggatcctt-----------
--------------------------------------------------
------------------------------------------------*
>DL;098_Verticillaris_clean-7602_VMNH
098_Verticillaris_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
-----------------------------------------cggttcgag
tgctga-----acacggccgatcccttcgagaaggcccagcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
a---tcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgcttatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacggactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
tacctgctcacgatggcctttgggattcagccatggctacctctaaaagt
ctgctggctcgtcttgccgttgagcactgtgtgcatgaggtatgccat*
>DL;NY093_Aegopogon_clean-7602_VMNH
NY093_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tcgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcaga------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;080_Sp8_clean-7602_VMNH
080_Sp8_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------ttccagtacctgatcgccc
aacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagcgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgttattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatccatgccaagg
gagttct-------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;025_Nigricans_clean-7602_VMNH
025_Nigricans_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---tga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aactcgtggctcgatggatccatccctcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtttg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;030_Nigricans_clean-7602_VMNH
030_Nigricans_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
---------------------------actggtggaagccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----acctcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtttggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgatttcatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactt---------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;126_Bruniana_clean-7602_VMNH
126_Bruniana_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----gct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagcaagctacgtc-----tgcaagttcggca
gctgttcgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctg---------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;H40_Nigricans_clean-7602_VMNH
H40_Nigricans_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
-----------------------------------------cggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----acctcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtttggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgatttcatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaag------------------------
--------------------------------------------------
------------------------------------------------*
>DL;100_Sp9_clean-7602_VMNH
100_Sp9_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------gggtgg----------------acgttccagtacctgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcatacggagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtct--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;071_Nigricans_clean-7602_VMNH
071_Nigricans_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------accttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgat----gtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagca----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;NY080_Papyrifera_clean-7602_VMNH
NY080_Papyrifera_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------tgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtttggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtt--------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;110_Sp6_clean-7602_VMNH
110_Sp6_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------tg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcggtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccatgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacggactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
tacctgctcacgacggcctttgggattcagccatggctacctctaaaagt
ctgcttgctcgtcttgccgttgag------------------------*
>DL;G08_Albescens_clean-7602_VMNH
G08_Albescens_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------t-----aattcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgctatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttgtccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctc-------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;NY088_Barbigera_clean-7602_VMNH
NY088_Barbigera_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------tccacgcc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcatacagagagttgggctat
cgacttatcctgggtaaaacctc---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;055_Aegopogon_clean-7602_VMNH
055_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------tgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgattgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtg------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;090_Aegopogon_aff_clean-7602_VMNH
090_Aegopogon_aff_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------tgtaagtaagctacgtc-----tgcaagttcggca
gccgtttgacgaaatgcctgagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttgtcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgt-------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;127_Johnwurdackiana_clean-7602_VMNH
127_Johnwurdackiana_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----gct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggc---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;102_Sp7_clean-7602_VMNH
102_Sp7_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
-------gaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcaact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctatgtctgcaatgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgggatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagcttgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgcgtttggccgtgattttctccatgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagattttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcaactaggttgcaagagctgggatccttctatggagctt
tacctgctcatgacggcctttgggattcagccatggctacctctaaaagt
ctgctggctcgtcttgccgttgatcactgtgtgcatgaggtacgcc--*
>DL;G02_Johnwurdackiana_clean-7602_VMNH
G02_Johnwurdackiana_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------ggcccggctttgcgact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tacaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatcct------------
--------------------------------------------------
------------------------------------------------*
>DL;044_Aegopogon_clean-7602_VMNH
044_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------------------------------------ccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgattgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aata--------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;NY082_Verticillaris_clean-7602_VMNH
NY082_Verticillaris_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------ttccgatctgtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtgg-----------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;A35_Bruniana_clean-7602_VMNH
A35_Bruniana_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--cctcgggtgg----------------acgtttcagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaaccttagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttctctgcgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagacttt--------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;111_Sp5_clean-7602_VMNH
111_Sp5_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------aattcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgcttatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgttaatatgctgttgtgtttggcc---------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;066_Aegopogon_clean-7602_VMNH
066_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------gagaaggcccggcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgatttcatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgacta---------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;G23_Melastomoides_clean-7602_VMNH
G23_Melastomoides_clean-7602_VMNH
-aatctcgattcgtcagaatacatacaagctttgaggattatagactgag
gcaaggaacttcatcttgtgggaaagggagacgtaacaaggagaatcatt
catgagcgcagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacggccaatcccttcgagaaggcccggcttggcgact
ctgtcgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcggtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacgtaattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacggactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
tacctgctcacgacggcctttgggattcagccatggctacctctaaaagt
ctgctggctcgtcttgccgttga-------------------------*
>DL;085_Aegopogon_aff_clean-7602_VMNH
085_Aegopogon_aff_clean-7602_VMNH
--------------------------------------------------
---------ttcatcttgtgggaaagggagaagtaataaggagaatcatc
catgagcgaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttgtcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggca--------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;014_Aegopogon_clean-7602_VMNH
014_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-gctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttctt--cagactttgtgaaggtggctcaagatgaaggtagac----
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;104_Sp6_clean-7602_VMNH
104_Sp6_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---aaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcggtgtggtctggatggttgt----
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;039_Verticillaris_clean-7602_VMNH
039_Verticillaris_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--tgagcgaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
atccccgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgagctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctttgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
tacctgctcacgacggcctttgggattcagccatggctacctct------
------------------------------------------------*
>DL;061_Angustifolia_clean-7602_VMNH
061_Angustifolia_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------gccc
cacaaggcttgcttatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgctatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttgtccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcaactaggttgcaag------------------------
--------------------------------------------------
------------------------------------------------*
>DL;NY086_Barbigera_clean-7602_VMNH
NY086_Barbigera_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------atgttccagtacccgatcgccc
gacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gttgttcgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgaag
agcaggcaggcaattgtgcacagccttgcgcatactgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
gagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgtaggacataattgctcg----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;NY078_Angustifolia_clean-7602_VMNH
NY078_Angustifolia_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------------------c-----tgcaagttcggca
gctgttcgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgaag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
gagttgt-aatatgctgt--------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;107_Sp7_clean-7602_VMNH
107_Sp7_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------cgtgaaggcccggcttggcaact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctatgtctgcaatgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgggatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagcttgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
t-----------tgctgttgcgtttggccgtgattttctccatgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagattttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcaactaggttgcaagagatgggatccttctatggagctt
tacctgctcatgacggcc--tgggattcagcc------------------
------------------------------------------------*
>DL;NY077_Angustifolia_clean-7602_VMNH
NY077_Angustifolia_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------tatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgagtaaaacc-----------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;G17_Aegopogon_clean-7602_VMNH
G17_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------tggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccaagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctcgcaactaggttgcaagagct--------------------
--------------------------------------------------
------------------------------------------------*
>DL;42_Angustifolia_clean-7602_VMNH
42_Angustifolia_clean-7602_VMNH
taatctcgattcgtcagaatacatacaggatttgaggattatagactgag
gcaaggaacttcatcttgtgggaaagggagaagtaataaggagaatcatc
catgagcgaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatcc-------------
--------------------------------------------------
------------------------------------------------*
>DL;NY079_Albescens_clean-7602_VMNH
NY079_Albescens_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------ccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtc---------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;050_Aegopogon_clean-7602_VMNH
050_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
-------------------------------------gccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----acctcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgattgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aat---------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;F41_Edmundoi_clean-7602_VMNH
F41_Edmundoi_clean-7602_VMNH
--------------------------------------------------
------------------------------------caaggagaatcgtc
catgagcgaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacgtccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgaag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttctccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatccat-------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;NY081_Papyrus_clean-7602_VMNH
NY081_Papyrus_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------gtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacact-
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;A37_Exasperata_clean-7602_VMNH
A37_Exasperata_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------gccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgattgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggat----------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;A01_Aegopogon_clean-7602_VMNH
A01_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------ccgatctgtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggagatcggaa---------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;114_Sp5_clean-7602_VMNH
114_Sp5_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------cgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgcttatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgttaatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggatataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggc--------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;109_Sp9_clean-7602_VMNH
109_Sp9_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------gact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgatggatccatcactcgaccttatgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctaagtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgaag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagc------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;131_Fraterna_clean-7602_VMNH
131_Fraterna_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
----------------------------gctgcaaaaggtgcgtcctggt
gattgacagctgcacagtccctgacagaacgacaaccctactcaccatct
atattacttgacgaccgcgtgcacttgcgtgtcgacca-tcgaccttatg
atcctcgggcag----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctttttgacgaaatgcttaaaaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagct-ggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgttgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtatacactt
cacgcttctggcaactaggttgcaagagctgggatcct------------
--------------------------------------------------
------------------------------------------------*
>DL;G09_Verticillaris_clean-7602_VMNH
G09_Verticillaris_clean-7602_VMNH
---------------------------------------tatagactgag
gcaaggaacttcatcttgtgggtaagggagaagtaataaggagaatcatc
cacgagcgaagtggcggagagggagacactggtggaagccgcggttcgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
atcctctggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgttaatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactc
cacgcttctggcgactaggttgc---------------------------
--------------------------------------------------
------------------------------------------------*
>DL;069_Nigricans_clean-7602_VMNH
069_Nigricans_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------cgact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagtagttaatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgcaggtggctcaagatgaaggta-------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;NY089_Barbigera_clean-7602_VMNH
NY089_Barbigera_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
---------------------------------------------ttatg
atcctcgggtgg----------------acgttccagtacctgatcgccc
cacaaggcttgctgatgtaagtaagccacgcc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcatacagagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatccatgccaa--
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;011_Papyrus_clean-7602_VMNH
011_Papyrus_clean-7602_VMNH
--------------------------------------------------
------------------tgggaaagggagaagtaataaggagaatcatc
catgagcgaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aactcgtggctcgatggatccatcactctaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtgatctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatcagtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
tacctgctcacgacggcctttgggattcagc-------------------
------------------------------------------------*
>DL;A10_Melastomoides_clean-7602_VMNH
A10_Melastomoides_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
----------------------------------------------cgag
tgctga-----acacggccaatcccttcgagaaggcccggcttggcgact
ctgtcgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcggtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacggactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
ta------------------------------------------------
------------------------------------------------*
>DL;003_Aegopogon_clean-7602_VMNH
003_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------cgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttgtcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgatttcatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaag--------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;073_Aegopogon_clean-7602_VMNH
073_Aegopogon_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
----------------------------------------------gccc
cacaaggcttgctgatgtaagtatgctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctcgcaactaggttgcaagagctg-------------------
--------------------------------------------------
------------------------------------------------*
>DL;113_Sp5_clean-7602_VMNH
113_Sp5_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-------------------gatcccttcgagaaggcccggcttggcgact
ctgttgct-----aattcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaaaaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtgtggtctggatggttgtcgga
tagttgttaatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctgggatccttctatggagctt
tacctgctcacgacggc---------------------------------
------------------------------------------------*
>DL;G21_Papyrus_clean-7602_VMNH
G21_Papyrus_clean-7602_VMNH
--------------------------------------------------
------------------------------------------------tc
catgagcgaagtggcggagagggagacactggtggaagccgcggtccgag
tgctga-----acacggccgatcccttcgagaaggcccggcttggcgact
ctgttgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcgatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaacctcagcagtttggtctggatggttgtcgga
tagttgt-aatatgctgttgtgtttggccgtgattttatccgtgggactg
ctctgcaggacataattgctcggtttggcaag------------------
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
------------------------------------------------*
>DL;052a_Melastomoides_clean-7602_VMNH
052a_Melastomoides_clean-7602_VMNH
--------------------------------------------------
--------------------------------------------------
--------------------------------------------------
-----------------ccaatcccttcgagaaggcccggcttggcgact
ctgtcgct-----aactcgtggctcgatggatccatcactcgaccttatg
atcctcgggtgg----------------acgttccagtacccgatcgccc
cacaaggcttgctgatgtaagtaagctacgtc-----tgcaagttcggca
gctgtttgacgaaatgcctaagaaaatttctgcaatcgtgcaggtgaaac
tggtgtctccgagtcttatgccgaagctcgggaaagctgggagcttgcag
agcaggcaggcaattgtgcacagccttgcgcataccgagagttgggctat
cgacttatcctgggtaaaaccttagcagtgtggtctggatggttgtcgga
tagttgt-aatatgctgttgagtttggccgtgattttctctgtgggactg
ctctgcaggacataattgctcggtttggcaagcaagaatctatgccaagg
gagttcttcacagactttgtgaaggtggctcaagatgaaggtagacactt
cacgcttctggcgactaggttgcaagagctaggatccttctatggagctt
tacctgctcacgacggcctttg----------------------------
------------------------------------------------*
